// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

@JavaClass("java.beans.PropertyChangeSupport", implements: Serializable.self)
open class PropertyChangeSupport: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaObject?, environment: JNIEnvironment? = nil)

    /// Java method `addPropertyChangeListener`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.addPropertyChangeListener(java.lang.String,java.beans.PropertyChangeListener)
    /// ```
  @JavaMethod
  open func addPropertyChangeListener(_ arg0: String, _ arg1: PropertyChangeListener?)

    /// Java method `addPropertyChangeListener`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.addPropertyChangeListener(java.beans.PropertyChangeListener)
    /// ```
  @JavaMethod
  open func addPropertyChangeListener(_ arg0: PropertyChangeListener?)

    /// Java method `removePropertyChangeListener`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.removePropertyChangeListener(java.lang.String,java.beans.PropertyChangeListener)
    /// ```
  @JavaMethod
  open func removePropertyChangeListener(_ arg0: String, _ arg1: PropertyChangeListener?)

    /// Java method `removePropertyChangeListener`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.removePropertyChangeListener(java.beans.PropertyChangeListener)
    /// ```
  @JavaMethod
  open func removePropertyChangeListener(_ arg0: PropertyChangeListener?)

    /// Java method `firePropertyChange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.firePropertyChange(java.lang.String,java.lang.Object,java.lang.Object)
    /// ```
  @JavaMethod
  open func firePropertyChange(_ arg0: String, _ arg1: JavaObject?, _ arg2: JavaObject?)

    /// Java method `firePropertyChange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.firePropertyChange(java.lang.String,int,int)
    /// ```
  @JavaMethod
  open func firePropertyChange(_ arg0: String, _ arg1: Int32, _ arg2: Int32)

    /// Java method `firePropertyChange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.firePropertyChange(java.beans.PropertyChangeEvent)
    /// ```
  @JavaMethod
  open func firePropertyChange(_ arg0: PropertyChangeEvent?)

    /// Java method `firePropertyChange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.firePropertyChange(java.lang.String,boolean,boolean)
    /// ```
  @JavaMethod
  open func firePropertyChange(_ arg0: String, _ arg1: Bool, _ arg2: Bool)

    /// Java method `fireIndexedPropertyChange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.fireIndexedPropertyChange(java.lang.String,int,boolean,boolean)
    /// ```
  @JavaMethod
  open func fireIndexedPropertyChange(_ arg0: String, _ arg1: Int32, _ arg2: Bool, _ arg3: Bool)

    /// Java method `fireIndexedPropertyChange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.fireIndexedPropertyChange(java.lang.String,int,java.lang.Object,java.lang.Object)
    /// ```
  @JavaMethod
  open func fireIndexedPropertyChange(_ arg0: String, _ arg1: Int32, _ arg2: JavaObject?, _ arg3: JavaObject?)

    /// Java method `fireIndexedPropertyChange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeSupport.fireIndexedPropertyChange(java.lang.String,int,int,int)
    /// ```
  @JavaMethod
  open func fireIndexedPropertyChange(_ arg0: String, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

    /// Java method `hasListeners`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.beans.PropertyChangeSupport.hasListeners(java.lang.String)
    /// ```
  @JavaMethod
  open func hasListeners(_ arg0: String) -> Bool

    /// Java method `getPropertyChangeListeners`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.beans.PropertyChangeListener[] java.beans.PropertyChangeSupport.getPropertyChangeListeners()
    /// ```
  @JavaMethod
  open func getPropertyChangeListeners() -> [PropertyChangeListener?]

    /// Java method `getPropertyChangeListeners`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.beans.PropertyChangeListener[] java.beans.PropertyChangeSupport.getPropertyChangeListeners(java.lang.String)
    /// ```
  @JavaMethod
  open func getPropertyChangeListeners(_ arg0: String) -> [PropertyChangeListener?]
}
