// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.beans.PropertyChangeListenerProxy", implements: PropertyChangeListener.self)
open class PropertyChangeListenerProxy: JavaObject<JavaBeans.PropertyChangeListener> {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: PropertyChangeListener?, environment: JNIEnvironment? = nil)

    /// Java method `getPropertyName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.beans.PropertyChangeListenerProxy.getPropertyName()
    /// ```
  @JavaMethod
  open func getPropertyName() -> String

    /// Java method `propertyChange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.beans.PropertyChangeListenerProxy.propertyChange(java.beans.PropertyChangeEvent)
    /// ```
  @JavaMethod
  open func propertyChange(_ arg0: PropertyChangeEvent?)
}
