// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.beans.PropertyChangeListener")
public struct PropertyChangeListener {
  /// Java method `propertyChange`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.beans.PropertyChangeListener.propertyChange(java.beans.PropertyChangeEvent)
  /// ```
@JavaMethod
  public func propertyChange(_ arg0: PropertyChangeEvent?)
}
