// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaInterface("java.io.Externalizable", extends: Serializable.self)
public struct Externalizable {
  /// Java method `writeExternal`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.Externalizable.writeExternal(java.io.ObjectOutput) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeExternal(_ arg0: ObjectOutput?) throws

  /// Java method `readExternal`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.Externalizable.readExternal(java.io.ObjectInput) throws java.io.IOException,java.lang.ClassNotFoundException
  /// ```
@JavaMethod
  public func readExternal(_ arg0: ObjectInput?) throws
}
