// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaInterface("java.io.FilenameFilter")
public struct FilenameFilter {
  @JavaMethod
  public func accept(_ arg0: File?, _ arg1: String) -> Bool
}
