// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaInterface("java.io.FilenameFilter")
public struct FilenameFilter {
  /// Java method `accept`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.io.FilenameFilter.accept(java.io.File,java.lang.String)
  /// ```
@JavaMethod
  public func accept(_ arg0: File?, _ arg1: String) -> Bool
}
