// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.io.FileInputStream")
open class FileInputStream: InputStream {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: FileDescriptor?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil) throws

    /// Java method `readAllBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public byte[] java.io.FileInputStream.readAllBytes() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func readAllBytes() throws -> [Int8]

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.FileInputStream.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func close() throws

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.FileInputStream.read(byte[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws -> Int32

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.FileInputStream.read(byte[]) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read(_ arg0: [Int8]) throws -> Int32

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.FileInputStream.read() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read() throws -> Int32

    /// Java method `readNBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public byte[] java.io.FileInputStream.readNBytes(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func readNBytes(_ arg0: Int32) throws -> [Int8]

    /// Java method `transferTo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.io.FileInputStream.transferTo(java.io.OutputStream) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func transferTo(_ arg0: OutputStream?) throws -> Int64

    /// Java method `skip`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.io.FileInputStream.skip(long) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func skip(_ arg0: Int64) throws -> Int64

    /// Java method `available`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.FileInputStream.available() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func available() throws -> Int32

    /// Java method `getFD`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.io.FileDescriptor java.io.FileInputStream.getFD() throws java.io.IOException
    /// ```
  @JavaMethod
  open func getFD() throws -> FileDescriptor!
}
