// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.io.FilterInputStream")
open class FilterInputStream: InputStream {
  /// Java method `reset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterInputStream.reset() throws java.io.IOException
  /// ```
@JavaMethod
  open override func reset() throws

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterInputStream.close() throws java.io.IOException
  /// ```
@JavaMethod
  open override func close() throws

  /// Java method `mark`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterInputStream.mark(int)
  /// ```
@JavaMethod
  open override func mark(_ arg0: Int32)

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.io.FilterInputStream.read() throws java.io.IOException
  /// ```
@JavaMethod
  open override func read() throws -> Int32

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.io.FilterInputStream.read(byte[]) throws java.io.IOException
  /// ```
@JavaMethod
  open override func read(_ arg0: [Int8]) throws -> Int32

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.io.FilterInputStream.read(byte[],int,int) throws java.io.IOException
  /// ```
@JavaMethod
  open override func read(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws -> Int32

  /// Java method `skip`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.io.FilterInputStream.skip(long) throws java.io.IOException
  /// ```
@JavaMethod
  open override func skip(_ arg0: Int64) throws -> Int64

  /// Java method `available`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.io.FilterInputStream.available() throws java.io.IOException
  /// ```
@JavaMethod
  open override func available() throws -> Int32

  /// Java method `markSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.io.FilterInputStream.markSupported()
  /// ```
@JavaMethod
  open override func markSupported() -> Bool
}
