// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.io.FilterWriter")
open class FilterWriter: Writer {
  /// Java method `flush`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterWriter.flush() throws java.io.IOException
  /// ```
@JavaMethod
  open override func flush() throws

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterWriter.write(java.lang.String,int,int) throws java.io.IOException
  /// ```
@JavaMethod
  open override func write(_ arg0: String, _ arg1: Int32, _ arg2: Int32) throws

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterWriter.write(char[],int,int) throws java.io.IOException
  /// ```
@JavaMethod
  open override func write(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) throws

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterWriter.write(int) throws java.io.IOException
  /// ```
@JavaMethod
  open override func write(_ arg0: Int32) throws

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterWriter.close() throws java.io.IOException
  /// ```
@JavaMethod
  open override func close() throws
}
