// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.io.FilterReader")
open class FilterReader: Reader {
  /// Java method `ready`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.io.FilterReader.ready() throws java.io.IOException
  /// ```
@JavaMethod
  open override func ready() throws -> Bool

  /// Java method `reset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterReader.reset() throws java.io.IOException
  /// ```
@JavaMethod
  open override func reset() throws

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterReader.close() throws java.io.IOException
  /// ```
@JavaMethod
  open override func close() throws

  /// Java method `mark`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.io.FilterReader.mark(int) throws java.io.IOException
  /// ```
@JavaMethod
  open override func mark(_ arg0: Int32) throws

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.io.FilterReader.read(char[],int,int) throws java.io.IOException
  /// ```
@JavaMethod
  open override func read(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) throws -> Int32

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.io.FilterReader.read() throws java.io.IOException
  /// ```
@JavaMethod
  open override func read() throws -> Int32

  /// Java method `skip`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.io.FilterReader.skip(long) throws java.io.IOException
  /// ```
@JavaMethod
  open override func skip(_ arg0: Int64) throws -> Int64

  /// Java method `markSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.io.FilterReader.markSupported()
  /// ```
@JavaMethod
  open override func markSupported() -> Bool
}
