// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.io.LineNumberReader")
open class LineNumberReader: BufferedReader {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Reader?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Reader?, _ arg1: Int32, environment: JNIEnvironment? = nil)

    /// Java method `reset`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.LineNumberReader.reset() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func reset() throws

    /// Java method `readLine`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.io.LineNumberReader.readLine() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func readLine() throws -> String

    /// Java method `mark`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.LineNumberReader.mark(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func mark(_ arg0: Int32) throws

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.LineNumberReader.read(char[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) throws -> Int32

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.LineNumberReader.read() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read() throws -> Int32

    /// Java method `skip`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.io.LineNumberReader.skip(long) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func skip(_ arg0: Int64) throws -> Int64

    /// Java method `getLineNumber`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.LineNumberReader.getLineNumber()
    /// ```
  @JavaMethod
  open func getLineNumber() -> Int32

    /// Java method `setLineNumber`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.LineNumberReader.setLineNumber(int)
    /// ```
  @JavaMethod
  open func setLineNumber(_ arg0: Int32)
}
