// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.io.ObjectInputStream", implements: ObjectInput.self, ObjectStreamConstants.self)
open class ObjectInputStream: InputStream {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: InputStream?, environment: JNIEnvironment? = nil) throws

    /// Java method `readStreamHeader`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void java.io.ObjectInputStream.readStreamHeader() throws java.io.IOException,java.io.StreamCorruptedException
    /// ```
  @JavaMethod
  open func readStreamHeader() throws

    /// Java method `readObjectOverride`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.lang.Object java.io.ObjectInputStream.readObjectOverride() throws java.io.IOException,java.lang.ClassNotFoundException
    /// ```
  @JavaMethod
  open func readObjectOverride() throws -> JavaObject!

    /// Java method `readUnshared`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.Object java.io.ObjectInputStream.readUnshared() throws java.io.IOException,java.lang.ClassNotFoundException
    /// ```
  @JavaMethod
  open func readUnshared() throws -> JavaObject!

    /// Java method `resolveObject`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.lang.Object java.io.ObjectInputStream.resolveObject(java.lang.Object) throws java.io.IOException
    /// ```
  @JavaMethod
  open func resolveObject(_ arg0: JavaObject?) throws -> JavaObject!

    /// Java method `resolveProxyClass`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.lang.Class<?> java.io.ObjectInputStream.resolveProxyClass(java.lang.String[]) throws java.io.IOException,java.lang.ClassNotFoundException
    /// ```
  @JavaMethod
  open func resolveProxyClass(_ arg0: [String]) throws -> JavaClass<JavaObject>!

    /// Java method `readClassDescriptor`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.io.ObjectStreamClass java.io.ObjectInputStream.readClassDescriptor() throws java.io.IOException,java.lang.ClassNotFoundException
    /// ```
  @JavaMethod
  open func readClassDescriptor() throws -> ObjectStreamClass!

    /// Java method `registerValidation`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.ObjectInputStream.registerValidation(java.io.ObjectInputValidation,int) throws java.io.NotActiveException,java.io.InvalidObjectException
    /// ```
  @JavaMethod
  open func registerValidation(_ arg0: ObjectInputValidation?, _ arg1: Int32) throws

    /// Java method `enableResolveObject`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected boolean java.io.ObjectInputStream.enableResolveObject(boolean)
    /// ```
  @JavaMethod
  open func enableResolveObject(_ arg0: Bool) -> Bool

    /// Java method `resolveClass`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.lang.Class<?> java.io.ObjectInputStream.resolveClass(java.io.ObjectStreamClass) throws java.io.IOException,java.lang.ClassNotFoundException
    /// ```
  @JavaMethod
  open func resolveClass(_ arg0: ObjectStreamClass?) throws -> JavaClass<JavaObject>!

    /// Java method `defaultReadObject`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.ObjectInputStream.defaultReadObject() throws java.io.IOException,java.lang.ClassNotFoundException
    /// ```
  @JavaMethod
  open func defaultReadObject() throws

    /// Java method `readObject`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.Object java.io.ObjectInputStream.readObject() throws java.io.IOException,java.lang.ClassNotFoundException
    /// ```
  @JavaMethod
  open func readObject() throws -> JavaObject!

    /// Java method `readFields`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.io.ObjectInputStream$GetField java.io.ObjectInputStream.readFields() throws java.io.IOException,java.lang.ClassNotFoundException
    /// ```
  @JavaMethod
  open func readFields() throws -> ObjectInputStream.GetField!

    /// Java method `readLine`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.io.ObjectInputStream.readLine() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readLine() throws -> String

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.ObjectInputStream.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func close() throws

    /// Java method `readInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectInputStream.readInt() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readInt() throws -> Int32

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectInputStream.read(byte[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws -> Int32

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectInputStream.read() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read() throws -> Int32

    /// Java method `available`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectInputStream.available() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func available() throws -> Int32

    /// Java method `readUTF`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.io.ObjectInputStream.readUTF() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readUTF() throws -> String

    /// Java method `readLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.io.ObjectInputStream.readLong() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readLong() throws -> Int64

    /// Java method `readByte`.
    ///
    /// ### Java method signature
    /// ```java
    /// public byte java.io.ObjectInputStream.readByte() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readByte() throws -> Int8

    /// Java method `readShort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public short java.io.ObjectInputStream.readShort() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readShort() throws -> Int16

    /// Java method `readUnsignedShort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectInputStream.readUnsignedShort() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readUnsignedShort() throws -> Int32

    /// Java method `readChar`.
    ///
    /// ### Java method signature
    /// ```java
    /// public char java.io.ObjectInputStream.readChar() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readChar() throws -> UInt16

    /// Java method `readFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public float java.io.ObjectInputStream.readFloat() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readFloat() throws -> Float

    /// Java method `readDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public double java.io.ObjectInputStream.readDouble() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readDouble() throws -> Double

    /// Java method `readFully`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.ObjectInputStream.readFully(byte[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func readFully(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws

    /// Java method `readFully`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.ObjectInputStream.readFully(byte[]) throws java.io.IOException
    /// ```
  @JavaMethod
  open func readFully(_ arg0: [Int8]) throws

    /// Java method `skipBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectInputStream.skipBytes(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func skipBytes(_ arg0: Int32) throws -> Int32

    /// Java method `readBoolean`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.io.ObjectInputStream.readBoolean() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readBoolean() throws -> Bool

    /// Java method `readUnsignedByte`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectInputStream.readUnsignedByte() throws java.io.IOException
    /// ```
  @JavaMethod
  open func readUnsignedByte() throws -> Int32
}
