// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaInterface("java.io.ObjectInputValidation")
public struct ObjectInputValidation {
  /// Java method `validateObject`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.ObjectInputValidation.validateObject() throws java.io.InvalidObjectException
  /// ```
@JavaMethod
  public func validateObject() throws
}
