// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.io.ObjectStreamField")
open class ObjectStreamField: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: JavaClass<JavaObject>?, _ arg2: Bool, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: JavaClass<JavaObject>?, environment: JNIEnvironment? = nil)

    /// Java method `getName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.io.ObjectStreamField.getName()
    /// ```
  @JavaMethod
  open func getName() -> String

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.io.ObjectStreamField.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `isPrimitive`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.io.ObjectStreamField.isPrimitive()
    /// ```
  @JavaMethod
  open func isPrimitive() -> Bool

    /// Java method `compareTo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectStreamField.compareTo(java.lang.Object)
    /// ```
  @JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

    /// Java method `getType`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.Class<?> java.io.ObjectStreamField.getType()
    /// ```
  @JavaMethod
  open func getType() -> JavaClass<JavaObject>!

    /// Java method `getTypeCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public char java.io.ObjectStreamField.getTypeCode()
    /// ```
  @JavaMethod
  open func getTypeCode() -> UInt16

    /// Java method `getTypeString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.io.ObjectStreamField.getTypeString()
    /// ```
  @JavaMethod
  open func getTypeString() -> String

    /// Java method `getOffset`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.ObjectStreamField.getOffset()
    /// ```
  @JavaMethod
  open func getOffset() -> Int32

    /// Java method `setOffset`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void java.io.ObjectStreamField.setOffset(int)
    /// ```
  @JavaMethod
  open func setOffset(_ arg0: Int32)

    /// Java method `isUnshared`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.io.ObjectStreamField.isUnshared()
    /// ```
  @JavaMethod
  open func isUnshared() -> Bool
}
