// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("java.io.ObjectInputValidation")
public struct ObjectInputValidation {
  @JavaMethod
  public func validateObject() throws
}
