// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaInterface("java.io.ObjectOutput", extends: DataOutput.self)
public struct ObjectOutput {
  /// Java method `flush`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.ObjectOutput.flush() throws java.io.IOException
  /// ```
@JavaMethod
  public func flush() throws

  /// Java method `writeObject`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.ObjectOutput.writeObject(java.lang.Object) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeObject(_ arg0: JavaObject?) throws

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.ObjectOutput.write(byte[],int,int) throws java.io.IOException
  /// ```
@JavaMethod
  public func write(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.ObjectOutput.write(byte[]) throws java.io.IOException
  /// ```
@JavaMethod
  public func write(_ arg0: [Int8]) throws

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.ObjectOutput.write(int) throws java.io.IOException
  /// ```
@JavaMethod
  public func write(_ arg0: Int32) throws

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.ObjectOutput.close() throws java.io.IOException
  /// ```
@JavaMethod
  public func close() throws

  /// Java method `writeInt`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeInt(int) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeInt(_ arg0: Int32) throws

  /// Java method `writeUTF`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeUTF(java.lang.String) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeUTF(_ arg0: String) throws

  /// Java method `writeLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeLong(long) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeLong(_ arg0: Int64) throws

  /// Java method `writeByte`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeByte(int) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeByte(_ arg0: Int32) throws

  /// Java method `writeShort`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeShort(int) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeShort(_ arg0: Int32) throws

  /// Java method `writeBytes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeBytes(java.lang.String) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeBytes(_ arg0: String) throws

  /// Java method `writeChar`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeChar(int) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeChar(_ arg0: Int32) throws

  /// Java method `writeFloat`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeFloat(float) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeFloat(_ arg0: Float) throws

  /// Java method `writeDouble`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeDouble(double) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeDouble(_ arg0: Double) throws

  /// Java method `writeBoolean`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeBoolean(boolean) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeBoolean(_ arg0: Bool) throws

  /// Java method `writeChars`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.io.DataOutput.writeChars(java.lang.String) throws java.io.IOException
  /// ```
@JavaMethod
  public func writeChars(_ arg0: String) throws
}
