// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.io.PipedReader")
open class PipedReader: Reader {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: PipedWriter?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: PipedWriter?, _ arg1: Int32, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

    /// Java method `ready`.
    ///
    /// ### Java method signature
    /// ```java
    /// public synchronized boolean java.io.PipedReader.ready() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func ready() throws -> Bool

    /// Java method `connect`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.PipedReader.connect(java.io.PipedWriter) throws java.io.IOException
    /// ```
  @JavaMethod
  open func connect(_ arg0: PipedWriter?) throws

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.PipedReader.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func close() throws

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public synchronized int java.io.PipedReader.read() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read() throws -> Int32

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public synchronized int java.io.PipedReader.read(char[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) throws -> Int32
}
