// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.io.PushbackReader")
open class PushbackReader: FilterReader {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Reader?, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Reader?, environment: JNIEnvironment? = nil)

    /// Java method `ready`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.io.PushbackReader.ready() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func ready() throws -> Bool

    /// Java method `reset`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.PushbackReader.reset() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func reset() throws

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.PushbackReader.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func close() throws

    /// Java method `mark`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.PushbackReader.mark(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func mark(_ arg0: Int32) throws

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.PushbackReader.read() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read() throws -> Int32

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.PushbackReader.read(char[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) throws -> Int32

    /// Java method `skip`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.io.PushbackReader.skip(long) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func skip(_ arg0: Int64) throws -> Int64

    /// Java method `markSupported`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.io.PushbackReader.markSupported()
    /// ```
  @JavaMethod
  open override func markSupported() -> Bool

    /// Java method `unread`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.PushbackReader.unread(char[]) throws java.io.IOException
    /// ```
  @JavaMethod
  open func unread(_ arg0: [UInt16]) throws

    /// Java method `unread`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.PushbackReader.unread(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func unread(_ arg0: Int32) throws

    /// Java method `unread`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.PushbackReader.unread(char[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func unread(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) throws
}
