// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.io.SequenceInputStream")
open class SequenceInputStream: InputStream {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: InputStream?, _ arg1: InputStream?, environment: JNIEnvironment? = nil)

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.io.SequenceInputStream.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func close() throws

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.SequenceInputStream.read(byte[],int,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws -> Int32

    /// Java method `read`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.SequenceInputStream.read() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func read() throws -> Int32

    /// Java method `transferTo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.io.SequenceInputStream.transferTo(java.io.OutputStream) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func transferTo(_ arg0: OutputStream?) throws -> Int64

    /// Java method `available`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.io.SequenceInputStream.available() throws java.io.IOException
    /// ```
  @JavaMethod
  open override func available() throws -> Int32
}
