// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

extension Base64 {
  @JavaClass("java.util.Base64$Encoder")
  open class Encoder: JavaObject {
    /// Java method `encodeToString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Base64$Encoder.encodeToString(byte[])
    /// ```
  @JavaMethod
  open func encodeToString(_ arg0: [Int8]) -> String

    /// Java method `withoutPadding`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Base64$Encoder java.util.Base64$Encoder.withoutPadding()
    /// ```
  @JavaMethod
  open func withoutPadding() -> Base64.Encoder!

    /// Java method `wrap`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.io.OutputStream java.util.Base64$Encoder.wrap(java.io.OutputStream)
    /// ```
  @JavaMethod
  open func wrap(_ arg0: OutputStream?) -> OutputStream!

    /// Java method `encode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.Base64$Encoder.encode(byte[],byte[])
    /// ```
  @JavaMethod
  open func encode(_ arg0: [Int8], _ arg1: [Int8]) -> Int32

    /// Java method `encode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public byte[] java.util.Base64$Encoder.encode(byte[])
    /// ```
  @JavaMethod
  open func encode(_ arg0: [Int8]) -> [Int8]

    /// Java method `encode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.nio.ByteBuffer java.util.Base64$Encoder.encode(java.nio.ByteBuffer)
    /// ```
  @JavaMethod
  open func encode(_ arg0: ByteBuffer?) -> ByteBuffer!
  }
}
