// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

extension Base64 {
  @JavaClass("java.util.Base64$Decoder")
  open class Decoder: JavaObject {
    /// Java method `decode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public byte[] java.util.Base64$Decoder.decode(byte[])
    /// ```
  @JavaMethod
  open func decode(_ arg0: [Int8]) -> [Int8]

    /// Java method `decode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.nio.ByteBuffer java.util.Base64$Decoder.decode(java.nio.ByteBuffer)
    /// ```
  @JavaMethod
  open func decode(_ arg0: ByteBuffer?) -> ByteBuffer!

    /// Java method `decode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public byte[] java.util.Base64$Decoder.decode(java.lang.String)
    /// ```
  @JavaMethod
  open func decode(_ arg0: String) -> [Int8]

    /// Java method `decode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.Base64$Decoder.decode(byte[],byte[])
    /// ```
  @JavaMethod
  open func decode(_ arg0: [Int8], _ arg1: [Int8]) -> Int32

    /// Java method `wrap`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.io.InputStream java.util.Base64$Decoder.wrap(java.io.InputStream)
    /// ```
  @JavaMethod
  open func wrap(_ arg0: InputStream?) -> InputStream!
  }
}
