// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

@JavaClass("java.util.Formatter", implements: Closeable.self, Flushable.self)
open class Formatter: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Appendable?, _ arg1: Locale?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Locale?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Appendable?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, _ arg1: String, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: Charset?, _ arg2: Locale?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: Locale?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: OutputStream?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: OutputStream?, _ arg1: String, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: OutputStream?, _ arg1: String, _ arg2: Locale?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: OutputStream?, _ arg1: Charset?, _ arg2: Locale?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, _ arg1: String, _ arg2: Locale?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, _ arg1: Charset?, _ arg2: Locale?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: PrintStream?, environment: JNIEnvironment? = nil)

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Formatter.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `flush`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.util.Formatter.flush()
    /// ```
  @JavaMethod
  open func flush()

    /// Java method `format`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Formatter java.util.Formatter.format(java.lang.String,java.lang.Object...)
    /// ```
  @JavaMethod
  open func format(_ arg0: String, _ arg1: [JavaObject?]) -> Formatter!

    /// Java method `format`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Formatter java.util.Formatter.format(java.util.Locale,java.lang.String,java.lang.Object...)
    /// ```
  @JavaMethod
  open func format(_ arg0: Locale?, _ arg1: String, _ arg2: [JavaObject?]) -> Formatter!

    /// Java method `locale`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale java.util.Formatter.locale()
    /// ```
  @JavaMethod
  open func locale() -> Locale!

    /// Java method `out`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.Appendable java.util.Formatter.out()
    /// ```
  @JavaMethod
  open func out() -> Appendable!

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.util.Formatter.close()
    /// ```
  @JavaMethod
  open func close()

    /// Java method `ioException`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.io.IOException java.util.Formatter.ioException()
    /// ```
  @JavaMethod
  open func ioException() -> IOException!
}
