// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import JavaLangIO
import SwiftJava

@JavaClass("java.util.Locale", implements: Cloneable.self, Serializable.self)
open class Locale: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.util.Locale.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.util.Locale.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.Locale.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `clone`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.Object java.util.Locale.clone()
    /// ```
  @JavaMethod
  open override func clone() -> JavaObject!

    /// Java method `getLanguage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getLanguage()
    /// ```
  @JavaMethod
  open func getLanguage() -> String

    /// Java method `getDisplayName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.util.Locale.getDisplayName()
    /// ```
  @JavaMethod
  open func getDisplayName() -> String

    /// Java method `getDisplayName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getDisplayName(java.util.Locale)
    /// ```
  @JavaMethod
  open func getDisplayName(_ arg0: Locale?) -> String

    /// Java method `getUnicodeLocaleType`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getUnicodeLocaleType(java.lang.String)
    /// ```
  @JavaMethod
  open func getUnicodeLocaleType(_ arg0: String) -> String

    /// Java method `getCountry`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getCountry()
    /// ```
  @JavaMethod
  open func getCountry() -> String

    /// Java method `stripExtensions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale java.util.Locale.stripExtensions()
    /// ```
  @JavaMethod
  open func stripExtensions() -> Locale!

    /// Java method `hasExtensions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.util.Locale.hasExtensions()
    /// ```
  @JavaMethod
  open func hasExtensions() -> Bool

    /// Java method `getVariant`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getVariant()
    /// ```
  @JavaMethod
  open func getVariant() -> String

    /// Java method `getScript`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getScript()
    /// ```
  @JavaMethod
  open func getScript() -> String

    /// Java method `getUnicodeLocaleAttributes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Set<java.lang.String> java.util.Locale.getUnicodeLocaleAttributes()
    /// ```
  @JavaMethod
  open func getUnicodeLocaleAttributes() -> JavaSet<JavaString>!

    /// Java method `getUnicodeLocaleKeys`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Set<java.lang.String> java.util.Locale.getUnicodeLocaleKeys()
    /// ```
  @JavaMethod
  open func getUnicodeLocaleKeys() -> JavaSet<JavaString>!

    /// Java method `getDisplayLanguage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.util.Locale.getDisplayLanguage()
    /// ```
  @JavaMethod
  open func getDisplayLanguage() -> String

    /// Java method `getDisplayLanguage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getDisplayLanguage(java.util.Locale)
    /// ```
  @JavaMethod
  open func getDisplayLanguage(_ arg0: Locale?) -> String

    /// Java method `getDisplayScript`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getDisplayScript(java.util.Locale)
    /// ```
  @JavaMethod
  open func getDisplayScript(_ arg0: Locale?) -> String

    /// Java method `getDisplayScript`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getDisplayScript()
    /// ```
  @JavaMethod
  open func getDisplayScript() -> String

    /// Java method `getDisplayCountry`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getDisplayCountry(java.util.Locale)
    /// ```
  @JavaMethod
  open func getDisplayCountry(_ arg0: Locale?) -> String

    /// Java method `getDisplayCountry`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.util.Locale.getDisplayCountry()
    /// ```
  @JavaMethod
  open func getDisplayCountry() -> String

    /// Java method `getDisplayVariant`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getDisplayVariant(java.util.Locale)
    /// ```
  @JavaMethod
  open func getDisplayVariant(_ arg0: Locale?) -> String

    /// Java method `getDisplayVariant`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.util.Locale.getDisplayVariant()
    /// ```
  @JavaMethod
  open func getDisplayVariant() -> String

    /// Java method `getExtension`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getExtension(char)
    /// ```
  @JavaMethod
  open func getExtension(_ arg0: UInt16) -> String

    /// Java method `getExtensionKeys`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Set<java.lang.Character> java.util.Locale.getExtensionKeys()
    /// ```
  @JavaMethod
  open func getExtensionKeys() -> JavaSet<JavaCharacter>!

    /// Java method `toLanguageTag`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.toLanguageTag()
    /// ```
  @JavaMethod
  open func toLanguageTag() -> String

    /// Java method `getISO3Language`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getISO3Language() throws java.util.MissingResourceException
    /// ```
  @JavaMethod
  open func getISO3Language() throws -> String

    /// Java method `getISO3Country`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale.getISO3Country() throws java.util.MissingResourceException
    /// ```
  @JavaMethod
  open func getISO3Country() throws -> String
}
extension Locale {
  @JavaClass("java.util.Locale$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `clear`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.clear()
    /// ```
  @JavaMethod
  open func clear() -> Locale.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale java.util.Locale$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> Locale!

    /// Java method `setLocale`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.setLocale(java.util.Locale)
    /// ```
  @JavaMethod
  open func setLocale(_ arg0: Locale?) -> Locale.Builder!

    /// Java method `setLanguageTag`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.setLanguageTag(java.lang.String)
    /// ```
  @JavaMethod
  open func setLanguageTag(_ arg0: String) -> Locale.Builder!

    /// Java method `setLanguage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.setLanguage(java.lang.String)
    /// ```
  @JavaMethod
  open func setLanguage(_ arg0: String) -> Locale.Builder!

    /// Java method `setScript`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.setScript(java.lang.String)
    /// ```
  @JavaMethod
  open func setScript(_ arg0: String) -> Locale.Builder!

    /// Java method `setRegion`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.setRegion(java.lang.String)
    /// ```
  @JavaMethod
  open func setRegion(_ arg0: String) -> Locale.Builder!

    /// Java method `setVariant`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.setVariant(java.lang.String)
    /// ```
  @JavaMethod
  open func setVariant(_ arg0: String) -> Locale.Builder!

    /// Java method `setExtension`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.setExtension(char,java.lang.String)
    /// ```
  @JavaMethod
  open func setExtension(_ arg0: UInt16, _ arg1: String) -> Locale.Builder!

    /// Java method `setUnicodeLocaleKeyword`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.setUnicodeLocaleKeyword(java.lang.String,java.lang.String)
    /// ```
  @JavaMethod
  open func setUnicodeLocaleKeyword(_ arg0: String, _ arg1: String) -> Locale.Builder!

    /// Java method `addUnicodeLocaleAttribute`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.addUnicodeLocaleAttribute(java.lang.String)
    /// ```
  @JavaMethod
  open func addUnicodeLocaleAttribute(_ arg0: String) -> Locale.Builder!

    /// Java method `removeUnicodeLocaleAttribute`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.removeUnicodeLocaleAttribute(java.lang.String)
    /// ```
  @JavaMethod
  open func removeUnicodeLocaleAttribute(_ arg0: String) -> Locale.Builder!

    /// Java method `clearExtensions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Locale$Builder java.util.Locale$Builder.clearExtensions()
    /// ```
  @JavaMethod
  open func clearExtensions() -> Locale.Builder!
  }
}
extension Locale {
  @JavaClass("java.util.Locale$LanguageRange")
  open class LanguageRange: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: Double, environment: JNIEnvironment? = nil)

    /// Java method `getRange`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale$LanguageRange.getRange()
    /// ```
  @JavaMethod
  open func getRange() -> String

    /// Java method `getWeight`.
    ///
    /// ### Java method signature
    /// ```java
    /// public double java.util.Locale$LanguageRange.getWeight()
    /// ```
  @JavaMethod
  open func getWeight() -> Double

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.util.Locale$LanguageRange.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.Locale$LanguageRange.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.Locale$LanguageRange.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32
  }
}
extension JavaClass<Locale.LanguageRange> {
  @JavaStaticField(isFinal: true)
  public var MAX_WEIGHT: Double

  @JavaStaticField(isFinal: true)
  public var MIN_WEIGHT: Double

    /// Java method `mapEquivalents`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.List<java.util.Locale$LanguageRange> java.util.Locale$LanguageRange.mapEquivalents(java.util.List<java.util.Locale$LanguageRange>,java.util.Map<java.lang.String, java.util.List<java.lang.String>>)
    /// ```
  @JavaStaticMethod
  public func mapEquivalents(_ arg0: List<Locale.LanguageRange>?, _ arg1: Map<JavaString, List<JavaString>>?) -> List<Locale.LanguageRange>!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.List<java.util.Locale$LanguageRange> java.util.Locale$LanguageRange.parse(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func parse(_ arg0: String) -> List<Locale.LanguageRange>!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.List<java.util.Locale$LanguageRange> java.util.Locale$LanguageRange.parse(java.lang.String,java.util.Map<java.lang.String, java.util.List<java.lang.String>>)
    /// ```
  @JavaStaticMethod
  public func parse(_ arg0: String, _ arg1: Map<JavaString, List<JavaString>>?) -> List<Locale.LanguageRange>!
}
extension JavaClass<Locale> {
  @JavaStaticField(isFinal: true)
  public var ENGLISH: Locale!

  @JavaStaticField(isFinal: true)
  public var FRENCH: Locale!

  @JavaStaticField(isFinal: true)
  public var GERMAN: Locale!

  @JavaStaticField(isFinal: true)
  public var ITALIAN: Locale!

  @JavaStaticField(isFinal: true)
  public var JAPANESE: Locale!

  @JavaStaticField(isFinal: true)
  public var KOREAN: Locale!

  @JavaStaticField(isFinal: true)
  public var CHINESE: Locale!

  @JavaStaticField(isFinal: true)
  public var SIMPLIFIED_CHINESE: Locale!

  @JavaStaticField(isFinal: true)
  public var TRADITIONAL_CHINESE: Locale!

  @JavaStaticField(isFinal: true)
  public var FRANCE: Locale!

  @JavaStaticField(isFinal: true)
  public var GERMANY: Locale!

  @JavaStaticField(isFinal: true)
  public var ITALY: Locale!

  @JavaStaticField(isFinal: true)
  public var JAPAN: Locale!

  @JavaStaticField(isFinal: true)
  public var KOREA: Locale!

  @JavaStaticField(isFinal: true)
  public var UK: Locale!

  @JavaStaticField(isFinal: true)
  public var US: Locale!

  @JavaStaticField(isFinal: true)
  public var CANADA: Locale!

  @JavaStaticField(isFinal: true)
  public var CANADA_FRENCH: Locale!

  @JavaStaticField(isFinal: true)
  public var ROOT: Locale!

  @JavaStaticField(isFinal: true)
  public var CHINA: Locale!

  @JavaStaticField(isFinal: true)
  public var PRC: Locale!

  @JavaStaticField(isFinal: true)
  public var TAIWAN: Locale!

  @JavaStaticField(isFinal: true)
  public var PRIVATE_USE_EXTENSION: UInt16

  @JavaStaticField(isFinal: true)
  public var UNICODE_LOCALE_EXTENSION: UInt16

    /// Java method `getDefault`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.Locale java.util.Locale.getDefault()
    /// ```
  @JavaStaticMethod
  public func getDefault() -> Locale!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.Locale java.util.Locale.of(java.lang.String,java.lang.String)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: String, _ arg1: String) -> Locale!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.Locale java.util.Locale.of(java.lang.String,java.lang.String,java.lang.String)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: String, _ arg1: String, _ arg2: String) -> Locale!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.Locale java.util.Locale.of(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: String) -> Locale!

    /// Java method `lookup`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.Locale java.util.Locale.lookup(java.util.List<java.util.Locale$LanguageRange>,java.util.Collection<java.util.Locale>)
    /// ```
  @JavaStaticMethod
  public func lookup(_ arg0: List<Locale.LanguageRange>?, _ arg1: JavaCollection<Locale>?) -> Locale!

    /// Java method `filter`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.List<java.util.Locale> java.util.Locale.filter(java.util.List<java.util.Locale$LanguageRange>,java.util.Collection<java.util.Locale>)
    /// ```
  @JavaStaticMethod
  public func filter(_ arg0: List<Locale.LanguageRange>?, _ arg1: JavaCollection<Locale>?) -> List<Locale>!

    /// Java method `getAvailableLocales`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.Locale[] java.util.Locale.getAvailableLocales()
    /// ```
  @JavaStaticMethod
  public func getAvailableLocales() -> [Locale?]

    /// Java method `setDefault`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static synchronized void java.util.Locale.setDefault(java.util.Locale)
    /// ```
  @JavaStaticMethod
  public func setDefault(_ arg0: Locale?)

    /// Java method `filterTags`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.List<java.lang.String> java.util.Locale.filterTags(java.util.List<java.util.Locale$LanguageRange>,java.util.Collection<java.lang.String>)
    /// ```
  @JavaStaticMethod
  public func filterTags(_ arg0: List<Locale.LanguageRange>?, _ arg1: JavaCollection<JavaString>?) -> List<JavaString>!

    /// Java method `lookupTag`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.lang.String java.util.Locale.lookupTag(java.util.List<java.util.Locale$LanguageRange>,java.util.Collection<java.lang.String>)
    /// ```
  @JavaStaticMethod
  public func lookupTag(_ arg0: List<Locale.LanguageRange>?, _ arg1: JavaCollection<JavaString>?) -> String

    /// Java method `getISOCountries`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.lang.String[] java.util.Locale.getISOCountries()
    /// ```
  @JavaStaticMethod
  public func getISOCountries() -> [String]

    /// Java method `getISOLanguages`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.lang.String[] java.util.Locale.getISOLanguages()
    /// ```
  @JavaStaticMethod
  public func getISOLanguages() -> [String]

    /// Java method `caseFoldLanguageTag`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.lang.String java.util.Locale.caseFoldLanguageTag(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func caseFoldLanguageTag(_ arg0: String) -> String

    /// Java method `forLanguageTag`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.util.Locale java.util.Locale.forLanguageTag(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func forLanguageTag(_ arg0: String) -> Locale!
}
