// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension Random {
  @JavaInterface("java.util.random.RandomGenerator")
  public struct Generator {
    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double) -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble()
    /// ```
  @JavaMethod
  public func nextDouble() -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double,double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt()
    /// ```
  @JavaMethod
  public func nextInt() -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int,int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32, _ arg1: Int32) -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32) -> Int32

    /// Java method `nextBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default void java.util.random.RandomGenerator.nextBytes(byte[])
    /// ```
  @JavaMethod
  public func nextBytes(_ arg0: [Int8])

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long,long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64, _ arg1: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract long java.util.random.RandomGenerator.nextLong()
    /// ```
  @JavaMethod
  public func nextLong() -> Int64

    /// Java method `nextBoolean`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.nextBoolean()
    /// ```
  @JavaMethod
  public func nextBoolean() -> Bool

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat()
    /// ```
  @JavaMethod
  public func nextFloat() -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float) -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float,float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float, _ arg1: Float) -> Float

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian(double,double)
    /// ```
  @JavaMethod
  public func nextGaussian(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian()
    /// ```
  @JavaMethod
  public func nextGaussian() -> Double

    /// Java method `isDeprecated`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.isDeprecated()
    /// ```
  @JavaMethod
  public func isDeprecated() -> Bool

    /// Java method `nextExponential`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextExponential()
    /// ```
  @JavaMethod
  public func nextExponential() -> Double
  }
}
extension Random.Generator {
  @JavaInterface("java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator", extends: Random.Generator.LeapableGenerator.self)
  public struct ArbitrarilyJumpableGenerator {
    /// Java method `copyAndJump`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.copyAndJump(double)
    /// ```
  @JavaMethod
  public func copyAndJump(_ arg0: Double) -> Random.Generator.ArbitrarilyJumpableGenerator!

    /// Java method `jumpPowerOfTwo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.jumpPowerOfTwo(int)
    /// ```
  @JavaMethod
  public func jumpPowerOfTwo(_ arg0: Int32)

    /// Java method `copy`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator$LeapableGenerator java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.copy()
    /// ```
  @JavaMethod
  public func copy() -> Random.Generator.LeapableGenerator!

    /// Java method `copy`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator$JumpableGenerator java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.copy()
    /// ```
  @JavaMethod
  public func copy() -> Random.Generator.JumpableGenerator!

    /// Java method `copy`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.copy()
    /// ```
  @JavaMethod
  public func copy() -> Random.Generator.ArbitrarilyJumpableGenerator!

    /// Java method `jump`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.jump(double)
    /// ```
  @JavaMethod
  public func jump(_ arg0: Double)

    /// Java method `jump`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default void java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.jump()
    /// ```
  @JavaMethod
  public func jump()

    /// Java method `leap`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default void java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.leap()
    /// ```
  @JavaMethod
  public func leap()

    /// Java method `leapDistance`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract double java.util.random.RandomGenerator$LeapableGenerator.leapDistance()
    /// ```
  @JavaMethod
  public func leapDistance() -> Double

    /// Java method `copyAndLeap`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator$JumpableGenerator java.util.random.RandomGenerator$LeapableGenerator.copyAndLeap()
    /// ```
  @JavaMethod
  public func copyAndLeap() -> Random.Generator.JumpableGenerator!

    /// Java method `jumpDistance`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract double java.util.random.RandomGenerator$JumpableGenerator.jumpDistance()
    /// ```
  @JavaMethod
  public func jumpDistance() -> Double

    /// Java method `copyAndJump`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator java.util.random.RandomGenerator$JumpableGenerator.copyAndJump()
    /// ```
  @JavaMethod
  public func copyAndJump() -> Random.Generator!

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double) -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble()
    /// ```
  @JavaMethod
  public func nextDouble() -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double,double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt()
    /// ```
  @JavaMethod
  public func nextInt() -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int,int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32, _ arg1: Int32) -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32) -> Int32

    /// Java method `nextBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default void java.util.random.RandomGenerator.nextBytes(byte[])
    /// ```
  @JavaMethod
  public func nextBytes(_ arg0: [Int8])

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long,long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64, _ arg1: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract long java.util.random.RandomGenerator.nextLong()
    /// ```
  @JavaMethod
  public func nextLong() -> Int64

    /// Java method `nextBoolean`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.nextBoolean()
    /// ```
  @JavaMethod
  public func nextBoolean() -> Bool

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat()
    /// ```
  @JavaMethod
  public func nextFloat() -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float) -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float,float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float, _ arg1: Float) -> Float

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian(double,double)
    /// ```
  @JavaMethod
  public func nextGaussian(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian()
    /// ```
  @JavaMethod
  public func nextGaussian() -> Double

    /// Java method `isDeprecated`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.isDeprecated()
    /// ```
  @JavaMethod
  public func isDeprecated() -> Bool

    /// Java method `nextExponential`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextExponential()
    /// ```
  @JavaMethod
  public func nextExponential() -> Double
  }
}
extension JavaClass<Random.Generator.ArbitrarilyJumpableGenerator> {
  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator java.util.random.RandomGenerator$ArbitrarilyJumpableGenerator.of(java.lang.String)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: String) -> Random.Generator.ArbitrarilyJumpableGenerator!
}
extension Random.Generator {
  @JavaInterface("java.util.random.RandomGenerator$JumpableGenerator", extends: Random.Generator.StreamableGenerator.self)
  public struct JumpableGenerator {
    /// Java method `jumpDistance`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract double java.util.random.RandomGenerator$JumpableGenerator.jumpDistance()
    /// ```
  @JavaMethod
  public func jumpDistance() -> Double

    /// Java method `copyAndJump`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator java.util.random.RandomGenerator$JumpableGenerator.copyAndJump()
    /// ```
  @JavaMethod
  public func copyAndJump() -> Random.Generator!

    /// Java method `copy`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.util.random.RandomGenerator$JumpableGenerator java.util.random.RandomGenerator$JumpableGenerator.copy()
    /// ```
  @JavaMethod
  public func copy() -> Random.Generator.JumpableGenerator!

    /// Java method `jump`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void java.util.random.RandomGenerator$JumpableGenerator.jump()
    /// ```
  @JavaMethod
  public func jump()

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double) -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble()
    /// ```
  @JavaMethod
  public func nextDouble() -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double,double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt()
    /// ```
  @JavaMethod
  public func nextInt() -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int,int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32, _ arg1: Int32) -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32) -> Int32

    /// Java method `nextBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default void java.util.random.RandomGenerator.nextBytes(byte[])
    /// ```
  @JavaMethod
  public func nextBytes(_ arg0: [Int8])

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long,long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64, _ arg1: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract long java.util.random.RandomGenerator.nextLong()
    /// ```
  @JavaMethod
  public func nextLong() -> Int64

    /// Java method `nextBoolean`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.nextBoolean()
    /// ```
  @JavaMethod
  public func nextBoolean() -> Bool

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat()
    /// ```
  @JavaMethod
  public func nextFloat() -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float) -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float,float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float, _ arg1: Float) -> Float

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian(double,double)
    /// ```
  @JavaMethod
  public func nextGaussian(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian()
    /// ```
  @JavaMethod
  public func nextGaussian() -> Double

    /// Java method `isDeprecated`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.isDeprecated()
    /// ```
  @JavaMethod
  public func isDeprecated() -> Bool

    /// Java method `nextExponential`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextExponential()
    /// ```
  @JavaMethod
  public func nextExponential() -> Double
  }
}
extension JavaClass<Random.Generator.JumpableGenerator> {
  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.random.RandomGenerator$JumpableGenerator java.util.random.RandomGenerator$JumpableGenerator.of(java.lang.String)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: String) -> Random.Generator.JumpableGenerator!
}
extension Random.Generator {
  @JavaInterface("java.util.random.RandomGenerator$LeapableGenerator", extends: Random.Generator.JumpableGenerator.self)
  public struct LeapableGenerator {
    /// Java method `leapDistance`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract double java.util.random.RandomGenerator$LeapableGenerator.leapDistance()
    /// ```
  @JavaMethod
  public func leapDistance() -> Double

    /// Java method `copyAndLeap`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator$JumpableGenerator java.util.random.RandomGenerator$LeapableGenerator.copyAndLeap()
    /// ```
  @JavaMethod
  public func copyAndLeap() -> Random.Generator.JumpableGenerator!

    /// Java method `copy`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator$JumpableGenerator java.util.random.RandomGenerator$LeapableGenerator.copy()
    /// ```
  @JavaMethod
  public func copy() -> Random.Generator.JumpableGenerator!

    /// Java method `copy`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.util.random.RandomGenerator$LeapableGenerator java.util.random.RandomGenerator$LeapableGenerator.copy()
    /// ```
  @JavaMethod
  public func copy() -> Random.Generator.LeapableGenerator!

    /// Java method `leap`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void java.util.random.RandomGenerator$LeapableGenerator.leap()
    /// ```
  @JavaMethod
  public func leap()

    /// Java method `jumpDistance`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract double java.util.random.RandomGenerator$JumpableGenerator.jumpDistance()
    /// ```
  @JavaMethod
  public func jumpDistance() -> Double

    /// Java method `copyAndJump`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default java.util.random.RandomGenerator java.util.random.RandomGenerator$JumpableGenerator.copyAndJump()
    /// ```
  @JavaMethod
  public func copyAndJump() -> Random.Generator!

    /// Java method `jump`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void java.util.random.RandomGenerator$JumpableGenerator.jump()
    /// ```
  @JavaMethod
  public func jump()

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double) -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble()
    /// ```
  @JavaMethod
  public func nextDouble() -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double,double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt()
    /// ```
  @JavaMethod
  public func nextInt() -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int,int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32, _ arg1: Int32) -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32) -> Int32

    /// Java method `nextBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default void java.util.random.RandomGenerator.nextBytes(byte[])
    /// ```
  @JavaMethod
  public func nextBytes(_ arg0: [Int8])

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long,long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64, _ arg1: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract long java.util.random.RandomGenerator.nextLong()
    /// ```
  @JavaMethod
  public func nextLong() -> Int64

    /// Java method `nextBoolean`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.nextBoolean()
    /// ```
  @JavaMethod
  public func nextBoolean() -> Bool

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat()
    /// ```
  @JavaMethod
  public func nextFloat() -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float) -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float,float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float, _ arg1: Float) -> Float

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian(double,double)
    /// ```
  @JavaMethod
  public func nextGaussian(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian()
    /// ```
  @JavaMethod
  public func nextGaussian() -> Double

    /// Java method `isDeprecated`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.isDeprecated()
    /// ```
  @JavaMethod
  public func isDeprecated() -> Bool

    /// Java method `nextExponential`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextExponential()
    /// ```
  @JavaMethod
  public func nextExponential() -> Double
  }
}
extension JavaClass<Random.Generator.LeapableGenerator> {
  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.random.RandomGenerator$LeapableGenerator java.util.random.RandomGenerator$LeapableGenerator.of(java.lang.String)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: String) -> Random.Generator.LeapableGenerator!
}
extension Random.Generator {
  @JavaInterface("java.util.random.RandomGenerator$SplittableGenerator", extends: Random.Generator.StreamableGenerator.self)
  public struct SplittableGenerator {
    /// Java method `split`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.util.random.RandomGenerator$SplittableGenerator java.util.random.RandomGenerator$SplittableGenerator.split()
    /// ```
  @JavaMethod
  public func split() -> Random.Generator.SplittableGenerator!

    /// Java method `split`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.util.random.RandomGenerator$SplittableGenerator java.util.random.RandomGenerator$SplittableGenerator.split(java.util.random.RandomGenerator$SplittableGenerator)
    /// ```
  @JavaMethod
  public func split(_ arg0: Random.Generator.SplittableGenerator?) -> Random.Generator.SplittableGenerator!

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double) -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble()
    /// ```
  @JavaMethod
  public func nextDouble() -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double,double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt()
    /// ```
  @JavaMethod
  public func nextInt() -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int,int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32, _ arg1: Int32) -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32) -> Int32

    /// Java method `nextBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default void java.util.random.RandomGenerator.nextBytes(byte[])
    /// ```
  @JavaMethod
  public func nextBytes(_ arg0: [Int8])

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long,long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64, _ arg1: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract long java.util.random.RandomGenerator.nextLong()
    /// ```
  @JavaMethod
  public func nextLong() -> Int64

    /// Java method `nextBoolean`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.nextBoolean()
    /// ```
  @JavaMethod
  public func nextBoolean() -> Bool

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat()
    /// ```
  @JavaMethod
  public func nextFloat() -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float) -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float,float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float, _ arg1: Float) -> Float

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian(double,double)
    /// ```
  @JavaMethod
  public func nextGaussian(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian()
    /// ```
  @JavaMethod
  public func nextGaussian() -> Double

    /// Java method `isDeprecated`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.isDeprecated()
    /// ```
  @JavaMethod
  public func isDeprecated() -> Bool

    /// Java method `nextExponential`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextExponential()
    /// ```
  @JavaMethod
  public func nextExponential() -> Double
  }
}
extension JavaClass<Random.Generator.SplittableGenerator> {
  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.random.RandomGenerator$SplittableGenerator java.util.random.RandomGenerator$SplittableGenerator.of(java.lang.String)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: String) -> Random.Generator.SplittableGenerator!
}
extension Random.Generator {
  @JavaInterface("java.util.random.RandomGenerator$StreamableGenerator", extends: Random.Generator.self)
  public struct StreamableGenerator {
    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double) -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble()
    /// ```
  @JavaMethod
  public func nextDouble() -> Double

    /// Java method `nextDouble`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextDouble(double,double)
    /// ```
  @JavaMethod
  public func nextDouble(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt()
    /// ```
  @JavaMethod
  public func nextInt() -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int,int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32, _ arg1: Int32) -> Int32

    /// Java method `nextInt`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default int java.util.random.RandomGenerator.nextInt(int)
    /// ```
  @JavaMethod
  public func nextInt(_ arg0: Int32) -> Int32

    /// Java method `nextBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default void java.util.random.RandomGenerator.nextBytes(byte[])
    /// ```
  @JavaMethod
  public func nextBytes(_ arg0: [Int8])

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long,long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64, _ arg1: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default long java.util.random.RandomGenerator.nextLong(long)
    /// ```
  @JavaMethod
  public func nextLong(_ arg0: Int64) -> Int64

    /// Java method `nextLong`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract long java.util.random.RandomGenerator.nextLong()
    /// ```
  @JavaMethod
  public func nextLong() -> Int64

    /// Java method `nextBoolean`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.nextBoolean()
    /// ```
  @JavaMethod
  public func nextBoolean() -> Bool

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat()
    /// ```
  @JavaMethod
  public func nextFloat() -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float) -> Float

    /// Java method `nextFloat`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default float java.util.random.RandomGenerator.nextFloat(float,float)
    /// ```
  @JavaMethod
  public func nextFloat(_ arg0: Float, _ arg1: Float) -> Float

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian(double,double)
    /// ```
  @JavaMethod
  public func nextGaussian(_ arg0: Double, _ arg1: Double) -> Double

    /// Java method `nextGaussian`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextGaussian()
    /// ```
  @JavaMethod
  public func nextGaussian() -> Double

    /// Java method `isDeprecated`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default boolean java.util.random.RandomGenerator.isDeprecated()
    /// ```
  @JavaMethod
  public func isDeprecated() -> Bool

    /// Java method `nextExponential`.
    ///
    /// ### Java method signature
    /// ```java
    /// public default double java.util.random.RandomGenerator.nextExponential()
    /// ```
  @JavaMethod
  public func nextExponential() -> Double
  }
}
extension JavaClass<Random.Generator.StreamableGenerator> {
  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.random.RandomGenerator$StreamableGenerator java.util.random.RandomGenerator$StreamableGenerator.of(java.lang.String)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: String) -> Random.Generator.StreamableGenerator!
}
extension JavaClass<Random.Generator> {
  /// Java method `getDefault`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.random.RandomGenerator java.util.random.RandomGenerator.getDefault()
  /// ```
@JavaStaticMethod
  public func getDefault() -> Random.Generator!

  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.random.RandomGenerator java.util.random.RandomGenerator.of(java.lang.String)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: String) -> Random.Generator!
}
