// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import JavaLangIO
import SwiftJava

@JavaClass("java.util.UUID", implements: Serializable.self)
open class UUID: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int64, _ arg1: Int64, environment: JNIEnvironment? = nil)

    /// Java method `getLeastSignificantBits`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.util.UUID.getLeastSignificantBits()
    /// ```
  @JavaMethod
  open func getLeastSignificantBits() -> Int64

    /// Java method `getMostSignificantBits`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.util.UUID.getMostSignificantBits()
    /// ```
  @JavaMethod
  open func getMostSignificantBits() -> Int64

    /// Java method `clockSequence`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.UUID.clockSequence()
    /// ```
  @JavaMethod
  open func clockSequence() -> Int32

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.util.UUID.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.util.UUID.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `version`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.UUID.version()
    /// ```
  @JavaMethod
  open func version() -> Int32

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.UUID.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `compareTo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.UUID.compareTo(java.lang.Object)
    /// ```
  @JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

    /// Java method `compareTo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.UUID.compareTo(java.util.UUID)
    /// ```
  @JavaMethod
  open func compareTo(_ arg0: UUID?) -> Int32

    /// Java method `timestamp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.util.UUID.timestamp()
    /// ```
  @JavaMethod
  open func timestamp() -> Int64

    /// Java method `node`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long java.util.UUID.node()
    /// ```
  @JavaMethod
  open func node() -> Int64

    /// Java method `variant`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.util.UUID.variant()
    /// ```
  @JavaMethod
  open func variant() -> Int32
}
extension JavaClass<UUID> {
  /// Java method `randomUUID`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.UUID java.util.UUID.randomUUID()
  /// ```
@JavaStaticMethod
  public func randomUUID() -> UUID!

  /// Java method `nameUUIDFromBytes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.UUID java.util.UUID.nameUUIDFromBytes(byte[])
  /// ```
@JavaStaticMethod
  public func nameUUIDFromBytes(_ arg0: [Int8]) -> UUID!

  /// Java method `fromString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.UUID java.util.UUID.fromString(java.lang.String)
  /// ```
@JavaStaticMethod
  public func fromString(_ arg0: String) -> UUID!
}
