// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.lang.AutoCloseable")
public struct AutoCloseable {
  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.lang.AutoCloseable.close() throws java.lang.Exception
  /// ```
@JavaMethod
  public func close() throws
}
