// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.lang.constant.Constable")
public struct Constable {
  /// Java method `describeConstable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.util.Optional<? extends java.lang.constant.ConstantDesc> java.lang.constant.Constable.describeConstable()
  /// ```
@JavaMethod
  public func describeConstable() -> JavaOptional<ConstantDesc>!

  public func describeConstableOptional() -> ConstantDesc? {
    Optional(javaOptional: describeConstable())
  }
}
