// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaRuntime

@JavaClass("java.lang.EnumConstantNotPresentException")
open class EnumConstantNotPresentException: RuntimeException {
  @JavaMethod
  open func constantName() -> String
}
