// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaUtilFunction
import CSwiftJavaJNI

@JavaInterface("java.lang.Iterable")
public struct Iterable<T: AnyJavaObject> {
  @JavaMethod
  public func iterator() -> JavaIterator<T>!

  @JavaMethod
  public func forEach(_ arg0: JavaConsumer<T>?)
}
