// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangReflect
import SwiftJava

@JavaClass("java.lang.Package")
open class Package: JavaObject {
  /// Java method `getName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.lang.Package.getName()
  /// ```
@JavaMethod
  open func getName() -> String

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.lang.Package.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.lang.Package.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `isSealed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.lang.Package.isSealed()
  /// ```
@JavaMethod
  open func isSealed() -> Bool

  /// Java method `isAnnotationPresent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.lang.Package.isAnnotationPresent(java.lang.Class<? extends java.lang.annotation.Annotation>)
  /// ```
@JavaMethod
  open func isAnnotationPresent(_ arg0: JavaClass<Annotation>?) -> Bool

  /// Java method `getAnnotation`.
  ///
  /// ### Java method signature
  /// ```java
  /// public <A extends java.lang.annotation.Annotation> A java.lang.Package.getAnnotation(java.lang.Class<A>)
  /// ```
@JavaMethod(typeErasedResult: "A!")
  open func getAnnotation<A: AnyJavaObject>(_ arg0: JavaClass<A>?) -> A!

  /// Java method `getAnnotationsByType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public <A extends java.lang.annotation.Annotation> A[] java.lang.Package.getAnnotationsByType(java.lang.Class<A>)
  /// ```
@JavaMethod
  open func getAnnotationsByType<A: AnyJavaObject>(_ arg0: JavaClass<A>?) -> [A?]

  /// Java method `getAnnotations`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.annotation.Annotation[] java.lang.Package.getAnnotations()
  /// ```
@JavaMethod
  open func getAnnotations() -> [Annotation?]

  /// Java method `getDeclaredAnnotation`.
  ///
  /// ### Java method signature
  /// ```java
  /// public <A extends java.lang.annotation.Annotation> A java.lang.Package.getDeclaredAnnotation(java.lang.Class<A>)
  /// ```
@JavaMethod(typeErasedResult: "A!")
  open func getDeclaredAnnotation<A: AnyJavaObject>(_ arg0: JavaClass<A>?) -> A!

  /// Java method `getDeclaredAnnotationsByType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public <A extends java.lang.annotation.Annotation> A[] java.lang.Package.getDeclaredAnnotationsByType(java.lang.Class<A>)
  /// ```
@JavaMethod
  open func getDeclaredAnnotationsByType<A: AnyJavaObject>(_ arg0: JavaClass<A>?) -> [A?]

  /// Java method `getDeclaredAnnotations`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.annotation.Annotation[] java.lang.Package.getDeclaredAnnotations()
  /// ```
@JavaMethod
  open func getDeclaredAnnotations() -> [Annotation?]

  /// Java method `getSpecificationTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.lang.Package.getSpecificationTitle()
  /// ```
@JavaMethod
  open func getSpecificationTitle() -> String

  /// Java method `getSpecificationVersion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.lang.Package.getSpecificationVersion()
  /// ```
@JavaMethod
  open func getSpecificationVersion() -> String

  /// Java method `getSpecificationVendor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.lang.Package.getSpecificationVendor()
  /// ```
@JavaMethod
  open func getSpecificationVendor() -> String

  /// Java method `getImplementationTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.lang.Package.getImplementationTitle()
  /// ```
@JavaMethod
  open func getImplementationTitle() -> String

  /// Java method `getImplementationVersion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.lang.Package.getImplementationVersion()
  /// ```
@JavaMethod
  open func getImplementationVersion() -> String

  /// Java method `getImplementationVendor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.lang.Package.getImplementationVendor()
  /// ```
@JavaMethod
  open func getImplementationVendor() -> String

  /// Java method `isCompatibleWith`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.lang.Package.isCompatibleWith(java.lang.String) throws java.lang.NumberFormatException
  /// ```
@JavaMethod
  open func isCompatibleWith(_ arg0: String) throws -> Bool
}
extension JavaClass<Package> {
  /// Java method `getPackage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.Package java.lang.Package.getPackage(java.lang.String)
  /// ```
@JavaStaticMethod
  public func getPackage(_ arg0: String) -> Package!

  /// Java method `getPackages`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.Package[] java.lang.Package.getPackages()
  /// ```
@JavaStaticMethod
  public func getPackages() -> [Package?]
}
