// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.lang.ProcessHandle", extends: Comparable<ProcessHandle>.self)
public struct ProcessHandle {
  /// Java method `supportsNormalTermination`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.lang.ProcessHandle.supportsNormalTermination()
  /// ```
@JavaMethod
  public func supportsNormalTermination() -> Bool

  /// Java method `destroyForcibly`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.lang.ProcessHandle.destroyForcibly()
  /// ```
@JavaMethod
  public func destroyForcibly() -> Bool

  /// Java method `parent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.util.Optional<java.lang.ProcessHandle> java.lang.ProcessHandle.parent()
  /// ```
@JavaMethod
  public func parent() -> JavaOptional<ProcessHandle>!

  public func parentOptional() -> ProcessHandle? {
    Optional(javaOptional: parent())
  }

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.lang.ProcessHandle.equals(java.lang.Object)
  /// ```
@JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.lang.ProcessHandle.hashCode()
  /// ```
@JavaMethod
  public func hashCode() -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.lang.ProcessHandle.compareTo(java.lang.Object)
  /// ```
@JavaMethod
  public func compareTo(_ arg0: JavaObject?) -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.lang.ProcessHandle.compareTo(java.lang.ProcessHandle)
  /// ```
@JavaMethod
  public func compareTo(_ arg0: ProcessHandle?) -> Int32

  /// Java method `info`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.ProcessHandle$Info java.lang.ProcessHandle.info()
  /// ```
@JavaMethod
  public func info() -> ProcessHandle.Info!

  /// Java method `isAlive`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.lang.ProcessHandle.isAlive()
  /// ```
@JavaMethod
  public func isAlive() -> Bool

  /// Java method `destroy`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.lang.ProcessHandle.destroy()
  /// ```
@JavaMethod
  public func destroy() -> Bool

  /// Java method `pid`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.lang.ProcessHandle.pid()
  /// ```
@JavaMethod
  public func pid() -> Int64
}
extension JavaClass<ProcessHandle> {
  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.Optional<java.lang.ProcessHandle> java.lang.ProcessHandle.of(long)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: Int64) -> JavaOptional<ProcessHandle>!

  public func ofOptional(_ arg0: Int64) -> ProcessHandle? {
    Optional(javaOptional: of(arg0))
  }

  /// Java method `current`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.ProcessHandle java.lang.ProcessHandle.current()
  /// ```
@JavaStaticMethod
  public func current() -> ProcessHandle!
}
