// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaClass("java.lang.RuntimePermission")
open class RuntimePermission: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)
}
