// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.lang.ThreadDeath")
open class ThreadDeath: JavaError {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
