// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension Thread {
  @JavaInterface("java.lang.Thread$UncaughtExceptionHandler")
  public struct UncaughtExceptionHandler {
  @JavaMethod
  public func uncaughtException(_ arg0: Thread?, _ arg1: Throwable?)
  }
}
