// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.channels.spi.AbstractSelectionKey")
open class AbstractSelectionKey: SelectionKey {
  /// Java method `cancel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void java.nio.channels.spi.AbstractSelectionKey.cancel()
  /// ```
@JavaMethod
  open override func cancel()

  /// Java method `isValid`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean java.nio.channels.spi.AbstractSelectionKey.isValid()
  /// ```
@JavaMethod
  open override func isValid() -> Bool
}
