// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.channels.spi.AbstractInterruptibleChannel", implements: Channel.self, InterruptibleChannel.self)
open class AbstractInterruptibleChannel: JavaObject {
  /// Java method `implCloseChannel`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected abstract void java.nio.channels.spi.AbstractInterruptibleChannel.implCloseChannel() throws java.io.IOException
  /// ```
@JavaMethod
  open func implCloseChannel() throws

  /// Java method `begin`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected final void java.nio.channels.spi.AbstractInterruptibleChannel.begin()
  /// ```
@JavaMethod
  open func begin()

  /// Java method `end`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected final void java.nio.channels.spi.AbstractInterruptibleChannel.end(boolean) throws java.nio.channels.AsynchronousCloseException
  /// ```
@JavaMethod
  open func end(_ arg0: Bool) throws

  /// Java method `isOpen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean java.nio.channels.spi.AbstractInterruptibleChannel.isOpen()
  /// ```
@JavaMethod
  open func isOpen() -> Bool

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void java.nio.channels.spi.AbstractInterruptibleChannel.close() throws java.io.IOException
  /// ```
@JavaMethod
  open func close() throws
}
