// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.channels.spi.AbstractSelectableChannel")
open class AbstractSelectableChannel: SelectableChannel {
  /// Java method `isBlocking`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean java.nio.channels.spi.AbstractSelectableChannel.isBlocking()
  /// ```
@JavaMethod
  open override func isBlocking() -> Bool

  /// Java method `implCloseSelectableChannel`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected abstract void java.nio.channels.spi.AbstractSelectableChannel.implCloseSelectableChannel() throws java.io.IOException
  /// ```
@JavaMethod
  open func implCloseSelectableChannel() throws

  /// Java method `implConfigureBlocking`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected abstract void java.nio.channels.spi.AbstractSelectableChannel.implConfigureBlocking(boolean) throws java.io.IOException
  /// ```
@JavaMethod
  open func implConfigureBlocking(_ arg0: Bool) throws

  /// Java method `keyFor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.channels.SelectionKey java.nio.channels.spi.AbstractSelectableChannel.keyFor(java.nio.channels.Selector)
  /// ```
@JavaMethod
  open override func keyFor(_ arg0: Selector?) -> SelectionKey!

  /// Java method `implCloseChannel`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected final void java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel() throws java.io.IOException
  /// ```
@JavaMethod
  open override func implCloseChannel() throws

  /// Java method `blockingLock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.Object java.nio.channels.spi.AbstractSelectableChannel.blockingLock()
  /// ```
@JavaMethod
  open override func blockingLock() -> JavaObject!

  /// Java method `configureBlocking`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.channels.SelectableChannel java.nio.channels.spi.AbstractSelectableChannel.configureBlocking(boolean) throws java.io.IOException
  /// ```
@JavaMethod
  open override func configureBlocking(_ arg0: Bool) throws -> SelectableChannel!

  /// Java method `isRegistered`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean java.nio.channels.spi.AbstractSelectableChannel.isRegistered()
  /// ```
@JavaMethod
  open override func isRegistered() -> Bool

  /// Java method `register`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.channels.SelectionKey java.nio.channels.spi.AbstractSelectableChannel.register(java.nio.channels.Selector,int,java.lang.Object) throws java.nio.channels.ClosedChannelException
  /// ```
@JavaMethod
  open override func register(_ arg0: Selector?, _ arg1: Int32, _ arg2: JavaObject?) throws -> SelectionKey!

  /// Java method `provider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.channels.spi.SelectorProvider java.nio.channels.spi.AbstractSelectableChannel.provider()
  /// ```
@JavaMethod
  open override func provider() -> SelectorProvider!
}
