// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.channels.AsynchronousFileChannel", implements: AsynchronousChannel.self)
open class AsynchronousFileChannel: JavaObject {
  /// Java method `size`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.nio.channels.AsynchronousFileChannel.size() throws java.io.IOException
  /// ```
@JavaMethod
  open func size() throws -> Int64

  /// Java method `lock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract <A> void java.nio.channels.AsynchronousFileChannel.lock(long,long,boolean,A,java.nio.channels.CompletionHandler<java.nio.channels.FileLock, ? super A>)
  /// ```
@JavaMethod
  open func lock<A: AnyJavaObject>(_ arg0: Int64, _ arg1: Int64, _ arg2: Bool, _ arg3: A?, _ arg4: CompletionHandler<FileLock, JavaObject>?)

  /// Java method `lock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final <A> void java.nio.channels.AsynchronousFileChannel.lock(A,java.nio.channels.CompletionHandler<java.nio.channels.FileLock, ? super A>)
  /// ```
@JavaMethod
  open func lock<A: AnyJavaObject>(_ arg0: A?, _ arg1: CompletionHandler<FileLock, JavaObject>?)

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract <A> void java.nio.channels.AsynchronousFileChannel.write(java.nio.ByteBuffer,long,A,java.nio.channels.CompletionHandler<java.lang.Integer, ? super A>)
  /// ```
@JavaMethod
  open func write<A: AnyJavaObject>(_ arg0: ByteBuffer?, _ arg1: Int64, _ arg2: A?, _ arg3: CompletionHandler<JavaInteger, JavaObject>?)

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract <A> void java.nio.channels.AsynchronousFileChannel.read(java.nio.ByteBuffer,long,A,java.nio.channels.CompletionHandler<java.lang.Integer, ? super A>)
  /// ```
@JavaMethod
  open func read<A: AnyJavaObject>(_ arg0: ByteBuffer?, _ arg1: Int64, _ arg2: A?, _ arg3: CompletionHandler<JavaInteger, JavaObject>?)

  /// Java method `tryLock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.channels.FileLock java.nio.channels.AsynchronousFileChannel.tryLock() throws java.io.IOException
  /// ```
@JavaMethod
  open func tryLock() throws -> FileLock!

  /// Java method `tryLock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.FileLock java.nio.channels.AsynchronousFileChannel.tryLock(long,long,boolean) throws java.io.IOException
  /// ```
@JavaMethod
  open func tryLock(_ arg0: Int64, _ arg1: Int64, _ arg2: Bool) throws -> FileLock!

  /// Java method `force`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.nio.channels.AsynchronousFileChannel.force(boolean) throws java.io.IOException
  /// ```
@JavaMethod
  open func force(_ arg0: Bool) throws

  /// Java method `truncate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.AsynchronousFileChannel java.nio.channels.AsynchronousFileChannel.truncate(long) throws java.io.IOException
  /// ```
@JavaMethod
  open func truncate(_ arg0: Int64) throws -> AsynchronousFileChannel!
}
extension JavaClass<AsynchronousFileChannel> {
  /// Java method `open`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.nio.channels.AsynchronousFileChannel java.nio.channels.AsynchronousFileChannel.open(java.nio.file.Path,java.nio.file.OpenOption...) throws java.io.IOException
  /// ```
@JavaStaticMethod
  public func open(_ arg0: Path?, _ arg1: [OpenOption?]) throws -> AsynchronousFileChannel!
}
