// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaRuntime

@JavaInterface("java.nio.channels.AsynchronousChannel", extends: Channel.self)
public struct AsynchronousChannel {
  @JavaMethod
  public func close() throws

  @JavaMethod
  public func isOpen() -> Bool
}
