// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaClass("java.nio.file.AtomicMoveNotSupportedException")
open class AtomicMoveNotSupportedException: FileSystemException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: String, environment: JNIEnvironment? = nil)
}
