// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("java.nio.file.attribute.AttributeView")
public struct AttributeView {
  @JavaMethod
  public func name() -> String
}
