// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.nio.file.attribute.AttributeView")
public struct AttributeView {
  /// Java method `name`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.nio.file.attribute.AttributeView.name()
  /// ```
@JavaMethod
  public func name() -> String
}
