// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.BufferUnderflowException")
open class BufferUnderflowException: RuntimeException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
