// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import SwiftJava

extension Charset {
  @JavaMethod
  public func newDecoder() -> CharsetDecoder!

  @JavaMethod
  public func decode(_ arg0: ByteBuffer?) -> CharBuffer!

  @JavaMethod
  public func newEncoder() -> CharsetEncoder!

  @JavaMethod
  public func encode(_ arg0: CharBuffer?) -> ByteBuffer!
}
extension JavaClass<Charset> {
  @JavaStaticMethod
  public func forName(_ arg0: String, _ arg1: Charset?) -> Charset!

  @JavaStaticMethod
  public func forName(_ arg0: String) -> Charset!

  @JavaStaticMethod
  public func defaultCharset() -> Charset!

  @JavaStaticMethod
  public func isSupported(_ arg0: String) -> Bool
}
