// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.charset.CharsetDecoder")
open class CharsetDecoder: JavaObject {
  /// Java method `averageCharsPerByte`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final float java.nio.charset.CharsetDecoder.averageCharsPerByte()
  /// ```
@JavaMethod
  open func averageCharsPerByte() -> Float

  /// Java method `decodeLoop`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected abstract java.nio.charset.CoderResult java.nio.charset.CharsetDecoder.decodeLoop(java.nio.ByteBuffer,java.nio.CharBuffer)
  /// ```
@JavaMethod
  open func decodeLoop(_ arg0: ByteBuffer?, _ arg1: CharBuffer?) -> CoderResult!

  /// Java method `isAutoDetecting`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.nio.charset.CharsetDecoder.isAutoDetecting()
  /// ```
@JavaMethod
  open func isAutoDetecting() -> Bool

  /// Java method `isCharsetDetected`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.nio.charset.CharsetDecoder.isCharsetDetected()
  /// ```
@JavaMethod
  open func isCharsetDetected() -> Bool

  /// Java method `detectedCharset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.nio.charset.Charset java.nio.charset.CharsetDecoder.detectedCharset()
  /// ```
@JavaMethod
  open func detectedCharset() -> Charset!

  /// Java method `reset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.charset.CharsetDecoder java.nio.charset.CharsetDecoder.reset()
  /// ```
@JavaMethod
  open func reset() -> CharsetDecoder!

  /// Java method `maxCharsPerByte`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final float java.nio.charset.CharsetDecoder.maxCharsPerByte()
  /// ```
@JavaMethod
  open func maxCharsPerByte() -> Float

  /// Java method `onMalformedInput`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.charset.CharsetDecoder java.nio.charset.CharsetDecoder.onMalformedInput(java.nio.charset.CodingErrorAction)
  /// ```
@JavaMethod
  open func onMalformedInput(_ arg0: CodingErrorAction?) -> CharsetDecoder!

  /// Java method `onUnmappableCharacter`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.charset.CharsetDecoder java.nio.charset.CharsetDecoder.onUnmappableCharacter(java.nio.charset.CodingErrorAction)
  /// ```
@JavaMethod
  open func onUnmappableCharacter(_ arg0: CodingErrorAction?) -> CharsetDecoder!

  /// Java method `decode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.charset.CoderResult java.nio.charset.CharsetDecoder.decode(java.nio.ByteBuffer,java.nio.CharBuffer,boolean)
  /// ```
@JavaMethod
  open func decode(_ arg0: ByteBuffer?, _ arg1: CharBuffer?, _ arg2: Bool) -> CoderResult!

  /// Java method `decode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.CharBuffer java.nio.charset.CharsetDecoder.decode(java.nio.ByteBuffer) throws java.nio.charset.CharacterCodingException
  /// ```
@JavaMethod
  open func decode(_ arg0: ByteBuffer?) throws -> CharBuffer!

  /// Java method `flush`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.charset.CoderResult java.nio.charset.CharsetDecoder.flush(java.nio.CharBuffer)
  /// ```
@JavaMethod
  open func flush(_ arg0: CharBuffer?) -> CoderResult!

  /// Java method `charset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.charset.Charset java.nio.charset.CharsetDecoder.charset()
  /// ```
@JavaMethod
  open func charset() -> Charset!

  /// Java method `replacement`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String java.nio.charset.CharsetDecoder.replacement()
  /// ```
@JavaMethod
  open func replacement() -> String

  /// Java method `implFlush`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected java.nio.charset.CoderResult java.nio.charset.CharsetDecoder.implFlush(java.nio.CharBuffer)
  /// ```
@JavaMethod
  open func implFlush(_ arg0: CharBuffer?) -> CoderResult!

  /// Java method `malformedInputAction`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.nio.charset.CodingErrorAction java.nio.charset.CharsetDecoder.malformedInputAction()
  /// ```
@JavaMethod
  open func malformedInputAction() -> CodingErrorAction!

  /// Java method `unmappableCharacterAction`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.nio.charset.CodingErrorAction java.nio.charset.CharsetDecoder.unmappableCharacterAction()
  /// ```
@JavaMethod
  open func unmappableCharacterAction() -> CodingErrorAction!

  /// Java method `replaceWith`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.charset.CharsetDecoder java.nio.charset.CharsetDecoder.replaceWith(java.lang.String)
  /// ```
@JavaMethod
  open func replaceWith(_ arg0: String) -> CharsetDecoder!

  /// Java method `implReplaceWith`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected void java.nio.charset.CharsetDecoder.implReplaceWith(java.lang.String)
  /// ```
@JavaMethod
  open func implReplaceWith(_ arg0: String)

  /// Java method `implOnMalformedInput`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected void java.nio.charset.CharsetDecoder.implOnMalformedInput(java.nio.charset.CodingErrorAction)
  /// ```
@JavaMethod
  open func implOnMalformedInput(_ arg0: CodingErrorAction?)

  /// Java method `implOnUnmappableCharacter`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected void java.nio.charset.CharsetDecoder.implOnUnmappableCharacter(java.nio.charset.CodingErrorAction)
  /// ```
@JavaMethod
  open func implOnUnmappableCharacter(_ arg0: CodingErrorAction?)

  /// Java method `implReset`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected void java.nio.charset.CharsetDecoder.implReset()
  /// ```
@JavaMethod
  open func implReset()
}
