// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaClass("java.nio.charset.spi.CharsetProvider")
open class CharsetProvider: JavaObject {
  @JavaMethod
  open func charsetForName(_ arg0: String) -> Charset!

  @JavaMethod
  open func charsets() -> JavaIterator<Charset>!
}
