// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.charset.spi.CharsetProvider")
open class CharsetProvider: JavaObject {
  /// Java method `charsetForName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.charset.Charset java.nio.charset.spi.CharsetProvider.charsetForName(java.lang.String)
  /// ```
@JavaMethod
  open func charsetForName(_ arg0: String) -> Charset!

  /// Java method `charsets`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.util.Iterator<java.nio.charset.Charset> java.nio.charset.spi.CharsetProvider.charsets()
  /// ```
@JavaMethod
  open func charsets() -> JavaIterator<Charset>!
}
