// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import SwiftJava

@JavaClass("java.nio.charset.CharacterCodingException")
open class CharacterCodingException: IOException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
