// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import SwiftJava
import CSwiftJavaJNI

@JavaClass("java.nio.file.ClosedDirectoryStreamException")
open class ClosedDirectoryStreamException: IllegalStateException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
