// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import SwiftJava

@JavaClass("java.nio.file.ClosedWatchServiceException")
open class ClosedWatchServiceException: IllegalStateException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
