// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.charset.CoderResult")
open class CoderResult: JavaObject {
  /// Java method `length`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.nio.charset.CoderResult.length()
  /// ```
@JavaMethod
  open func length() -> Int32

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.nio.charset.CoderResult.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `isUnderflow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.nio.charset.CoderResult.isUnderflow()
  /// ```
@JavaMethod
  open func isUnderflow() -> Bool

  /// Java method `throwException`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.nio.charset.CoderResult.throwException() throws java.nio.charset.CharacterCodingException
  /// ```
@JavaMethod
  open func throwException() throws

  /// Java method `isOverflow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.nio.charset.CoderResult.isOverflow()
  /// ```
@JavaMethod
  open func isOverflow() -> Bool

  /// Java method `isError`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.nio.charset.CoderResult.isError()
  /// ```
@JavaMethod
  open func isError() -> Bool

  /// Java method `isMalformed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.nio.charset.CoderResult.isMalformed()
  /// ```
@JavaMethod
  open func isMalformed() -> Bool

  /// Java method `isUnmappable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.nio.charset.CoderResult.isUnmappable()
  /// ```
@JavaMethod
  open func isUnmappable() -> Bool
}
extension JavaClass<CoderResult> {
  @JavaStaticField(isFinal: true)
  public var UNDERFLOW: CoderResult!

  @JavaStaticField(isFinal: true)
  public var OVERFLOW: CoderResult!

    /// Java method `malformedForLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.nio.charset.CoderResult java.nio.charset.CoderResult.malformedForLength(int)
    /// ```
  @JavaStaticMethod
  public func malformedForLength(_ arg0: Int32) -> CoderResult!

    /// Java method `unmappableForLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.nio.charset.CoderResult java.nio.charset.CoderResult.unmappableForLength(int)
    /// ```
  @JavaStaticMethod
  public func unmappableForLength(_ arg0: Int32) -> CoderResult!
}
