// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.channels.DatagramChannel", implements: ByteChannel.self, ScatteringByteChannel.self, GatheringByteChannel.self, MulticastChannel.self)
open class DatagramChannel: AbstractSelectableChannel {
  /// Java method `validOps`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final int java.nio.channels.DatagramChannel.validOps()
  /// ```
@JavaMethod
  open override func validOps() -> Int32

  /// Java method `isConnected`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.nio.channels.DatagramChannel.isConnected()
  /// ```
@JavaMethod
  open func isConnected() -> Bool

  /// Java method `disconnect`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.DatagramChannel java.nio.channels.DatagramChannel.disconnect() throws java.io.IOException
  /// ```
@JavaMethod
  open func disconnect() throws -> DatagramChannel!

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final long java.nio.channels.DatagramChannel.write(java.nio.ByteBuffer[]) throws java.io.IOException
  /// ```
@JavaMethod
  open func write(_ arg0: [ByteBuffer?]) throws -> Int64

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.nio.channels.DatagramChannel.write(java.nio.ByteBuffer) throws java.io.IOException
  /// ```
@JavaMethod
  open func write(_ arg0: ByteBuffer?) throws -> Int32

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.nio.channels.DatagramChannel.write(java.nio.ByteBuffer[],int,int) throws java.io.IOException
  /// ```
@JavaMethod
  open func write(_ arg0: [ByteBuffer?], _ arg1: Int32, _ arg2: Int32) throws -> Int64

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.nio.channels.DatagramChannel.read(java.nio.ByteBuffer[],int,int) throws java.io.IOException
  /// ```
@JavaMethod
  open func read(_ arg0: [ByteBuffer?], _ arg1: Int32, _ arg2: Int32) throws -> Int64

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.nio.channels.DatagramChannel.read(java.nio.ByteBuffer) throws java.io.IOException
  /// ```
@JavaMethod
  open func read(_ arg0: ByteBuffer?) throws -> Int32

  /// Java method `read`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final long java.nio.channels.DatagramChannel.read(java.nio.ByteBuffer[]) throws java.io.IOException
  /// ```
@JavaMethod
  open func read(_ arg0: [ByteBuffer?]) throws -> Int64
}
extension JavaClass<DatagramChannel> {
  /// Java method `open`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.nio.channels.DatagramChannel java.nio.channels.DatagramChannel.open() throws java.io.IOException
  /// ```
@JavaStaticMethod
  public func open() throws -> DatagramChannel!
}
