// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaRuntime

extension DirectoryStream {
  @JavaInterface("java.nio.file.DirectoryStream$Filter")
  public struct Filter<T: AnyJavaObject> {
  @JavaMethod
  public func accept(_ arg0: JavaObject?) throws -> Bool
  }
}
