// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension DirectoryStream {
  @JavaInterface("java.nio.file.DirectoryStream$Filter")
  public struct Filter<T: AnyJavaObject> {
    /// Java method `accept`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract boolean java.nio.file.DirectoryStream$Filter.accept(T) throws java.io.IOException
    /// ```
  @JavaMethod
  public func accept(_ arg0: T?) throws -> Bool
  }
}
