// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.nio.file.FileSystemException")
open class FileSystemException: IOException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: String, environment: JNIEnvironment? = nil)

    /// Java method `getMessage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.file.FileSystemException.getMessage()
    /// ```
  @JavaMethod
  open override func getMessage() -> String

    /// Java method `getFile`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.file.FileSystemException.getFile()
    /// ```
  @JavaMethod
  open func getFile() -> String

    /// Java method `getReason`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.file.FileSystemException.getReason()
    /// ```
  @JavaMethod
  open func getReason() -> String

    /// Java method `getOtherFile`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.file.FileSystemException.getOtherFile()
    /// ```
  @JavaMethod
  open func getOtherFile() -> String
}
