// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

@JavaInterface("java.nio.file.FileVisitor")
public struct FileVisitor<T: AnyJavaObject> {

}
