// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.nio.file.attribute.FileOwnerAttributeView", extends: FileAttributeView.self)
public struct FileOwnerAttributeView {
  /// Java method `name`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.nio.file.attribute.FileOwnerAttributeView.name()
  /// ```
@JavaMethod
  public func name() -> String

  /// Java method `getOwner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.file.attribute.UserPrincipal java.nio.file.attribute.FileOwnerAttributeView.getOwner() throws java.io.IOException
  /// ```
@JavaMethod
  public func getOwner() throws -> UserPrincipal!

  /// Java method `setOwner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.nio.file.attribute.FileOwnerAttributeView.setOwner(java.nio.file.attribute.UserPrincipal) throws java.io.IOException
  /// ```
@JavaMethod
  public func setOwner(_ arg0: UserPrincipal?) throws
}
