// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.nio.file.attribute.FileAttribute")
public struct FileAttribute<T: AnyJavaObject> {
  /// Java method `name`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.nio.file.attribute.FileAttribute.name()
  /// ```
@JavaMethod
  public func name() -> String

  /// Java method `value`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract T java.nio.file.attribute.FileAttribute.value()
  /// ```
@JavaMethod(typeErasedResult: "T!")
  public func value() -> T!
}
