// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import SwiftJava

@JavaClass("java.nio.file.attribute.FileTime", implements: Comparable<FileTime>.self)
open class FileTime: JavaObject {
  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.nio.file.attribute.FileTime.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.nio.file.attribute.FileTime.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.nio.file.attribute.FileTime.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.nio.file.attribute.FileTime.compareTo(java.nio.file.attribute.FileTime)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: FileTime?) -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.nio.file.attribute.FileTime.compareTo(java.lang.Object)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

  /// Java method `toMillis`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.nio.file.attribute.FileTime.toMillis()
  /// ```
@JavaMethod
  open func toMillis() -> Int64
}
extension JavaClass<FileTime> {
  /// Java method `fromMillis`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.nio.file.attribute.FileTime java.nio.file.attribute.FileTime.fromMillis(long)
  /// ```
@JavaStaticMethod
  public func fromMillis(_ arg0: Int64) -> FileTime!
}
