// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaClass("java.nio.file.spi.FileTypeDetector")
open class FileTypeDetector: JavaObject {
  @JavaMethod
  open func probeContentType(_ arg0: Path?) throws -> String
}
