// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaInterface("java.nio.file.attribute.FileAttributeView", extends: AttributeView.self)
public struct FileAttributeView {
  @JavaMethod
  public func name() -> String
}
