// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import SwiftJava
import JavaRuntime

@JavaClass("java.nio.channels.FileLockInterruptionException")
open class FileLockInterruptionException: IOException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
