// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.file.spi.FileTypeDetector")
open class FileTypeDetector: JavaObject {
  /// Java method `probeContentType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.nio.file.spi.FileTypeDetector.probeContentType(java.nio.file.Path) throws java.io.IOException
  /// ```
@JavaMethod
  open func probeContentType(_ arg0: Path?) throws -> String
}
