// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaRuntime

@JavaClass("java.nio.file.FileSystemLoopException")
open class FileSystemLoopException: FileSystemException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)
}
