// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaRuntime

@JavaInterface("java.nio.file.attribute.FileStoreAttributeView", extends: AttributeView.self)
public struct FileStoreAttributeView {
  @JavaMethod
  public func name() -> String
}
