// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension FileChannel {
  @JavaClass("java.nio.channels.FileChannel$MapMode")
  open class MapMode: JavaObject {
    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.channels.FileChannel$MapMode.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String
  }
}
extension JavaClass<FileChannel.MapMode> {
  @JavaStaticField(isFinal: true)
  public var READ_ONLY: FileChannel.MapMode!

  @JavaStaticField(isFinal: true)
  public var READ_WRITE: FileChannel.MapMode!

  @JavaStaticField(isFinal: true)
  public var PRIVATE: FileChannel.MapMode!
}
