// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import SwiftJava

@JavaClass("java.nio.channels.FileLock", implements: AutoCloseable.self)
open class FileLock: JavaObject {
  /// Java method `acquiredBy`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.nio.channels.Channel java.nio.channels.FileLock.acquiredBy()
  /// ```
@JavaMethod
  open func acquiredBy() -> Channel!

  /// Java method `isShared`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean java.nio.channels.FileLock.isShared()
  /// ```
@JavaMethod
  open func isShared() -> Bool

  /// Java method `overlaps`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final boolean java.nio.channels.FileLock.overlaps(long,long)
  /// ```
@JavaMethod
  open func overlaps(_ arg0: Int64, _ arg1: Int64) -> Bool

  /// Java method `size`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final long java.nio.channels.FileLock.size()
  /// ```
@JavaMethod
  open func size() -> Int64

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String java.nio.channels.FileLock.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `position`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final long java.nio.channels.FileLock.position()
  /// ```
@JavaMethod
  open func position() -> Int64

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void java.nio.channels.FileLock.close() throws java.io.IOException
  /// ```
@JavaMethod
  open func close() throws

  /// Java method `release`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.nio.channels.FileLock.release() throws java.io.IOException
  /// ```
@JavaMethod
  open func release() throws

  /// Java method `channel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.channels.FileChannel java.nio.channels.FileLock.channel()
  /// ```
@JavaMethod
  open func channel() -> FileChannel!

  /// Java method `isValid`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.nio.channels.FileLock.isValid()
  /// ```
@JavaMethod
  open func isValid() -> Bool
}
