// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.nio.channels.GatheringByteChannel", extends: WritableByteChannel.self)
public struct GatheringByteChannel {
  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.nio.channels.GatheringByteChannel.write(java.nio.ByteBuffer[],int,int) throws java.io.IOException
  /// ```
@JavaMethod
  public func write(_ arg0: [ByteBuffer?], _ arg1: Int32, _ arg2: Int32) throws -> Int64

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.nio.channels.GatheringByteChannel.write(java.nio.ByteBuffer[]) throws java.io.IOException
  /// ```
@JavaMethod
  public func write(_ arg0: [ByteBuffer?]) throws -> Int64

  /// Java method `write`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.nio.channels.WritableByteChannel.write(java.nio.ByteBuffer) throws java.io.IOException
  /// ```
@JavaMethod
  public func write(_ arg0: ByteBuffer?) throws -> Int32

  /// Java method `isOpen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.nio.channels.Channel.isOpen()
  /// ```
@JavaMethod
  public func isOpen() -> Bool

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.nio.channels.Channel.close() throws java.io.IOException
  /// ```
@JavaMethod
  public func close() throws
}
