// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaRuntime

@JavaInterface("java.nio.channels.GatheringByteChannel", extends: WritableByteChannel.self)
public struct GatheringByteChannel {
  @JavaMethod
  public func write(_ arg0: [ByteBuffer?], _ arg1: Int32, _ arg2: Int32) throws -> Int64

  @JavaMethod
  public func write(_ arg0: [ByteBuffer?]) throws -> Int64

  @JavaMethod
  public func write(_ arg0: ByteBuffer?) throws -> Int32

  @JavaMethod
  public func isOpen() -> Bool

  @JavaMethod
  public func close() throws
}
