// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import SwiftJava

@JavaClass("java.nio.charset.IllegalCharsetNameException")
open class IllegalCharsetNameException: IllegalArgumentException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

    /// Java method `getCharsetName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.charset.IllegalCharsetNameException.getCharsetName()
    /// ```
  @JavaMethod
  open func getCharsetName() -> String
}
