// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

@JavaClass("java.nio.channels.InterruptedByTimeoutException")
open class InterruptedByTimeoutException: IOException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
