// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.nio.channels.InterruptibleChannel", extends: Channel.self)
public struct InterruptibleChannel {
  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.nio.channels.InterruptibleChannel.close() throws java.io.IOException
  /// ```
@JavaMethod
  public func close() throws

  /// Java method `isOpen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.nio.channels.Channel.isOpen()
  /// ```
@JavaMethod
  public func isOpen() -> Bool
}
