// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import SwiftJava

@JavaClass("java.nio.file.InvalidPathException")
open class InvalidPathException: IllegalArgumentException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)

    /// Java method `getMessage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.file.InvalidPathException.getMessage()
    /// ```
  @JavaMethod
  open override func getMessage() -> String

    /// Java method `getIndex`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.nio.file.InvalidPathException.getIndex()
    /// ```
  @JavaMethod
  open func getIndex() -> Int32

    /// Java method `getReason`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.file.InvalidPathException.getReason()
    /// ```
  @JavaMethod
  open func getReason() -> String

    /// Java method `getInput`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.nio.file.InvalidPathException.getInput()
    /// ```
  @JavaMethod
  open func getInput() -> String
}
