// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("java.nio.channels.MembershipKey")
open class MembershipKey: JavaObject {
  @JavaMethod
  open func drop()

  @JavaMethod
  open func channel() -> MulticastChannel!

  @JavaMethod
  open func isValid() -> Bool
}
