// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaCollection
import CSwiftJavaJNI

@JavaInterface("java.nio.channels.MulticastChannel", extends: NetworkChannel.self)
public struct MulticastChannel {
  @JavaMethod
  public func close() throws

  @JavaMethod
  public func isOpen() -> Bool
}
