// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import SwiftJava
import JavaRuntime

@JavaClass("java.nio.channels.NoConnectionPendingException")
open class NoConnectionPendingException: IllegalStateException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
