// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import SwiftJava

@JavaClass("java.nio.channels.NonWritableChannelException")
open class NonWritableChannelException: IllegalStateException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
