// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.nio.file.PathMatcher")
public struct PathMatcher {
  /// Java method `matches`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.nio.file.PathMatcher.matches(java.nio.file.Path)
  /// ```
@JavaMethod
  public func matches(_ arg0: Path?) -> Bool
}
