// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension Pipe {
  @JavaClass("java.nio.channels.Pipe$SourceChannel", implements: ReadableByteChannel.self, ScatteringByteChannel.self)
  open class SourceChannel: AbstractSelectableChannel {
    /// Java method `validOps`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int java.nio.channels.Pipe$SourceChannel.validOps()
    /// ```
  @JavaMethod
  open override func validOps() -> Int32
  }
}
