// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.nio.file.attribute.PosixFileAttributeView", extends: BasicFileAttributeView.self, FileOwnerAttributeView.self)
public struct PosixFileAttributeView {
  /// Java method `setGroup`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.nio.file.attribute.PosixFileAttributeView.setGroup(java.nio.file.attribute.GroupPrincipal) throws java.io.IOException
  /// ```
@JavaMethod
  public func setGroup(_ arg0: GroupPrincipal?) throws

  /// Java method `name`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.nio.file.attribute.PosixFileAttributeView.name()
  /// ```
@JavaMethod
  public func name() -> String

  /// Java method `readAttributes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.nio.file.attribute.BasicFileAttributes java.nio.file.attribute.PosixFileAttributeView.readAttributes() throws java.io.IOException
  /// ```
@JavaMethod
  public func readAttributes() throws -> BasicFileAttributes!

  /// Java method `readAttributes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.file.attribute.PosixFileAttributes java.nio.file.attribute.PosixFileAttributeView.readAttributes() throws java.io.IOException
  /// ```
@JavaMethod
  public func readAttributes() throws -> PosixFileAttributes!

  /// Java method `setTimes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.nio.file.attribute.BasicFileAttributeView.setTimes(java.nio.file.attribute.FileTime,java.nio.file.attribute.FileTime,java.nio.file.attribute.FileTime) throws java.io.IOException
  /// ```
@JavaMethod
  public func setTimes(_ arg0: FileTime?, _ arg1: FileTime?, _ arg2: FileTime?) throws

  /// Java method `getOwner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.file.attribute.UserPrincipal java.nio.file.attribute.FileOwnerAttributeView.getOwner() throws java.io.IOException
  /// ```
@JavaMethod
  public func getOwner() throws -> UserPrincipal!

  /// Java method `setOwner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.nio.file.attribute.FileOwnerAttributeView.setOwner(java.nio.file.attribute.UserPrincipal) throws java.io.IOException
  /// ```
@JavaMethod
  public func setOwner(_ arg0: UserPrincipal?) throws
}
