// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("java.nio.file.attribute.PosixFilePermissions")
open class PosixFilePermissions: JavaObject {

}
extension JavaClass<PosixFilePermissions> {
  @JavaStaticMethod
  public func fromString(_ arg0: String) -> JavaSet<PosixFilePermission>!

  @JavaStaticMethod
  public func asFileAttribute(_ arg0: JavaSet<PosixFilePermission>?) -> FileAttribute<JavaSet<PosixFilePermission>>!

  @JavaStaticMethod
  public func toString(_ arg0: JavaSet<PosixFilePermission>?) -> String
}
