// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import SwiftJava
import CSwiftJavaJNI

@JavaClass("java.nio.ReadOnlyBufferException")
open class ReadOnlyBufferException: UnsupportedOperationException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
