// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import SwiftJava
import CSwiftJavaJNI

@JavaClass("java.nio.file.ReadOnlyFileSystemException")
open class ReadOnlyFileSystemException: UnsupportedOperationException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
