// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.channels.SelectableChannel", implements: Channel.self)
open class SelectableChannel: AbstractInterruptibleChannel {
  /// Java method `validOps`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.nio.channels.SelectableChannel.validOps()
  /// ```
@JavaMethod
  open func validOps() -> Int32

  /// Java method `isBlocking`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.nio.channels.SelectableChannel.isBlocking()
  /// ```
@JavaMethod
  open func isBlocking() -> Bool

  /// Java method `keyFor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.SelectionKey java.nio.channels.SelectableChannel.keyFor(java.nio.channels.Selector)
  /// ```
@JavaMethod
  open func keyFor(_ arg0: Selector?) -> SelectionKey!

  /// Java method `blockingLock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.Object java.nio.channels.SelectableChannel.blockingLock()
  /// ```
@JavaMethod
  open func blockingLock() -> JavaObject!

  /// Java method `configureBlocking`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.SelectableChannel java.nio.channels.SelectableChannel.configureBlocking(boolean) throws java.io.IOException
  /// ```
@JavaMethod
  open func configureBlocking(_ arg0: Bool) throws -> SelectableChannel!

  /// Java method `isRegistered`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.nio.channels.SelectableChannel.isRegistered()
  /// ```
@JavaMethod
  open func isRegistered() -> Bool

  /// Java method `register`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.SelectionKey java.nio.channels.SelectableChannel.register(java.nio.channels.Selector,int,java.lang.Object) throws java.nio.channels.ClosedChannelException
  /// ```
@JavaMethod
  open func register(_ arg0: Selector?, _ arg1: Int32, _ arg2: JavaObject?) throws -> SelectionKey!

  /// Java method `register`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.nio.channels.SelectionKey java.nio.channels.SelectableChannel.register(java.nio.channels.Selector,int) throws java.nio.channels.ClosedChannelException
  /// ```
@JavaMethod
  open func register(_ arg0: Selector?, _ arg1: Int32) throws -> SelectionKey!

  /// Java method `provider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.spi.SelectorProvider java.nio.channels.SelectableChannel.provider()
  /// ```
@JavaMethod
  open func provider() -> SelectorProvider!
}
