// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.channels.spi.SelectorProvider")
open class SelectorProvider: JavaObject {
  /// Java method `openDatagramChannel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.DatagramChannel java.nio.channels.spi.SelectorProvider.openDatagramChannel() throws java.io.IOException
  /// ```
@JavaMethod
  open func openDatagramChannel() throws -> DatagramChannel!

  /// Java method `openPipe`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.Pipe java.nio.channels.spi.SelectorProvider.openPipe() throws java.io.IOException
  /// ```
@JavaMethod
  open func openPipe() throws -> Pipe!

  /// Java method `openSelector`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.spi.AbstractSelector java.nio.channels.spi.SelectorProvider.openSelector() throws java.io.IOException
  /// ```
@JavaMethod
  open func openSelector() throws -> AbstractSelector!

  /// Java method `openServerSocketChannel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.ServerSocketChannel java.nio.channels.spi.SelectorProvider.openServerSocketChannel() throws java.io.IOException
  /// ```
@JavaMethod
  open func openServerSocketChannel() throws -> ServerSocketChannel!

  /// Java method `openSocketChannel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.channels.SocketChannel java.nio.channels.spi.SelectorProvider.openSocketChannel() throws java.io.IOException
  /// ```
@JavaMethod
  open func openSocketChannel() throws -> SocketChannel!

  /// Java method `inheritedChannel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.nio.channels.Channel java.nio.channels.spi.SelectorProvider.inheritedChannel() throws java.io.IOException
  /// ```
@JavaMethod
  open func inheritedChannel() throws -> Channel!
}
extension JavaClass<SelectorProvider> {
  /// Java method `provider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.nio.channels.spi.SelectorProvider java.nio.channels.spi.SelectorProvider.provider()
  /// ```
@JavaStaticMethod
  public func provider() -> SelectorProvider!
}
