// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaClass("java.nio.channels.ServerSocketChannel", implements: NetworkChannel.self)
open class ServerSocketChannel: AbstractSelectableChannel {
  @JavaMethod
  open override func validOps() -> Int32

  @JavaMethod
  open func accept() throws -> SocketChannel!
}
extension JavaClass<ServerSocketChannel> {
  @JavaStaticMethod
  public func open() throws -> ServerSocketChannel!
}
