// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import SwiftJava
import JavaRuntime

@JavaClass("java.nio.channels.ShutdownChannelGroupException")
open class ShutdownChannelGroupException: IllegalStateException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
