// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

@JavaClass("java.nio.file.SimpleFileVisitor", implements: FileVisitor<T>.self)
open class SimpleFileVisitor<T: AnyJavaObject>: JavaObject {

}
