// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import JavaKit
import JavaRuntime

@JavaClass("java.nio.channels.UnsupportedAddressTypeException")
open class UnsupportedAddressTypeException: IllegalArgumentException {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
