// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.nio.file.attribute.UserPrincipalLookupService")
open class UserPrincipalLookupService: JavaObject {
  /// Java method `lookupPrincipalByName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.file.attribute.UserPrincipal java.nio.file.attribute.UserPrincipalLookupService.lookupPrincipalByName(java.lang.String) throws java.io.IOException
  /// ```
@JavaMethod
  open func lookupPrincipalByName(_ arg0: String) throws -> UserPrincipal!

  /// Java method `lookupPrincipalByGroupName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.file.attribute.GroupPrincipal java.nio.file.attribute.UserPrincipalLookupService.lookupPrincipalByGroupName(java.lang.String) throws java.io.IOException
  /// ```
@JavaMethod
  open func lookupPrincipalByGroupName(_ arg0: String) throws -> GroupPrincipal!
}
