// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.nio.file.WatchEvent")
public struct WatchEvent<T: AnyJavaObject> {
  /// Java method `count`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.nio.file.WatchEvent.count()
  /// ```
@JavaMethod
  public func count() -> Int32

  /// Java method `kind`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.nio.file.WatchEvent$Kind<T> java.nio.file.WatchEvent.kind()
  /// ```
@JavaMethod
  public func kind() -> WatchEvent.Kind<T>!

  /// Java method `context`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract T java.nio.file.WatchEvent.context()
  /// ```
@JavaMethod(typeErasedResult: "T!")
  public func context() -> T!
}
