// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

extension WatchEvent {
  @JavaInterface("java.nio.file.WatchEvent$Kind")
  public struct Kind<T: AnyJavaObject> {
  @JavaMethod
  public func name() -> String

  @JavaMethod
  public func type() -> JavaClass<JavaObject>!
  }
}
