// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.AccessController")
open class AccessController: JavaObject {

}
extension JavaClass<AccessController> {
  /// Java method `checkPermission`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void java.security.AccessController.checkPermission(java.security.Permission) throws java.security.AccessControlException
  /// ```
@JavaStaticMethod
  public func checkPermission(_ arg0: Permission?) throws

  /// Java method `doPrivileged`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivileged(java.security.PrivilegedExceptionAction<T>,java.security.AccessControlContext,java.security.Permission...) throws java.security.PrivilegedActionException
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivileged<T: AnyJavaObject>(_ arg0: PrivilegedExceptionAction<T>?, _ arg1: AccessControlContext?, _ arg2: [Permission?]) throws -> T!

  /// Java method `doPrivileged`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivileged(java.security.PrivilegedAction<T>)
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivileged<T: AnyJavaObject>(_ arg0: PrivilegedAction<T>?) -> T!

  /// Java method `doPrivileged`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivileged(java.security.PrivilegedExceptionAction<T>) throws java.security.PrivilegedActionException
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivileged<T: AnyJavaObject>(_ arg0: PrivilegedExceptionAction<T>?) throws -> T!

  /// Java method `doPrivileged`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivileged(java.security.PrivilegedExceptionAction<T>,java.security.AccessControlContext) throws java.security.PrivilegedActionException
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivileged<T: AnyJavaObject>(_ arg0: PrivilegedExceptionAction<T>?, _ arg1: AccessControlContext?) throws -> T!

  /// Java method `doPrivileged`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivileged(java.security.PrivilegedAction<T>,java.security.AccessControlContext,java.security.Permission...)
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivileged<T: AnyJavaObject>(_ arg0: PrivilegedAction<T>?, _ arg1: AccessControlContext?, _ arg2: [Permission?]) -> T!

  /// Java method `doPrivileged`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivileged(java.security.PrivilegedAction<T>,java.security.AccessControlContext)
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivileged<T: AnyJavaObject>(_ arg0: PrivilegedAction<T>?, _ arg1: AccessControlContext?) -> T!

  /// Java method `doPrivilegedWithCombiner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivilegedWithCombiner(java.security.PrivilegedExceptionAction<T>,java.security.AccessControlContext,java.security.Permission...) throws java.security.PrivilegedActionException
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivilegedWithCombiner<T: AnyJavaObject>(_ arg0: PrivilegedExceptionAction<T>?, _ arg1: AccessControlContext?, _ arg2: [Permission?]) throws -> T!

  /// Java method `doPrivilegedWithCombiner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivilegedWithCombiner(java.security.PrivilegedExceptionAction<T>) throws java.security.PrivilegedActionException
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivilegedWithCombiner<T: AnyJavaObject>(_ arg0: PrivilegedExceptionAction<T>?) throws -> T!

  /// Java method `doPrivilegedWithCombiner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivilegedWithCombiner(java.security.PrivilegedAction<T>)
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivilegedWithCombiner<T: AnyJavaObject>(_ arg0: PrivilegedAction<T>?) -> T!

  /// Java method `doPrivilegedWithCombiner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static <T> T java.security.AccessController.doPrivilegedWithCombiner(java.security.PrivilegedAction<T>,java.security.AccessControlContext,java.security.Permission...)
  /// ```
@JavaStaticMethod(typeErasedResult: "T!")
  public func doPrivilegedWithCombiner<T: AnyJavaObject>(_ arg0: PrivilegedAction<T>?, _ arg1: AccessControlContext?, _ arg2: [Permission?]) -> T!

  /// Java method `getContext`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.AccessControlContext java.security.AccessController.getContext()
  /// ```
@JavaStaticMethod
  public func getContext() -> AccessControlContext!
}
