// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.AlgorithmParametersSpi")
open class AlgorithmParametersSpi: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `engineInit`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.security.AlgorithmParametersSpi.engineInit(byte[]) throws java.io.IOException
    /// ```
  @JavaMethod
  open func engineInit(_ arg0: [Int8]) throws

    /// Java method `engineInit`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.security.AlgorithmParametersSpi.engineInit(java.security.spec.AlgorithmParameterSpec) throws java.security.spec.InvalidParameterSpecException
    /// ```
  @JavaMethod
  open func engineInit(_ arg0: AlgorithmParameterSpec?) throws

    /// Java method `engineInit`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.security.AlgorithmParametersSpi.engineInit(byte[],java.lang.String) throws java.io.IOException
    /// ```
  @JavaMethod
  open func engineInit(_ arg0: [Int8], _ arg1: String) throws

    /// Java method `engineGetParameterSpec`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract <T extends java.security.spec.AlgorithmParameterSpec> T java.security.AlgorithmParametersSpi.engineGetParameterSpec(java.lang.Class<T>) throws java.security.spec.InvalidParameterSpecException
    /// ```
  @JavaMethod(typeErasedResult: "T!")
  open func engineGetParameterSpec<T: AnyJavaObject>(_ arg0: JavaClass<T>?) throws -> T!

    /// Java method `engineGetEncoded`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract byte[] java.security.AlgorithmParametersSpi.engineGetEncoded(java.lang.String) throws java.io.IOException
    /// ```
  @JavaMethod
  open func engineGetEncoded(_ arg0: String) throws -> [Int8]

    /// Java method `engineGetEncoded`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract byte[] java.security.AlgorithmParametersSpi.engineGetEncoded() throws java.io.IOException
    /// ```
  @JavaMethod
  open func engineGetEncoded() throws -> [Int8]

    /// Java method `engineToString`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract java.lang.String java.security.AlgorithmParametersSpi.engineToString()
    /// ```
  @JavaMethod
  open func engineToString() -> String
}
