// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.AlgorithmParameterGenerator")
open class AlgorithmParameterGenerator: JavaObject {
  /// Java method `generateParameters`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.AlgorithmParameters java.security.AlgorithmParameterGenerator.generateParameters()
  /// ```
@JavaMethod
  open func generateParameters() -> AlgorithmParameters!

  /// Java method `init`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void java.security.AlgorithmParameterGenerator.init(int,java.security.SecureRandom)
  /// ```
@JavaMethod("init")
  open func `init`(_ arg0: Int32, _ arg1: SecureRandom?)

  /// Java method `init`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void java.security.AlgorithmParameterGenerator.init(java.security.spec.AlgorithmParameterSpec) throws java.security.InvalidAlgorithmParameterException
  /// ```
@JavaMethod("init")
  open func `init`(_ arg0: AlgorithmParameterSpec?) throws

  /// Java method `init`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void java.security.AlgorithmParameterGenerator.init(java.security.spec.AlgorithmParameterSpec,java.security.SecureRandom) throws java.security.InvalidAlgorithmParameterException
  /// ```
@JavaMethod("init")
  open func `init`(_ arg0: AlgorithmParameterSpec?, _ arg1: SecureRandom?) throws

  /// Java method `init`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void java.security.AlgorithmParameterGenerator.init(int)
  /// ```
@JavaMethod("init")
  open func `init`(_ arg0: Int32)

  /// Java method `getProvider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.Provider java.security.AlgorithmParameterGenerator.getProvider()
  /// ```
@JavaMethod
  open func getProvider() -> Provider!

  /// Java method `getAlgorithm`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String java.security.AlgorithmParameterGenerator.getAlgorithm()
  /// ```
@JavaMethod
  open func getAlgorithm() -> String
}
extension JavaClass<AlgorithmParameterGenerator> {
  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.AlgorithmParameterGenerator java.security.AlgorithmParameterGenerator.getInstance(java.lang.String,java.security.Provider) throws java.security.NoSuchAlgorithmException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: Provider?) throws -> AlgorithmParameterGenerator!

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.AlgorithmParameterGenerator java.security.AlgorithmParameterGenerator.getInstance(java.lang.String,java.lang.String) throws java.security.NoSuchAlgorithmException,java.security.NoSuchProviderException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: String) throws -> AlgorithmParameterGenerator!

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.AlgorithmParameterGenerator java.security.AlgorithmParameterGenerator.getInstance(java.lang.String) throws java.security.NoSuchAlgorithmException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String) throws -> AlgorithmParameterGenerator!
}
