// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.AuthProvider")
open class AuthProvider: Provider {
  /// Java method `logout`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.security.AuthProvider.logout() throws javax.security.auth.login.LoginException
  /// ```
@JavaMethod
  open func logout() throws
}
