// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.cert.CertStore")
open class CertStore: JavaObject {
  /// Java method `getCRLs`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.Collection<? extends java.security.cert.CRL> java.security.cert.CertStore.getCRLs(java.security.cert.CRLSelector) throws java.security.cert.CertStoreException
  /// ```
@JavaMethod
  open func getCRLs(_ arg0: CRLSelector?) throws -> JavaCollection<CRL>!

  /// Java method `getCertStoreParameters`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.cert.CertStoreParameters java.security.cert.CertStore.getCertStoreParameters()
  /// ```
@JavaMethod
  open func getCertStoreParameters() -> CertStoreParameters!

  /// Java method `getCertificates`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.util.Collection<? extends java.security.cert.Certificate> java.security.cert.CertStore.getCertificates(java.security.cert.CertSelector) throws java.security.cert.CertStoreException
  /// ```
@JavaMethod
  open func getCertificates(_ arg0: CertSelector?) throws -> JavaCollection<CertCertificate>!

  /// Java method `getType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String java.security.cert.CertStore.getType()
  /// ```
@JavaMethod
  open func getType() -> String

  /// Java method `getProvider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.Provider java.security.cert.CertStore.getProvider()
  /// ```
@JavaMethod
  open func getProvider() -> Provider!
}
extension JavaClass<CertStore> {
  /// Java method `getDefaultType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static final java.lang.String java.security.cert.CertStore.getDefaultType()
  /// ```
@JavaStaticMethod
  public func getDefaultType() -> String

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.cert.CertStore java.security.cert.CertStore.getInstance(java.lang.String,java.security.cert.CertStoreParameters,java.lang.String) throws java.security.InvalidAlgorithmParameterException,java.security.NoSuchAlgorithmException,java.security.NoSuchProviderException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: CertStoreParameters?, _ arg2: String) throws -> CertStore!

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.cert.CertStore java.security.cert.CertStore.getInstance(java.lang.String,java.security.cert.CertStoreParameters,java.security.Provider) throws java.security.NoSuchAlgorithmException,java.security.InvalidAlgorithmParameterException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: CertStoreParameters?, _ arg2: Provider?) throws -> CertStore!

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.cert.CertStore java.security.cert.CertStore.getInstance(java.lang.String,java.security.cert.CertStoreParameters) throws java.security.InvalidAlgorithmParameterException,java.security.NoSuchAlgorithmException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: CertStoreParameters?) throws -> CertStore!
}
