// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import SwiftJava

@JavaInterface("java.security.cert.CertPathParameters", extends: Cloneable.self)
public struct CertPathParameters {
  /// Java method `clone`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.Object java.security.cert.CertPathParameters.clone()
  /// ```
@JavaMethod
  public func clone() -> JavaObject!
}
