// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

@JavaClass("java.security.cert.CertPath", implements: Serializable.self)
open class CertPath: JavaObject {
  /// Java method `getEncodings`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.util.Iterator<java.lang.String> java.security.cert.CertPath.getEncodings()
  /// ```
@JavaMethod
  open func getEncodings() -> JavaIterator<JavaString>!

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.security.cert.CertPath.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.security.cert.CertPath.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.security.cert.CertPath.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `getCertificates`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.util.List<? extends java.security.cert.Certificate> java.security.cert.CertPath.getCertificates()
  /// ```
@JavaMethod
  open func getCertificates() -> List<CertCertificate>!

  /// Java method `getType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.security.cert.CertPath.getType()
  /// ```
@JavaMethod
  open func getType() -> String

  /// Java method `getEncoded`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract byte[] java.security.cert.CertPath.getEncoded(java.lang.String) throws java.security.cert.CertificateEncodingException
  /// ```
@JavaMethod
  open func getEncoded(_ arg0: String) throws -> [Int8]

  /// Java method `getEncoded`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract byte[] java.security.cert.CertPath.getEncoded() throws java.security.cert.CertificateEncodingException
  /// ```
@JavaMethod
  open func getEncoded() throws -> [Int8]

  /// Java method `writeReplace`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected java.lang.Object java.security.cert.CertPath.writeReplace() throws java.io.ObjectStreamException
  /// ```
@JavaMethod
  open func writeReplace() throws -> JavaObject!
}
