// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.cert.CertPathValidator")
open class CertPathValidator: JavaObject {
  /// Java method `getRevocationChecker`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.cert.CertPathChecker java.security.cert.CertPathValidator.getRevocationChecker()
  /// ```
@JavaMethod
  open func getRevocationChecker() -> CertPathChecker!

  /// Java method `validate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.cert.CertPathValidatorResult java.security.cert.CertPathValidator.validate(java.security.cert.CertPath,java.security.cert.CertPathParameters) throws java.security.cert.CertPathValidatorException,java.security.InvalidAlgorithmParameterException
  /// ```
@JavaMethod
  open func validate(_ arg0: CertPath?, _ arg1: CertPathParameters?) throws -> CertPathValidatorResult!

  /// Java method `getProvider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.Provider java.security.cert.CertPathValidator.getProvider()
  /// ```
@JavaMethod
  open func getProvider() -> Provider!

  /// Java method `getAlgorithm`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String java.security.cert.CertPathValidator.getAlgorithm()
  /// ```
@JavaMethod
  open func getAlgorithm() -> String
}
extension JavaClass<CertPathValidator> {
  /// Java method `getDefaultType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static final java.lang.String java.security.cert.CertPathValidator.getDefaultType()
  /// ```
@JavaStaticMethod
  public func getDefaultType() -> String

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.cert.CertPathValidator java.security.cert.CertPathValidator.getInstance(java.lang.String) throws java.security.NoSuchAlgorithmException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String) throws -> CertPathValidator!

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.cert.CertPathValidator java.security.cert.CertPathValidator.getInstance(java.lang.String,java.security.Provider) throws java.security.NoSuchAlgorithmException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: Provider?) throws -> CertPathValidator!

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.cert.CertPathValidator java.security.cert.CertPathValidator.getInstance(java.lang.String,java.lang.String) throws java.security.NoSuchAlgorithmException,java.security.NoSuchProviderException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: String) throws -> CertPathValidator!
}
