// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.cert.CertificateRevokedException")
open class CertificateRevokedException: CertificateException {
  /// Java method `getMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.security.cert.CertificateRevokedException.getMessage()
  /// ```
@JavaMethod
  open override func getMessage() -> String
}
