// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.cert.CertPathValidatorSpi")
open class CertPathValidatorSpi: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `engineValidate`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.security.cert.CertPathValidatorResult java.security.cert.CertPathValidatorSpi.engineValidate(java.security.cert.CertPath,java.security.cert.CertPathParameters) throws java.security.cert.CertPathValidatorException,java.security.InvalidAlgorithmParameterException
    /// ```
  @JavaMethod
  open func engineValidate(_ arg0: CertPath?, _ arg1: CertPathParameters?) throws -> CertPathValidatorResult!

    /// Java method `engineGetRevocationChecker`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.cert.CertPathChecker java.security.cert.CertPathValidatorSpi.engineGetRevocationChecker()
    /// ```
  @JavaMethod
  open func engineGetRevocationChecker() -> CertPathChecker!
}
