// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

extension CertCertificate {
  @JavaClass("java.security.cert.Certificate$CertificateRep", implements: Serializable.self)
  open class CertificateRep: JavaObject {
    /// Java method `readResolve`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.lang.Object java.security.cert.Certificate$CertificateRep.readResolve() throws java.io.ObjectStreamException
    /// ```
  @JavaMethod
  open func readResolve() throws -> JavaObject!
  }
}
