// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.security.interfaces.DSAParams", extends: AlgorithmParameterSpec.self)
public struct DSAParams {

}
