// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.spec.DSAPublicKeySpec", implements: KeySpec.self)
open class DSAPublicKeySpec: JavaObject {

}
