// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.spec.DSAPrivateKeySpec", implements: KeySpec.self)
open class DSAPrivateKeySpec: JavaObject {

}
