// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.spec.ECPublicKeySpec", implements: KeySpec.self)
open class ECPublicKeySpec: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ECPoint?, _ arg1: ECParameterSpec?, environment: JNIEnvironment? = nil)

    /// Java method `getParams`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.spec.ECParameterSpec java.security.spec.ECPublicKeySpec.getParams()
    /// ```
  @JavaMethod
  open func getParams() -> ECParameterSpec!

    /// Java method `getW`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.spec.ECPoint java.security.spec.ECPublicKeySpec.getW()
    /// ```
  @JavaMethod
  open func getW() -> ECPoint!
}
