// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.security.Guard")
public struct Guard {
  /// Java method `checkGuard`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void java.security.Guard.checkGuard(java.lang.Object) throws java.lang.SecurityException
  /// ```
@JavaMethod
  public func checkGuard(_ arg0: JavaObject?) throws
}
