// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.IdentityScope")
open class IdentityScope: Identity {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: IdentityScope?, environment: JNIEnvironment? = nil) throws

    /// Java method `addIdentity`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void java.security.IdentityScope.addIdentity(java.security.Identity) throws java.security.KeyManagementException
    /// ```
  @JavaMethod
  open func addIdentity(_ arg0: Identity?) throws

    /// Java method `getIdentity`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.Identity java.security.IdentityScope.getIdentity(java.security.Principal)
    /// ```
  @JavaMethod
  open func getIdentity(_ arg0: Principal?) -> Identity!

    /// Java method `getIdentity`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.security.Identity java.security.IdentityScope.getIdentity(java.lang.String)
    /// ```
  @JavaMethod
  open func getIdentity(_ arg0: String) -> Identity!

    /// Java method `getIdentity`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.security.Identity java.security.IdentityScope.getIdentity(java.security.PublicKey)
    /// ```
  @JavaMethod
  open func getIdentity(_ arg0: PublicKey?) -> Identity!

    /// Java method `removeIdentity`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void java.security.IdentityScope.removeIdentity(java.security.Identity) throws java.security.KeyManagementException
    /// ```
  @JavaMethod
  open func removeIdentity(_ arg0: Identity?) throws

    /// Java method `size`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract int java.security.IdentityScope.size()
    /// ```
  @JavaMethod
  open func size() -> Int32

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.IdentityScope.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String
}
extension JavaClass<IdentityScope> {
  /// Java method `getSystemScope`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.IdentityScope java.security.IdentityScope.getSystemScope()
  /// ```
@JavaStaticMethod
  public func getSystemScope() -> IdentityScope!

  /// Java method `setSystemScope`.
  ///
  /// ### Java method signature
  /// ```java
  /// protected static void java.security.IdentityScope.setSystemScope(java.security.IdentityScope)
  /// ```
@JavaStaticMethod
  public func setSystemScope(_ arg0: IdentityScope?)
}
