// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaInterface("java.security.Key", extends: Serializable.self)
public struct Key {
  /// Java method `getEncoded`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract byte[] java.security.Key.getEncoded()
  /// ```
@JavaMethod
  public func getEncoded() -> [Int8]

  /// Java method `getFormat`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.security.Key.getFormat()
  /// ```
@JavaMethod
  public func getFormat() -> String

  /// Java method `getAlgorithm`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.security.Key.getAlgorithm()
  /// ```
@JavaMethod
  public func getAlgorithm() -> String
}
extension JavaClass<Key> {
  @JavaStaticField(isFinal: true)
  public var serialVersionUID: Int64
}
