// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.KeyFactory")
open class KeyFactory: JavaObject {
  /// Java method `generatePublic`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.PublicKey java.security.KeyFactory.generatePublic(java.security.spec.KeySpec) throws java.security.spec.InvalidKeySpecException
  /// ```
@JavaMethod
  open func generatePublic(_ arg0: KeySpec?) throws -> PublicKey!

  /// Java method `generatePrivate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.PrivateKey java.security.KeyFactory.generatePrivate(java.security.spec.KeySpec) throws java.security.spec.InvalidKeySpecException
  /// ```
@JavaMethod
  open func generatePrivate(_ arg0: KeySpec?) throws -> PrivateKey!

  /// Java method `getKeySpec`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final <T extends java.security.spec.KeySpec> T java.security.KeyFactory.getKeySpec(java.security.Key,java.lang.Class<T>) throws java.security.spec.InvalidKeySpecException
  /// ```
@JavaMethod(typeErasedResult: "T!")
  open func getKeySpec<T: AnyJavaObject>(_ arg0: Key?, _ arg1: JavaClass<T>?) throws -> T!

  /// Java method `translateKey`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.Key java.security.KeyFactory.translateKey(java.security.Key) throws java.security.InvalidKeyException
  /// ```
@JavaMethod
  open func translateKey(_ arg0: Key?) throws -> Key!

  /// Java method `getProvider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.security.Provider java.security.KeyFactory.getProvider()
  /// ```
@JavaMethod
  open func getProvider() -> Provider!

  /// Java method `getAlgorithm`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final java.lang.String java.security.KeyFactory.getAlgorithm()
  /// ```
@JavaMethod
  open func getAlgorithm() -> String
}
extension JavaClass<KeyFactory> {
  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.KeyFactory java.security.KeyFactory.getInstance(java.lang.String) throws java.security.NoSuchAlgorithmException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String) throws -> KeyFactory!

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.KeyFactory java.security.KeyFactory.getInstance(java.lang.String,java.lang.String) throws java.security.NoSuchAlgorithmException,java.security.NoSuchProviderException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: String) throws -> KeyFactory!

  /// Java method `getInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.security.KeyFactory java.security.KeyFactory.getInstance(java.lang.String,java.security.Provider) throws java.security.NoSuchAlgorithmException
  /// ```
@JavaStaticMethod
  public func getInstance(_ arg0: String, _ arg1: Provider?) throws -> KeyFactory!
}
