// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension KeyStore {
  @JavaClass("java.security.KeyStore$CallbackHandlerProtection", implements: KeyStore.ProtectionParameter.self)
  open class CallbackHandlerProtection: JavaObject {

  }
}
