// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension KeyStore {
  @JavaClass("java.security.KeyStore$SecretKeyEntry", implements: KeyStore.Entry.self)
  open class SecretKeyEntry: JavaObject {
    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.KeyStore$SecretKeyEntry.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `getAttributes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Set<java.security.KeyStore$Entry$Attribute> java.security.KeyStore$SecretKeyEntry.getAttributes()
    /// ```
  @JavaMethod
  open func getAttributes() -> JavaSet<KeyStore.Entry.Attribute>!
  }
}
