// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension KeyStore {
  @JavaClass("java.security.KeyStore$PrivateKeyEntry", implements: KeyStore.Entry.self)
  open class PrivateKeyEntry: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: PrivateKey?, _ arg1: [CertCertificate?], _ arg2: JavaSet<KeyStore.Entry.Attribute>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: PrivateKey?, _ arg1: [CertCertificate?], environment: JNIEnvironment? = nil)

    /// Java method `getPrivateKey`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.PrivateKey java.security.KeyStore$PrivateKeyEntry.getPrivateKey()
    /// ```
  @JavaMethod
  open func getPrivateKey() -> PrivateKey!

    /// Java method `getCertificate`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.cert.Certificate java.security.KeyStore$PrivateKeyEntry.getCertificate()
    /// ```
  @JavaMethod
  open func getCertificate() -> CertCertificate!

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.KeyStore$PrivateKeyEntry.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `getAttributes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Set<java.security.KeyStore$Entry$Attribute> java.security.KeyStore$PrivateKeyEntry.getAttributes()
    /// ```
  @JavaMethod
  open func getAttributes() -> JavaSet<KeyStore.Entry.Attribute>!

    /// Java method `getCertificateChain`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.cert.Certificate[] java.security.KeyStore$PrivateKeyEntry.getCertificateChain()
    /// ```
  @JavaMethod
  open func getCertificateChain() -> [CertCertificate?]
  }
}
