// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension KeyStore {
  @JavaClass("java.security.KeyStore$PasswordProtection", implements: KeyStore.ProtectionParameter.self)
  open class PasswordProtection: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [UInt16], environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [UInt16], _ arg1: String, _ arg2: AlgorithmParameterSpec?, environment: JNIEnvironment? = nil)

    /// Java method `getPassword`.
    ///
    /// ### Java method signature
    /// ```java
    /// public synchronized char[] java.security.KeyStore$PasswordProtection.getPassword()
    /// ```
  @JavaMethod
  open func getPassword() -> [UInt16]

    /// Java method `getProtectionAlgorithm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.KeyStore$PasswordProtection.getProtectionAlgorithm()
    /// ```
  @JavaMethod
  open func getProtectionAlgorithm() -> String

    /// Java method `getProtectionParameters`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.spec.AlgorithmParameterSpec java.security.KeyStore$PasswordProtection.getProtectionParameters()
    /// ```
  @JavaMethod
  open func getProtectionParameters() -> AlgorithmParameterSpec!

    /// Java method `isDestroyed`.
    ///
    /// ### Java method signature
    /// ```java
    /// public synchronized boolean java.security.KeyStore$PasswordProtection.isDestroyed()
    /// ```
  @JavaMethod
  open func isDestroyed() -> Bool

    /// Java method `destroy`.
    ///
    /// ### Java method signature
    /// ```java
    /// public synchronized void java.security.KeyStore$PasswordProtection.destroy() throws javax.security.auth.DestroyFailedException
    /// ```
  @JavaMethod
  open func destroy() throws
  }
}
