// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension KeyStore {
  @JavaClass("java.security.KeyStore$TrustedCertificateEntry", implements: KeyStore.Entry.self)
  open class TrustedCertificateEntry: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CertCertificate?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CertCertificate?, _ arg1: JavaSet<KeyStore.Entry.Attribute>?, environment: JNIEnvironment? = nil)

    /// Java method `getTrustedCertificate`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.cert.Certificate java.security.KeyStore$TrustedCertificateEntry.getTrustedCertificate()
    /// ```
  @JavaMethod
  open func getTrustedCertificate() -> CertCertificate!

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.KeyStore$TrustedCertificateEntry.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `getAttributes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.util.Set<java.security.KeyStore$Entry$Attribute> java.security.KeyStore$TrustedCertificateEntry.getAttributes()
    /// ```
  @JavaMethod
  open func getAttributes() -> JavaSet<KeyStore.Entry.Attribute>!
  }
}
