// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.MessageDigestSpi")
open class MessageDigestSpi: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `engineUpdate`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.security.MessageDigestSpi.engineUpdate(byte[],int,int)
    /// ```
  @JavaMethod
  open func engineUpdate(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32)

    /// Java method `engineUpdate`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.security.MessageDigestSpi.engineUpdate(byte)
    /// ```
  @JavaMethod
  open func engineUpdate(_ arg0: Int8)

    /// Java method `engineUpdate`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void java.security.MessageDigestSpi.engineUpdate(java.nio.ByteBuffer)
    /// ```
  @JavaMethod
  open func engineUpdate(_ arg0: ByteBuffer?)

    /// Java method `engineDigest`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected int java.security.MessageDigestSpi.engineDigest(byte[],int,int) throws java.security.DigestException
    /// ```
  @JavaMethod
  open func engineDigest(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws -> Int32

    /// Java method `engineDigest`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract byte[] java.security.MessageDigestSpi.engineDigest()
    /// ```
  @JavaMethod
  open func engineDigest() -> [Int8]

    /// Java method `engineReset`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.security.MessageDigestSpi.engineReset()
    /// ```
  @JavaMethod
  open func engineReset()

    /// Java method `engineGetDigestLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected int java.security.MessageDigestSpi.engineGetDigestLength()
    /// ```
  @JavaMethod
  open func engineGetDigestLength() -> Int32

    /// Java method `clone`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.Object java.security.MessageDigestSpi.clone() throws java.lang.CloneNotSupportedException
    /// ```
  @JavaMethod
  open override func clone() throws -> JavaObject!
}
