// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.spec.MGF1ParameterSpec", implements: AlgorithmParameterSpec.self)
open class MGF1ParameterSpec: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

    /// Java method `getDigestAlgorithm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.spec.MGF1ParameterSpec.getDigestAlgorithm()
    /// ```
  @JavaMethod
  open func getDigestAlgorithm() -> String

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.spec.MGF1ParameterSpec.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String
}
extension JavaClass<MGF1ParameterSpec> {
  @JavaStaticField(isFinal: true)
  public var SHA1: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA224: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA256: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA384: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA512: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA512_224: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA512_256: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA3_224: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA3_256: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA3_384: MGF1ParameterSpec!

  @JavaStaticField(isFinal: true)
  public var SHA3_512: MGF1ParameterSpec!
}
