// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.security.Permission", implements: Guard.self, Serializable.self)
open class Permission: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

    /// Java method `getName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.security.Permission.getName()
    /// ```
  @JavaMethod
  open func getName() -> String

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract boolean java.security.Permission.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.Permission.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract int java.security.Permission.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `implies`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract boolean java.security.Permission.implies(java.security.Permission)
    /// ```
  @JavaMethod
  open func implies(_ arg0: Permission?) -> Bool

    /// Java method `getActions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.lang.String java.security.Permission.getActions()
    /// ```
  @JavaMethod
  open func getActions() -> String

    /// Java method `newPermissionCollection`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.PermissionCollection java.security.Permission.newPermissionCollection()
    /// ```
  @JavaMethod
  open func newPermissionCollection() -> PermissionCollection!

    /// Java method `checkGuard`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.security.Permission.checkGuard(java.lang.Object) throws java.lang.SecurityException
    /// ```
  @JavaMethod
  open func checkGuard(_ arg0: JavaObject?) throws
}
