// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.security.Permissions", implements: Serializable.self)
open class Permissions: PermissionCollection {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `add`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.security.Permissions.add(java.security.Permission)
    /// ```
  @JavaMethod
  open override func add(_ arg0: Permission?)

    /// Java method `implies`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.security.Permissions.implies(java.security.Permission)
    /// ```
  @JavaMethod
  open override func implies(_ arg0: Permission?) -> Bool
}
