// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.cert.PKIXCertPathBuilderResult", implements: CertPathBuilderResult.self)
open class PKIXCertPathBuilderResult: PKIXCertPathValidatorResult {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CertPath?, _ arg1: TrustAnchor?, _ arg2: PolicyNode?, _ arg3: PublicKey?, environment: JNIEnvironment? = nil)

    /// Java method `getCertPath`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.cert.CertPath java.security.cert.PKIXCertPathBuilderResult.getCertPath()
    /// ```
  @JavaMethod
  open func getCertPath() -> CertPath!

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.cert.PKIXCertPathBuilderResult.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String
}
