// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.cert.PKIXBuilderParameters")
open class PKIXBuilderParameters: PKIXParameters {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaSet<TrustAnchor>?, _ arg1: CertSelector?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: KeyStore?, _ arg1: CertSelector?, environment: JNIEnvironment? = nil) throws

    /// Java method `setMaxPathLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.security.cert.PKIXBuilderParameters.setMaxPathLength(int)
    /// ```
  @JavaMethod
  open func setMaxPathLength(_ arg0: Int32)

    /// Java method `getMaxPathLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.security.cert.PKIXBuilderParameters.getMaxPathLength()
    /// ```
  @JavaMethod
  open func getMaxPathLength() -> Int32

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.cert.PKIXBuilderParameters.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String
}
