// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.cert.PKIXCertPathValidatorResult", implements: CertPathValidatorResult.self)
open class PKIXCertPathValidatorResult: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: TrustAnchor?, _ arg1: PolicyNode?, _ arg2: PublicKey?, environment: JNIEnvironment? = nil)

    /// Java method `getTrustAnchor`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.cert.TrustAnchor java.security.cert.PKIXCertPathValidatorResult.getTrustAnchor()
    /// ```
  @JavaMethod
  open func getTrustAnchor() -> TrustAnchor!

    /// Java method `getPolicyTree`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.cert.PolicyNode java.security.cert.PKIXCertPathValidatorResult.getPolicyTree()
    /// ```
  @JavaMethod
  open func getPolicyTree() -> PolicyNode!

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.cert.PKIXCertPathValidatorResult.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `clone`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.Object java.security.cert.PKIXCertPathValidatorResult.clone()
    /// ```
  @JavaMethod
  open override func clone() -> JavaObject!

    /// Java method `getPublicKey`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.PublicKey java.security.cert.PKIXCertPathValidatorResult.getPublicKey()
    /// ```
  @JavaMethod
  open func getPublicKey() -> PublicKey!
}
