// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.security.PrivilegedExceptionAction")
public struct PrivilegedExceptionAction<T: AnyJavaObject> {
  /// Java method `run`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract T java.security.PrivilegedExceptionAction.run() throws java.lang.Exception
  /// ```
@JavaMethod(typeErasedResult: "T!")
  public func run() throws -> T!
}
