// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.ProtectionDomain")
open class ProtectionDomain: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CodeSource?, _ arg1: PermissionCollection?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CodeSource?, _ arg1: PermissionCollection?, _ arg2: JavaClassLoader?, _ arg3: [Principal?], environment: JNIEnvironment? = nil)

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.ProtectionDomain.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `getClassLoader`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.ClassLoader java.security.ProtectionDomain.getClassLoader()
    /// ```
  @JavaMethod
  open func getClassLoader() -> JavaClassLoader!

    /// Java method `getCodeSource`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.security.CodeSource java.security.ProtectionDomain.getCodeSource()
    /// ```
  @JavaMethod
  open func getCodeSource() -> CodeSource!

    /// Java method `implies`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.security.ProtectionDomain.implies(java.security.Permission)
    /// ```
  @JavaMethod
  open func implies(_ arg0: Permission?) -> Bool

    /// Java method `getPrincipals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.security.Principal[] java.security.ProtectionDomain.getPrincipals()
    /// ```
  @JavaMethod
  open func getPrincipals() -> [Principal?]

    /// Java method `getPermissions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.security.PermissionCollection java.security.ProtectionDomain.getPermissions()
    /// ```
  @JavaMethod
  open func getPermissions() -> PermissionCollection!

    /// Java method `staticPermissionsOnly`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean java.security.ProtectionDomain.staticPermissionsOnly()
    /// ```
  @JavaMethod
  open func staticPermissionsOnly() -> Bool
}
