// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

extension Provider {
  @JavaClass("java.security.Provider$Service")
  open class Service: JavaObject {
    /// Java method `supportsParameter`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.security.Provider$Service.supportsParameter(java.lang.Object)
    /// ```
  @JavaMethod
  open func supportsParameter(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.Provider$Service.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `newInstance`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.Object java.security.Provider$Service.newInstance(java.lang.Object) throws java.security.NoSuchAlgorithmException
    /// ```
  @JavaMethod
  open func newInstance(_ arg0: JavaObject?) throws -> JavaObject!

    /// Java method `getType`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.security.Provider$Service.getType()
    /// ```
  @JavaMethod
  open func getType() -> String

    /// Java method `getClassName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.security.Provider$Service.getClassName()
    /// ```
  @JavaMethod
  open func getClassName() -> String

    /// Java method `getAttribute`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.security.Provider$Service.getAttribute(java.lang.String)
    /// ```
  @JavaMethod
  open func getAttribute(_ arg0: String) -> String

    /// Java method `getProvider`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.security.Provider java.security.Provider$Service.getProvider()
    /// ```
  @JavaMethod
  open func getProvider() -> Provider!

    /// Java method `getAlgorithm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.security.Provider$Service.getAlgorithm()
    /// ```
  @JavaMethod
  open func getAlgorithm() -> String
  }
}
