// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.spec.PSSParameterSpec", implements: AlgorithmParameterSpec.self)
open class PSSParameterSpec: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: AlgorithmParameterSpec?, _ arg3: Int32, _ arg4: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

    /// Java method `getDigestAlgorithm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.spec.PSSParameterSpec.getDigestAlgorithm()
    /// ```
  @JavaMethod
  open func getDigestAlgorithm() -> String

    /// Java method `getMGFAlgorithm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.spec.PSSParameterSpec.getMGFAlgorithm()
    /// ```
  @JavaMethod
  open func getMGFAlgorithm() -> String

    /// Java method `getMGFParameters`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.spec.AlgorithmParameterSpec java.security.spec.PSSParameterSpec.getMGFParameters()
    /// ```
  @JavaMethod
  open func getMGFParameters() -> AlgorithmParameterSpec!

    /// Java method `getSaltLength`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.security.spec.PSSParameterSpec.getSaltLength()
    /// ```
  @JavaMethod
  open func getSaltLength() -> Int32

    /// Java method `getTrailerField`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.security.spec.PSSParameterSpec.getTrailerField()
    /// ```
  @JavaMethod
  open func getTrailerField() -> Int32

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.spec.PSSParameterSpec.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String
}
extension JavaClass<PSSParameterSpec> {
  @JavaStaticField(isFinal: true)
  public var TRAILER_FIELD_BC: Int32

  @JavaStaticField(isFinal: true)
  public var DEFAULT: PSSParameterSpec!
}
