// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.spec.RSAPublicKeySpec", implements: KeySpec.self)
open class RSAPublicKeySpec: JavaObject {
  /// Java method `getParams`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.security.spec.AlgorithmParameterSpec java.security.spec.RSAPublicKeySpec.getParams()
  /// ```
@JavaMethod
  open func getParams() -> AlgorithmParameterSpec!
}
