// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.security.SecureRandomSpi", implements: Serializable.self)
open class SecureRandomSpi: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `engineSetSeed`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.security.SecureRandomSpi.engineSetSeed(byte[])
    /// ```
  @JavaMethod
  open func engineSetSeed(_ arg0: [Int8])

    /// Java method `engineNextBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.security.SecureRandomSpi.engineNextBytes(byte[])
    /// ```
  @JavaMethod
  open func engineNextBytes(_ arg0: [Int8])

    /// Java method `engineGenerateSeed`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract byte[] java.security.SecureRandomSpi.engineGenerateSeed(int)
    /// ```
  @JavaMethod
  open func engineGenerateSeed(_ arg0: Int32) -> [Int8]

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.SecureRandomSpi.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String
}
