// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.Signer")
open class Signer: Identity {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: IdentityScope?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

    /// Java method `getPrivateKey`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.PrivateKey java.security.Signer.getPrivateKey()
    /// ```
  @JavaMethod
  open func getPrivateKey() -> PrivateKey!

    /// Java method `setKeyPair`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final void java.security.Signer.setKeyPair(java.security.KeyPair) throws java.security.InvalidParameterException,java.security.KeyException
    /// ```
  @JavaMethod
  open func setKeyPair(_ arg0: KeyPair?) throws

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.Signer.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String
}
