// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.security.UnresolvedPermission", implements: Serializable.self)
open class UnresolvedPermission: Permission {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: String, _ arg3: [CertCertificate?], environment: JNIEnvironment? = nil)

    /// Java method `getUnresolvedType`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.UnresolvedPermission.getUnresolvedType()
    /// ```
  @JavaMethod
  open func getUnresolvedType() -> String

    /// Java method `getUnresolvedName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.UnresolvedPermission.getUnresolvedName()
    /// ```
  @JavaMethod
  open func getUnresolvedName() -> String

    /// Java method `getUnresolvedActions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.UnresolvedPermission.getUnresolvedActions()
    /// ```
  @JavaMethod
  open func getUnresolvedActions() -> String

    /// Java method `getUnresolvedCerts`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.cert.Certificate[] java.security.UnresolvedPermission.getUnresolvedCerts()
    /// ```
  @JavaMethod
  open func getUnresolvedCerts() -> [CertCertificate?]

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.security.UnresolvedPermission.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.UnresolvedPermission.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.security.UnresolvedPermission.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `implies`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.security.UnresolvedPermission.implies(java.security.Permission)
    /// ```
  @JavaMethod
  open override func implies(_ arg0: Permission?) -> Bool

    /// Java method `getActions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.security.UnresolvedPermission.getActions()
    /// ```
  @JavaMethod
  open override func getActions() -> String

    /// Java method `newPermissionCollection`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.security.PermissionCollection java.security.UnresolvedPermission.newPermissionCollection()
    /// ```
  @JavaMethod
  open override func newPermissionCollection() -> PermissionCollection!
}
