// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.security.cert.URICertStoreParameters", implements: CertStoreParameters.self)
open class URICertStoreParameters: JavaObject {
  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.security.cert.URICertStoreParameters.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.security.cert.URICertStoreParameters.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.security.cert.URICertStoreParameters.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `clone`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.security.cert.URICertStoreParameters java.security.cert.URICertStoreParameters.clone()
  /// ```
@JavaMethod
  open override func clone() -> URICertStoreParameters!
}
