// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.security.cert.X509Extension")
public struct X509Extension {
  /// Java method `getCriticalExtensionOIDs`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.util.Set<java.lang.String> java.security.cert.X509Extension.getCriticalExtensionOIDs()
  /// ```
@JavaMethod
  public func getCriticalExtensionOIDs() -> JavaSet<JavaString>!

  /// Java method `hasUnsupportedCriticalExtension`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.security.cert.X509Extension.hasUnsupportedCriticalExtension()
  /// ```
@JavaMethod
  public func hasUnsupportedCriticalExtension() -> Bool

  /// Java method `getNonCriticalExtensionOIDs`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.util.Set<java.lang.String> java.security.cert.X509Extension.getNonCriticalExtensionOIDs()
  /// ```
@JavaMethod
  public func getNonCriticalExtensionOIDs() -> JavaSet<JavaString>!

  /// Java method `getExtensionValue`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract byte[] java.security.cert.X509Extension.getExtensionValue(java.lang.String)
  /// ```
@JavaMethod
  public func getExtensionValue(_ arg0: String) -> [Int8]
}
