// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.time.chrono.AbstractChronology", implements: Chronology.self)
open class AbstractChronology: JavaObject {
  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.chrono.AbstractChronology.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.AbstractChronology.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.chrono.AbstractChronology.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.chrono.AbstractChronology.compareTo(java.lang.Object)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.chrono.AbstractChronology.compareTo(java.time.chrono.Chronology)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: Chronology?) -> Int32
}
