// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import SwiftJava

@JavaInterface("java.time.chrono.ChronoLocalDate", extends: Temporal.self, TemporalAdjuster.self)
public struct ChronoLocalDate {
  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.time.chrono.ChronoLocalDate.equals(java.lang.Object)
  /// ```
@JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.time.chrono.ChronoLocalDate.toString()
  /// ```
@JavaMethod
  public func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.time.chrono.ChronoLocalDate.hashCode()
  /// ```
@JavaMethod
  public func hashCode() -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.time.chrono.ChronoLocalDate.compareTo(java.time.chrono.ChronoLocalDate)
  /// ```
@JavaMethod
  public func compareTo(_ arg0: ChronoLocalDate?) -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.time.chrono.ChronoLocalDate.compareTo(java.lang.Object)
  /// ```
@JavaMethod
  public func compareTo(_ arg0: JavaObject?) -> Int32

  /// Java method `format`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.lang.String java.time.chrono.ChronoLocalDate.format(java.time.format.DateTimeFormatter)
  /// ```
@JavaMethod
  public func format(_ arg0: DateTimeFormatter?) -> String

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoLocalDate.isSupported(java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func isSupported(_ arg0: TemporalUnit?) -> Bool

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoLocalDate.isSupported(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func isSupported(_ arg0: TemporalField?) -> Bool

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoLocalDate java.time.chrono.ChronoLocalDate.with(java.time.temporal.TemporalField,long)
  /// ```
@JavaMethod
  public func with(_ arg0: TemporalField?, _ arg1: Int64) -> ChronoLocalDate!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoLocalDate.with(java.time.temporal.TemporalField,long)
  /// ```
@JavaMethod
  public func with(_ arg0: TemporalField?, _ arg1: Int64) -> Temporal!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoLocalDate.with(java.time.temporal.TemporalAdjuster)
  /// ```
@JavaMethod
  public func with(_ arg0: TemporalAdjuster?) -> Temporal!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoLocalDate java.time.chrono.ChronoLocalDate.with(java.time.temporal.TemporalAdjuster)
  /// ```
@JavaMethod
  public func with(_ arg0: TemporalAdjuster?) -> ChronoLocalDate!

  /// Java method `query`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default <R> R java.time.chrono.ChronoLocalDate.query(java.time.temporal.TemporalQuery<R>)
  /// ```
@JavaMethod(typeErasedResult: "R!")
  public func query<R: AnyJavaObject>(_ arg0: TemporalQuery<R>?) -> R!

  /// Java method `isEqual`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoLocalDate.isEqual(java.time.chrono.ChronoLocalDate)
  /// ```
@JavaMethod
  public func isEqual(_ arg0: ChronoLocalDate?) -> Bool

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoLocalDate.minus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  public func minus(_ arg0: TemporalAmount?) -> Temporal!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoLocalDate java.time.chrono.ChronoLocalDate.minus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  public func minus(_ arg0: TemporalAmount?) -> ChronoLocalDate!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoLocalDate.minus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func minus(_ arg0: Int64, _ arg1: TemporalUnit?) -> Temporal!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoLocalDate java.time.chrono.ChronoLocalDate.minus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func minus(_ arg0: Int64, _ arg1: TemporalUnit?) -> ChronoLocalDate!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoLocalDate.plus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  public func plus(_ arg0: TemporalAmount?) -> Temporal!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoLocalDate java.time.chrono.ChronoLocalDate.plus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  public func plus(_ arg0: TemporalAmount?) -> ChronoLocalDate!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoLocalDate java.time.chrono.ChronoLocalDate.plus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func plus(_ arg0: Int64, _ arg1: TemporalUnit?) -> ChronoLocalDate!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoLocalDate.plus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func plus(_ arg0: Int64, _ arg1: TemporalUnit?) -> Temporal!

  /// Java method `until`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.time.chrono.ChronoLocalDate.until(java.time.temporal.Temporal,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func until(_ arg0: Temporal?, _ arg1: TemporalUnit?) -> Int64

  /// Java method `until`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.ChronoPeriod java.time.chrono.ChronoLocalDate.until(java.time.chrono.ChronoLocalDate)
  /// ```
@JavaMethod
  public func until(_ arg0: ChronoLocalDate?) -> ChronoPeriod!

  /// Java method `adjustInto`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoLocalDate.adjustInto(java.time.temporal.Temporal)
  /// ```
@JavaMethod
  public func adjustInto(_ arg0: Temporal?) -> Temporal!

  /// Java method `isAfter`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoLocalDate.isAfter(java.time.chrono.ChronoLocalDate)
  /// ```
@JavaMethod
  public func isAfter(_ arg0: ChronoLocalDate?) -> Bool

  /// Java method `isBefore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoLocalDate.isBefore(java.time.chrono.ChronoLocalDate)
  /// ```
@JavaMethod
  public func isBefore(_ arg0: ChronoLocalDate?) -> Bool

  /// Java method `isLeapYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoLocalDate.isLeapYear()
  /// ```
@JavaMethod
  public func isLeapYear() -> Bool

  /// Java method `lengthOfMonth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.time.chrono.ChronoLocalDate.lengthOfMonth()
  /// ```
@JavaMethod
  public func lengthOfMonth() -> Int32

  /// Java method `lengthOfYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.time.chrono.ChronoLocalDate.lengthOfYear()
  /// ```
@JavaMethod
  public func lengthOfYear() -> Int32

  /// Java method `toEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default long java.time.chrono.ChronoLocalDate.toEpochDay()
  /// ```
@JavaMethod
  public func toEpochDay() -> Int64

  /// Java method `atTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoLocalDateTime<?> java.time.chrono.ChronoLocalDate.atTime(java.time.LocalTime)
  /// ```
@JavaMethod
  public func atTime(_ arg0: LocalTime?) -> ChronoLocalDateTime<JavaObject>!

  /// Java method `getEra`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.Era java.time.chrono.ChronoLocalDate.getEra()
  /// ```
@JavaMethod
  public func getEra() -> Era!

  /// Java method `getChronology`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.Chronology java.time.chrono.ChronoLocalDate.getChronology()
  /// ```
@JavaMethod
  public func getChronology() -> Chronology!

  /// Java method `get`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.time.temporal.TemporalAccessor.get(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func get(_ arg0: TemporalField?) -> Int32

  /// Java method `getLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.time.temporal.TemporalAccessor.getLong(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func getLong(_ arg0: TemporalField?) -> Int64

  /// Java method `range`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.ValueRange java.time.temporal.TemporalAccessor.range(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func range(_ arg0: TemporalField?) -> ValueRange!
}
