// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import SwiftJava

@JavaInterface("java.time.chrono.ChronoZonedDateTime", extends: Temporal.self)
public struct ChronoZonedDateTime<D> {
  /// Java method `withEarlierOffsetAtOverlap`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.withEarlierOffsetAtOverlap()
  /// ```
@JavaMethod
  public func withEarlierOffsetAtOverlap() -> ChronoZonedDateTime<D>!

  /// Java method `withLaterOffsetAtOverlap`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.withLaterOffsetAtOverlap()
  /// ```
@JavaMethod
  public func withLaterOffsetAtOverlap() -> ChronoZonedDateTime<D>!

  /// Java method `withZoneSameLocal`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.withZoneSameLocal(java.time.ZoneId)
  /// ```
@JavaMethod
  public func withZoneSameLocal(_ arg0: ZoneId?) -> ChronoZonedDateTime<D>!

  /// Java method `withZoneSameInstant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.withZoneSameInstant(java.time.ZoneId)
  /// ```
@JavaMethod
  public func withZoneSameInstant(_ arg0: ZoneId?) -> ChronoZonedDateTime<D>!

  /// Java method `get`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.time.chrono.ChronoZonedDateTime.get(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func get(_ arg0: TemporalField?) -> Int32

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.time.chrono.ChronoZonedDateTime.equals(java.lang.Object)
  /// ```
@JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.time.chrono.ChronoZonedDateTime.toString()
  /// ```
@JavaMethod
  public func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int java.time.chrono.ChronoZonedDateTime.hashCode()
  /// ```
@JavaMethod
  public func hashCode() -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.time.chrono.ChronoZonedDateTime.compareTo(java.time.chrono.ChronoZonedDateTime<?>)
  /// ```
@JavaMethod
  public func compareTo(_ arg0: ChronoZonedDateTime<JavaObject>?) -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.time.chrono.ChronoZonedDateTime.compareTo(java.lang.Object)
  /// ```
@JavaMethod
  public func compareTo(_ arg0: JavaObject?) -> Int32

  /// Java method `getLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default long java.time.chrono.ChronoZonedDateTime.getLong(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func getLong(_ arg0: TemporalField?) -> Int64

  /// Java method `format`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.lang.String java.time.chrono.ChronoZonedDateTime.format(java.time.format.DateTimeFormatter)
  /// ```
@JavaMethod
  public func format(_ arg0: DateTimeFormatter?) -> String

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.time.chrono.ChronoZonedDateTime.isSupported(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func isSupported(_ arg0: TemporalField?) -> Bool

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoZonedDateTime.isSupported(java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func isSupported(_ arg0: TemporalUnit?) -> Bool

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoZonedDateTime.with(java.time.temporal.TemporalAdjuster)
  /// ```
@JavaMethod
  public func with(_ arg0: TemporalAdjuster?) -> Temporal!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.with(java.time.temporal.TemporalAdjuster)
  /// ```
@JavaMethod
  public func with(_ arg0: TemporalAdjuster?) -> ChronoZonedDateTime<D>!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.with(java.time.temporal.TemporalField,long)
  /// ```
@JavaMethod
  public func with(_ arg0: TemporalField?, _ arg1: Int64) -> ChronoZonedDateTime<D>!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoZonedDateTime.with(java.time.temporal.TemporalField,long)
  /// ```
@JavaMethod
  public func with(_ arg0: TemporalField?, _ arg1: Int64) -> Temporal!

  /// Java method `query`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default <R> R java.time.chrono.ChronoZonedDateTime.query(java.time.temporal.TemporalQuery<R>)
  /// ```
@JavaMethod(typeErasedResult: "R!")
  public func query<R: AnyJavaObject>(_ arg0: TemporalQuery<R>?) -> R!

  /// Java method `getOffset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.ZoneOffset java.time.chrono.ChronoZonedDateTime.getOffset()
  /// ```
@JavaMethod
  public func getOffset() -> ZoneOffset!

  /// Java method `range`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.ValueRange java.time.chrono.ChronoZonedDateTime.range(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func range(_ arg0: TemporalField?) -> ValueRange!

  /// Java method `isEqual`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoZonedDateTime.isEqual(java.time.chrono.ChronoZonedDateTime<?>)
  /// ```
@JavaMethod
  public func isEqual(_ arg0: ChronoZonedDateTime<JavaObject>?) -> Bool

  /// Java method `toInstant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.Instant java.time.chrono.ChronoZonedDateTime.toInstant()
  /// ```
@JavaMethod
  public func toInstant() -> Instant!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoZonedDateTime.minus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func minus(_ arg0: Int64, _ arg1: TemporalUnit?) -> Temporal!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.minus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func minus(_ arg0: Int64, _ arg1: TemporalUnit?) -> ChronoZonedDateTime<D>!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoZonedDateTime.minus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  public func minus(_ arg0: TemporalAmount?) -> Temporal!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.minus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  public func minus(_ arg0: TemporalAmount?) -> ChronoZonedDateTime<D>!

  /// Java method `getZone`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.ZoneId java.time.chrono.ChronoZonedDateTime.getZone()
  /// ```
@JavaMethod
  public func getZone() -> ZoneId!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoZonedDateTime.plus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func plus(_ arg0: Int64, _ arg1: TemporalUnit?) -> Temporal!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.plus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func plus(_ arg0: Int64, _ arg1: TemporalUnit?) -> ChronoZonedDateTime<D>!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.ChronoZonedDateTime<D> java.time.chrono.ChronoZonedDateTime.plus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  public func plus(_ arg0: TemporalAmount?) -> ChronoZonedDateTime<D>!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.Temporal java.time.chrono.ChronoZonedDateTime.plus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  public func plus(_ arg0: TemporalAmount?) -> Temporal!

  /// Java method `isAfter`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoZonedDateTime.isAfter(java.time.chrono.ChronoZonedDateTime<?>)
  /// ```
@JavaMethod
  public func isAfter(_ arg0: ChronoZonedDateTime<JavaObject>?) -> Bool

  /// Java method `isBefore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean java.time.chrono.ChronoZonedDateTime.isBefore(java.time.chrono.ChronoZonedDateTime<?>)
  /// ```
@JavaMethod
  public func isBefore(_ arg0: ChronoZonedDateTime<JavaObject>?) -> Bool

  /// Java method `toLocalTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.LocalTime java.time.chrono.ChronoZonedDateTime.toLocalTime()
  /// ```
@JavaMethod
  public func toLocalTime() -> LocalTime!

  /// Java method `getChronology`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.chrono.Chronology java.time.chrono.ChronoZonedDateTime.getChronology()
  /// ```
@JavaMethod
  public func getChronology() -> Chronology!

  /// Java method `toEpochSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default long java.time.chrono.ChronoZonedDateTime.toEpochSecond()
  /// ```
@JavaMethod
  public func toEpochSecond() -> Int64

  /// Java method `toLocalDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.chrono.ChronoLocalDateTime<D> java.time.chrono.ChronoZonedDateTime.toLocalDateTime()
  /// ```
@JavaMethod
  public func toLocalDateTime() -> ChronoLocalDateTime<D>!

  /// Java method `toLocalDate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default D java.time.chrono.ChronoZonedDateTime.toLocalDate()
  /// ```
@JavaMethod(typeErasedResult: "D!")
  public func toLocalDate() -> D!

  /// Java method `until`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.time.temporal.Temporal.until(java.time.temporal.Temporal,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  public func until(_ arg0: Temporal?, _ arg1: TemporalUnit?) -> Int64
}
