// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.time.chrono.HijrahChronology", implements: Serializable.self)
open class HijrahChronology: AbstractChronology {
  /// Java method `getId`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.HijrahChronology.getId()
  /// ```
@JavaMethod
  open func getId() -> String

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.date(int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.date(int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> HijrahDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.date(java.time.chrono.Era,int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> HijrahDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.date(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func date(_ arg0: TemporalAccessor?) -> HijrahDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.date(java.time.chrono.Era,int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.date(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func date(_ arg0: TemporalAccessor?) -> ChronoLocalDate!

  /// Java method `eras`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.util.List<java.time.chrono.Era> java.time.chrono.HijrahChronology.eras()
  /// ```
@JavaMethod
  open func eras() -> List<Era>!

  /// Java method `isLeapYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.chrono.HijrahChronology.isLeapYear(long)
  /// ```
@JavaMethod
  open func isLeapYear(_ arg0: Int64) -> Bool

  /// Java method `eraOf`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.Era java.time.chrono.HijrahChronology.eraOf(int)
  /// ```
@JavaMethod
  open func eraOf(_ arg0: Int32) -> Era!

  /// Java method `localDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDateTime<java.time.chrono.HijrahDate> java.time.chrono.HijrahChronology.localDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func localDateTime(_ arg0: TemporalAccessor?) -> ChronoLocalDateTime<HijrahDate>!

  /// Java method `getCalendarType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.HijrahChronology.getCalendarType()
  /// ```
@JavaMethod
  open func getCalendarType() -> String

  /// Java method `dateEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.dateEpochDay(long)
  /// ```
@JavaMethod
  open func dateEpochDay(_ arg0: Int64) -> ChronoLocalDate!

  /// Java method `dateEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.dateEpochDay(long)
  /// ```
@JavaMethod
  open func dateEpochDay(_ arg0: Int64) -> HijrahDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.dateNow(java.time.ZoneId)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: ZoneId?) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.dateNow(java.time.Clock)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: Clock?) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.dateNow()
  /// ```
@JavaMethod
  open func dateNow() -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.dateNow(java.time.ZoneId)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: ZoneId?) -> HijrahDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.dateNow()
  /// ```
@JavaMethod
  open func dateNow() -> HijrahDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.dateNow(java.time.Clock)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: Clock?) -> HijrahDate!

  /// Java method `prolepticYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.chrono.HijrahChronology.prolepticYear(java.time.chrono.Era,int)
  /// ```
@JavaMethod
  open func prolepticYear(_ arg0: Era?, _ arg1: Int32) -> Int32

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.dateYearDay(int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Int32, _ arg1: Int32) -> ChronoLocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.HijrahChronology.dateYearDay(java.time.chrono.Era,int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32) -> ChronoLocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.dateYearDay(int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Int32, _ arg1: Int32) -> HijrahDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.HijrahDate java.time.chrono.HijrahChronology.dateYearDay(java.time.chrono.Era,int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32) -> HijrahDate!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoZonedDateTime<java.time.chrono.HijrahDate> java.time.chrono.HijrahChronology.zonedDateTime(java.time.Instant,java.time.ZoneId)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: Instant?, _ arg1: ZoneId?) -> ChronoZonedDateTime<HijrahDate>!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoZonedDateTime<java.time.chrono.HijrahDate> java.time.chrono.HijrahChronology.zonedDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: TemporalAccessor?) -> ChronoZonedDateTime<HijrahDate>!
}
extension JavaClass<HijrahChronology> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: HijrahChronology!
}
