// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.time.chrono.IsoChronology", implements: Serializable.self)
open class IsoChronology: AbstractChronology {
  /// Java method `getId`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.IsoChronology.getId()
  /// ```
@JavaMethod
  open func getId() -> String

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.date(java.time.chrono.Era,int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> LocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.date(int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> LocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.date(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func date(_ arg0: TemporalAccessor?) -> LocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.date(int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.date(java.time.chrono.Era,int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.date(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func date(_ arg0: TemporalAccessor?) -> ChronoLocalDate!

  /// Java method `eras`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.util.List<java.time.chrono.Era> java.time.chrono.IsoChronology.eras()
  /// ```
@JavaMethod
  open func eras() -> List<Era>!

  /// Java method `epochSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.chrono.IsoChronology.epochSecond(int,int,int,int,int,int,java.time.ZoneOffset)
  /// ```
@JavaMethod
  open func epochSecond(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, _ arg6: ZoneOffset?) -> Int64

  /// Java method `isLeapYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.chrono.IsoChronology.isLeapYear(long)
  /// ```
@JavaMethod
  open func isLeapYear(_ arg0: Int64) -> Bool

  /// Java method `eraOf`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.Era java.time.chrono.IsoChronology.eraOf(int)
  /// ```
@JavaMethod
  open func eraOf(_ arg0: Int32) -> Era!

  /// Java method `localDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDateTime java.time.chrono.IsoChronology.localDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func localDateTime(_ arg0: TemporalAccessor?) -> ChronoLocalDateTime!

  /// Java method `localDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDateTime java.time.chrono.IsoChronology.localDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func localDateTime(_ arg0: TemporalAccessor?) -> LocalDateTime!

  /// Java method `getCalendarType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.IsoChronology.getCalendarType()
  /// ```
@JavaMethod
  open func getCalendarType() -> String

  /// Java method `dateEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.dateEpochDay(long)
  /// ```
@JavaMethod
  open func dateEpochDay(_ arg0: Int64) -> LocalDate!

  /// Java method `dateEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.dateEpochDay(long)
  /// ```
@JavaMethod
  open func dateEpochDay(_ arg0: Int64) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.dateNow(java.time.Clock)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: Clock?) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.dateNow()
  /// ```
@JavaMethod
  open func dateNow() -> LocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.dateNow(java.time.Clock)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: Clock?) -> LocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.dateNow(java.time.ZoneId)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: ZoneId?) -> LocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.dateNow()
  /// ```
@JavaMethod
  open func dateNow() -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.dateNow(java.time.ZoneId)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: ZoneId?) -> ChronoLocalDate!

  /// Java method `prolepticYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.chrono.IsoChronology.prolepticYear(java.time.chrono.Era,int)
  /// ```
@JavaMethod
  open func prolepticYear(_ arg0: Era?, _ arg1: Int32) -> Int32

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.dateYearDay(int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Int32, _ arg1: Int32) -> LocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.chrono.IsoChronology.dateYearDay(java.time.chrono.Era,int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32) -> LocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.dateYearDay(int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Int32, _ arg1: Int32) -> ChronoLocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.IsoChronology.dateYearDay(java.time.chrono.Era,int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32) -> ChronoLocalDate!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.ZonedDateTime java.time.chrono.IsoChronology.zonedDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: TemporalAccessor?) -> ZonedDateTime!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoZonedDateTime java.time.chrono.IsoChronology.zonedDateTime(java.time.Instant,java.time.ZoneId)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: Instant?, _ arg1: ZoneId?) -> ChronoZonedDateTime!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoZonedDateTime java.time.chrono.IsoChronology.zonedDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: TemporalAccessor?) -> ChronoZonedDateTime!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.ZonedDateTime java.time.chrono.IsoChronology.zonedDateTime(java.time.Instant,java.time.ZoneId)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: Instant?, _ arg1: ZoneId?) -> ZonedDateTime!

  /// Java method `period`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoPeriod java.time.chrono.IsoChronology.period(int,int,int)
  /// ```
@JavaMethod
  open func period(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> ChronoPeriod!

  /// Java method `period`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.Period java.time.chrono.IsoChronology.period(int,int,int)
  /// ```
@JavaMethod
  open func period(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> Period!

  /// Java method `isIsoBased`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.chrono.IsoChronology.isIsoBased()
  /// ```
@JavaMethod
  open func isIsoBased() -> Bool
}
extension JavaClass<IsoChronology> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: IsoChronology!
}
