// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

@JavaClass("java.time.chrono.JapaneseChronology", implements: Serializable.self)
open class JapaneseChronology: AbstractChronology {
  /// Java method `getId`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.JapaneseChronology.getId()
  /// ```
@JavaMethod
  open func getId() -> String

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.date(java.time.chrono.Era,int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> JapaneseDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.date(int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> JapaneseDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.date(java.time.chrono.Era,int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.date(int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.date(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func date(_ arg0: TemporalAccessor?) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.date(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func date(_ arg0: TemporalAccessor?) -> JapaneseDate!

  /// Java method `eras`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.util.List<java.time.chrono.Era> java.time.chrono.JapaneseChronology.eras()
  /// ```
@JavaMethod
  open func eras() -> List<Era>!

  /// Java method `isLeapYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.chrono.JapaneseChronology.isLeapYear(long)
  /// ```
@JavaMethod
  open func isLeapYear(_ arg0: Int64) -> Bool

  /// Java method `eraOf`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.Era java.time.chrono.JapaneseChronology.eraOf(int)
  /// ```
@JavaMethod
  open func eraOf(_ arg0: Int32) -> Era!

  /// Java method `eraOf`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseEra java.time.chrono.JapaneseChronology.eraOf(int)
  /// ```
@JavaMethod
  open func eraOf(_ arg0: Int32) -> JapaneseEra!

  /// Java method `localDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDateTime<java.time.chrono.JapaneseDate> java.time.chrono.JapaneseChronology.localDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func localDateTime(_ arg0: TemporalAccessor?) -> ChronoLocalDateTime<JapaneseDate>!

  /// Java method `getCalendarType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.JapaneseChronology.getCalendarType()
  /// ```
@JavaMethod
  open func getCalendarType() -> String

  /// Java method `dateEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.dateEpochDay(long)
  /// ```
@JavaMethod
  open func dateEpochDay(_ arg0: Int64) -> ChronoLocalDate!

  /// Java method `dateEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.dateEpochDay(long)
  /// ```
@JavaMethod
  open func dateEpochDay(_ arg0: Int64) -> JapaneseDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.dateNow()
  /// ```
@JavaMethod
  open func dateNow() -> JapaneseDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.dateNow(java.time.Clock)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: Clock?) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.dateNow(java.time.ZoneId)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: ZoneId?) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.dateNow()
  /// ```
@JavaMethod
  open func dateNow() -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.dateNow(java.time.Clock)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: Clock?) -> JapaneseDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.dateNow(java.time.ZoneId)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: ZoneId?) -> JapaneseDate!

  /// Java method `prolepticYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.chrono.JapaneseChronology.prolepticYear(java.time.chrono.Era,int)
  /// ```
@JavaMethod
  open func prolepticYear(_ arg0: Era?, _ arg1: Int32) -> Int32

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.dateYearDay(java.time.chrono.Era,int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32) -> ChronoLocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.JapaneseChronology.dateYearDay(int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Int32, _ arg1: Int32) -> ChronoLocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.dateYearDay(java.time.chrono.Era,int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32) -> JapaneseDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.JapaneseDate java.time.chrono.JapaneseChronology.dateYearDay(int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Int32, _ arg1: Int32) -> JapaneseDate!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoZonedDateTime<java.time.chrono.JapaneseDate> java.time.chrono.JapaneseChronology.zonedDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: TemporalAccessor?) -> ChronoZonedDateTime<JapaneseDate>!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoZonedDateTime<java.time.chrono.JapaneseDate> java.time.chrono.JapaneseChronology.zonedDateTime(java.time.Instant,java.time.ZoneId)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: Instant?, _ arg1: ZoneId?) -> ChronoZonedDateTime<JapaneseDate>!

  /// Java method `isIsoBased`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.chrono.JapaneseChronology.isIsoBased()
  /// ```
@JavaMethod
  open func isIsoBased() -> Bool
}
extension JavaClass<JapaneseChronology> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: JapaneseChronology!
}
