// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import JavaLangIO
import SwiftJava

@JavaClass("java.time.LocalTime", implements: Temporal.self, TemporalAdjuster.self, Comparable<LocalTime>.self, Serializable.self)
open class LocalTime: JavaObject {
  /// Java method `get`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.get(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func get(_ arg0: TemporalField?) -> Int32

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.LocalTime.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.LocalTime.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.compareTo(java.lang.Object)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.compareTo(java.time.LocalTime)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: LocalTime?) -> Int32

  /// Java method `getLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.LocalTime.getLong(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func getLong(_ arg0: TemporalField?) -> Int64

  /// Java method `format`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.LocalTime.format(java.time.format.DateTimeFormatter)
  /// ```
@JavaMethod
  open func format(_ arg0: DateTimeFormatter?) -> String

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.LocalTime.isSupported(java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func isSupported(_ arg0: TemporalUnit?) -> Bool

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.LocalTime.isSupported(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func isSupported(_ arg0: TemporalField?) -> Bool

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.with(java.time.temporal.TemporalAdjuster)
  /// ```
@JavaMethod
  open func with(_ arg0: TemporalAdjuster?) -> LocalTime!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.LocalTime.with(java.time.temporal.TemporalAdjuster)
  /// ```
@JavaMethod
  open func with(_ arg0: TemporalAdjuster?) -> Temporal!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.with(java.time.temporal.TemporalField,long)
  /// ```
@JavaMethod
  open func with(_ arg0: TemporalField?, _ arg1: Int64) -> LocalTime!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.LocalTime.with(java.time.temporal.TemporalField,long)
  /// ```
@JavaMethod
  open func with(_ arg0: TemporalField?, _ arg1: Int64) -> Temporal!

  /// Java method `query`.
  ///
  /// ### Java method signature
  /// ```java
  /// public <R> R java.time.LocalTime.query(java.time.temporal.TemporalQuery<R>)
  /// ```
@JavaMethod(typeErasedResult: "R!")
  open func query<R: AnyJavaObject>(_ arg0: TemporalQuery<R>?) -> R!

  /// Java method `range`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.ValueRange java.time.LocalTime.range(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func range(_ arg0: TemporalField?) -> ValueRange!

  /// Java method `getNano`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.getNano()
  /// ```
@JavaMethod
  open func getNano() -> Int32

  /// Java method `getHour`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.getHour()
  /// ```
@JavaMethod
  open func getHour() -> Int32

  /// Java method `getMinute`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.getMinute()
  /// ```
@JavaMethod
  open func getMinute() -> Int32

  /// Java method `getSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.getSecond()
  /// ```
@JavaMethod
  open func getSecond() -> Int32

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.LocalTime.minus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func minus(_ arg0: Int64, _ arg1: TemporalUnit?) -> Temporal!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.minus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  open func minus(_ arg0: TemporalAmount?) -> LocalTime!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.minus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func minus(_ arg0: Int64, _ arg1: TemporalUnit?) -> LocalTime!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.LocalTime.minus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  open func minus(_ arg0: TemporalAmount?) -> Temporal!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.plus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  open func plus(_ arg0: TemporalAmount?) -> LocalTime!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.LocalTime.plus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  open func plus(_ arg0: TemporalAmount?) -> Temporal!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.LocalTime.plus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func plus(_ arg0: Int64, _ arg1: TemporalUnit?) -> Temporal!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.plus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func plus(_ arg0: Int64, _ arg1: TemporalUnit?) -> LocalTime!

  /// Java method `until`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.LocalTime.until(java.time.temporal.Temporal,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func until(_ arg0: Temporal?, _ arg1: TemporalUnit?) -> Int64

  /// Java method `plusNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.plusNanos(long)
  /// ```
@JavaMethod
  open func plusNanos(_ arg0: Int64) -> LocalTime!

  /// Java method `plusSeconds`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.plusSeconds(long)
  /// ```
@JavaMethod
  open func plusSeconds(_ arg0: Int64) -> LocalTime!

  /// Java method `plusHours`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.plusHours(long)
  /// ```
@JavaMethod
  open func plusHours(_ arg0: Int64) -> LocalTime!

  /// Java method `plusMinutes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.plusMinutes(long)
  /// ```
@JavaMethod
  open func plusMinutes(_ arg0: Int64) -> LocalTime!

  /// Java method `minusHours`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.minusHours(long)
  /// ```
@JavaMethod
  open func minusHours(_ arg0: Int64) -> LocalTime!

  /// Java method `minusMinutes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.minusMinutes(long)
  /// ```
@JavaMethod
  open func minusMinutes(_ arg0: Int64) -> LocalTime!

  /// Java method `minusSeconds`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.minusSeconds(long)
  /// ```
@JavaMethod
  open func minusSeconds(_ arg0: Int64) -> LocalTime!

  /// Java method `minusNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.minusNanos(long)
  /// ```
@JavaMethod
  open func minusNanos(_ arg0: Int64) -> LocalTime!

  /// Java method `truncatedTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.truncatedTo(java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func truncatedTo(_ arg0: TemporalUnit?) -> LocalTime!

  /// Java method `adjustInto`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.LocalTime.adjustInto(java.time.temporal.Temporal)
  /// ```
@JavaMethod
  open func adjustInto(_ arg0: Temporal?) -> Temporal!

  /// Java method `atOffset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetTime java.time.LocalTime.atOffset(java.time.ZoneOffset)
  /// ```
@JavaMethod
  open func atOffset(_ arg0: ZoneOffset?) -> OffsetTime!

  /// Java method `isAfter`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.LocalTime.isAfter(java.time.LocalTime)
  /// ```
@JavaMethod
  open func isAfter(_ arg0: LocalTime?) -> Bool

  /// Java method `isBefore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.LocalTime.isBefore(java.time.LocalTime)
  /// ```
@JavaMethod
  open func isBefore(_ arg0: LocalTime?) -> Bool

  /// Java method `toSecondOfDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.LocalTime.toSecondOfDay()
  /// ```
@JavaMethod
  open func toSecondOfDay() -> Int32

  /// Java method `toEpochSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.LocalTime.toEpochSecond(java.time.LocalDate,java.time.ZoneOffset)
  /// ```
@JavaMethod
  open func toEpochSecond(_ arg0: LocalDate?, _ arg1: ZoneOffset?) -> Int64

  /// Java method `withHour`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.withHour(int)
  /// ```
@JavaMethod
  open func withHour(_ arg0: Int32) -> LocalTime!

  /// Java method `withMinute`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.withMinute(int)
  /// ```
@JavaMethod
  open func withMinute(_ arg0: Int32) -> LocalTime!

  /// Java method `withSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.withSecond(int)
  /// ```
@JavaMethod
  open func withSecond(_ arg0: Int32) -> LocalTime!

  /// Java method `withNano`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.LocalTime.withNano(int)
  /// ```
@JavaMethod
  open func withNano(_ arg0: Int32) -> LocalTime!

  /// Java method `toNanoOfDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.LocalTime.toNanoOfDay()
  /// ```
@JavaMethod
  open func toNanoOfDay() -> Int64

  /// Java method `atDate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDateTime java.time.LocalTime.atDate(java.time.LocalDate)
  /// ```
@JavaMethod
  open func atDate(_ arg0: LocalDate?) -> LocalDateTime!
}
extension JavaClass<LocalTime> {
  @JavaStaticField(isFinal: true)
  public var MIN: LocalTime!

  @JavaStaticField(isFinal: true)
  public var MAX: LocalTime!

  @JavaStaticField(isFinal: true)
  public var MIDNIGHT: LocalTime!

  @JavaStaticField(isFinal: true)
  public var NOON: LocalTime!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.of(int,int,int)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> LocalTime!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.of(int,int,int,int)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> LocalTime!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.of(int,int)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: Int32, _ arg1: Int32) -> LocalTime!

    /// Java method `from`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.from(java.time.temporal.TemporalAccessor)
    /// ```
  @JavaStaticMethod
  public func from(_ arg0: TemporalAccessor?) -> LocalTime!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.parse(java.lang.CharSequence)
    /// ```
  @JavaStaticMethod
  public func parse(_ arg0: CharSequence?) -> LocalTime!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.parse(java.lang.CharSequence,java.time.format.DateTimeFormatter)
    /// ```
  @JavaStaticMethod
  public func parse(_ arg0: CharSequence?, _ arg1: DateTimeFormatter?) -> LocalTime!

    /// Java method `now`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.now()
    /// ```
  @JavaStaticMethod
  public func now() -> LocalTime!

    /// Java method `now`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.now(java.time.Clock)
    /// ```
  @JavaStaticMethod
  public func now(_ arg0: Clock?) -> LocalTime!

    /// Java method `now`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.now(java.time.ZoneId)
    /// ```
  @JavaStaticMethod
  public func now(_ arg0: ZoneId?) -> LocalTime!

    /// Java method `ofInstant`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.ofInstant(java.time.Instant,java.time.ZoneId)
    /// ```
  @JavaStaticMethod
  public func ofInstant(_ arg0: Instant?, _ arg1: ZoneId?) -> LocalTime!

    /// Java method `ofNanoOfDay`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.ofNanoOfDay(long)
    /// ```
  @JavaStaticMethod
  public func ofNanoOfDay(_ arg0: Int64) -> LocalTime!

    /// Java method `ofSecondOfDay`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.LocalTime java.time.LocalTime.ofSecondOfDay(long)
    /// ```
  @JavaStaticMethod
  public func ofSecondOfDay(_ arg0: Int64) -> LocalTime!
}
