// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.time.chrono.MinguoChronology", implements: Serializable.self)
open class MinguoChronology: AbstractChronology {
  /// Java method `getId`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.MinguoChronology.getId()
  /// ```
@JavaMethod
  open func getId() -> String

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.date(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func date(_ arg0: TemporalAccessor?) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.date(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func date(_ arg0: TemporalAccessor?) -> MinguoDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.date(java.time.chrono.Era,int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> MinguoDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.date(int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.date(java.time.chrono.Era,int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> ChronoLocalDate!

  /// Java method `date`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.date(int,int,int)
  /// ```
@JavaMethod
  open func date(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> MinguoDate!

  /// Java method `eras`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.util.List<java.time.chrono.Era> java.time.chrono.MinguoChronology.eras()
  /// ```
@JavaMethod
  open func eras() -> List<Era>!

  /// Java method `isLeapYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.chrono.MinguoChronology.isLeapYear(long)
  /// ```
@JavaMethod
  open func isLeapYear(_ arg0: Int64) -> Bool

  /// Java method `eraOf`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.Era java.time.chrono.MinguoChronology.eraOf(int)
  /// ```
@JavaMethod
  open func eraOf(_ arg0: Int32) -> Era!

  /// Java method `localDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDateTime<java.time.chrono.MinguoDate> java.time.chrono.MinguoChronology.localDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func localDateTime(_ arg0: TemporalAccessor?) -> ChronoLocalDateTime<MinguoDate>!

  /// Java method `getCalendarType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.chrono.MinguoChronology.getCalendarType()
  /// ```
@JavaMethod
  open func getCalendarType() -> String

  /// Java method `dateEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.dateEpochDay(long)
  /// ```
@JavaMethod
  open func dateEpochDay(_ arg0: Int64) -> MinguoDate!

  /// Java method `dateEpochDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.dateEpochDay(long)
  /// ```
@JavaMethod
  open func dateEpochDay(_ arg0: Int64) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.dateNow(java.time.Clock)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: Clock?) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.dateNow(java.time.ZoneId)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: ZoneId?) -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.dateNow()
  /// ```
@JavaMethod
  open func dateNow() -> MinguoDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.dateNow(java.time.Clock)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: Clock?) -> MinguoDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.dateNow()
  /// ```
@JavaMethod
  open func dateNow() -> ChronoLocalDate!

  /// Java method `dateNow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.dateNow(java.time.ZoneId)
  /// ```
@JavaMethod
  open func dateNow(_ arg0: ZoneId?) -> MinguoDate!

  /// Java method `prolepticYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.chrono.MinguoChronology.prolepticYear(java.time.chrono.Era,int)
  /// ```
@JavaMethod
  open func prolepticYear(_ arg0: Era?, _ arg1: Int32) -> Int32

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.dateYearDay(int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Int32, _ arg1: Int32) -> MinguoDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.dateYearDay(java.time.chrono.Era,int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32) -> ChronoLocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoLocalDate java.time.chrono.MinguoChronology.dateYearDay(int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Int32, _ arg1: Int32) -> ChronoLocalDate!

  /// Java method `dateYearDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.MinguoDate java.time.chrono.MinguoChronology.dateYearDay(java.time.chrono.Era,int,int)
  /// ```
@JavaMethod
  open func dateYearDay(_ arg0: Era?, _ arg1: Int32, _ arg2: Int32) -> MinguoDate!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoZonedDateTime<java.time.chrono.MinguoDate> java.time.chrono.MinguoChronology.zonedDateTime(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: TemporalAccessor?) -> ChronoZonedDateTime<MinguoDate>!

  /// Java method `zonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.chrono.ChronoZonedDateTime<java.time.chrono.MinguoDate> java.time.chrono.MinguoChronology.zonedDateTime(java.time.Instant,java.time.ZoneId)
  /// ```
@JavaMethod
  open func zonedDateTime(_ arg0: Instant?, _ arg1: ZoneId?) -> ChronoZonedDateTime<MinguoDate>!

  /// Java method `isIsoBased`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.chrono.MinguoChronology.isIsoBased()
  /// ```
@JavaMethod
  open func isIsoBased() -> Bool
}
extension JavaClass<MinguoChronology> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: MinguoChronology!
}
