// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import JavaLangIO
import SwiftJava

@JavaClass("java.time.OffsetDateTime", implements: Temporal.self, TemporalAdjuster.self,  Serializable.self)
open class OffsetDateTime: JavaObject {
  /// Java method `withOffsetSameLocal`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withOffsetSameLocal(java.time.ZoneOffset)
  /// ```
@JavaMethod
  open func withOffsetSameLocal(_ arg0: ZoneOffset?) -> OffsetDateTime!

  /// Java method `withOffsetSameInstant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withOffsetSameInstant(java.time.ZoneOffset)
  /// ```
@JavaMethod
  open func withOffsetSameInstant(_ arg0: ZoneOffset?) -> OffsetDateTime!

  /// Java method `atZoneSameInstant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.ZonedDateTime java.time.OffsetDateTime.atZoneSameInstant(java.time.ZoneId)
  /// ```
@JavaMethod
  open func atZoneSameInstant(_ arg0: ZoneId?) -> ZonedDateTime!

  /// Java method `atZoneSimilarLocal`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.ZonedDateTime java.time.OffsetDateTime.atZoneSimilarLocal(java.time.ZoneId)
  /// ```
@JavaMethod
  open func atZoneSimilarLocal(_ arg0: ZoneId?) -> ZonedDateTime!

  /// Java method `toOffsetTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetTime java.time.OffsetDateTime.toOffsetTime()
  /// ```
@JavaMethod
  open func toOffsetTime() -> OffsetTime!

  /// Java method `get`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.get(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func get(_ arg0: TemporalField?) -> Int32

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.OffsetDateTime.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.OffsetDateTime.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.compareTo(java.time.OffsetDateTime)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: OffsetDateTime?) -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.compareTo(java.lang.Object)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

  /// Java method `getLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.OffsetDateTime.getLong(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func getLong(_ arg0: TemporalField?) -> Int64

  /// Java method `format`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.OffsetDateTime.format(java.time.format.DateTimeFormatter)
  /// ```
@JavaMethod
  open func format(_ arg0: DateTimeFormatter?) -> String

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.OffsetDateTime.isSupported(java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func isSupported(_ arg0: TemporalUnit?) -> Bool

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.OffsetDateTime.isSupported(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func isSupported(_ arg0: TemporalField?) -> Bool

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.OffsetDateTime.with(java.time.temporal.TemporalField,long)
  /// ```
@JavaMethod
  open func with(_ arg0: TemporalField?, _ arg1: Int64) -> Temporal!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.with(java.time.temporal.TemporalAdjuster)
  /// ```
@JavaMethod
  open func with(_ arg0: TemporalAdjuster?) -> OffsetDateTime!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.with(java.time.temporal.TemporalField,long)
  /// ```
@JavaMethod
  open func with(_ arg0: TemporalField?, _ arg1: Int64) -> OffsetDateTime!

  /// Java method `with`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.OffsetDateTime.with(java.time.temporal.TemporalAdjuster)
  /// ```
@JavaMethod
  open func with(_ arg0: TemporalAdjuster?) -> Temporal!

  /// Java method `query`.
  ///
  /// ### Java method signature
  /// ```java
  /// public <R> R java.time.OffsetDateTime.query(java.time.temporal.TemporalQuery<R>)
  /// ```
@JavaMethod(typeErasedResult: "R!")
  open func query<R: AnyJavaObject>(_ arg0: TemporalQuery<R>?) -> R!

  /// Java method `getOffset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.ZoneOffset java.time.OffsetDateTime.getOffset()
  /// ```
@JavaMethod
  open func getOffset() -> ZoneOffset!

  /// Java method `range`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.ValueRange java.time.OffsetDateTime.range(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func range(_ arg0: TemporalField?) -> ValueRange!

  /// Java method `isEqual`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.OffsetDateTime.isEqual(java.time.OffsetDateTime)
  /// ```
@JavaMethod
  open func isEqual(_ arg0: OffsetDateTime?) -> Bool

  /// Java method `getNano`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.getNano()
  /// ```
@JavaMethod
  open func getNano() -> Int32

  /// Java method `toInstant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.Instant java.time.OffsetDateTime.toInstant()
  /// ```
@JavaMethod
  open func toInstant() -> Instant!

  /// Java method `getYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.getYear()
  /// ```
@JavaMethod
  open func getYear() -> Int32

  /// Java method `getMonthValue`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.getMonthValue()
  /// ```
@JavaMethod
  open func getMonthValue() -> Int32

  /// Java method `getDayOfMonth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.getDayOfMonth()
  /// ```
@JavaMethod
  open func getDayOfMonth() -> Int32

  /// Java method `getHour`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.getHour()
  /// ```
@JavaMethod
  open func getHour() -> Int32

  /// Java method `getMinute`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.getMinute()
  /// ```
@JavaMethod
  open func getMinute() -> Int32

  /// Java method `getSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.getSecond()
  /// ```
@JavaMethod
  open func getSecond() -> Int32

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func minus(_ arg0: Int64, _ arg1: TemporalUnit?) -> OffsetDateTime!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  open func minus(_ arg0: TemporalAmount?) -> OffsetDateTime!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.OffsetDateTime.minus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  open func minus(_ arg0: TemporalAmount?) -> Temporal!

  /// Java method `minus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.OffsetDateTime.minus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func minus(_ arg0: Int64, _ arg1: TemporalUnit?) -> Temporal!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.OffsetDateTime.plus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  open func plus(_ arg0: TemporalAmount?) -> Temporal!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.OffsetDateTime.plus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func plus(_ arg0: Int64, _ arg1: TemporalUnit?) -> Temporal!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plus(long,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func plus(_ arg0: Int64, _ arg1: TemporalUnit?) -> OffsetDateTime!

  /// Java method `plus`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plus(java.time.temporal.TemporalAmount)
  /// ```
@JavaMethod
  open func plus(_ arg0: TemporalAmount?) -> OffsetDateTime!

  /// Java method `until`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.OffsetDateTime.until(java.time.temporal.Temporal,java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func until(_ arg0: Temporal?, _ arg1: TemporalUnit?) -> Int64

  /// Java method `plusNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plusNanos(long)
  /// ```
@JavaMethod
  open func plusNanos(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `plusSeconds`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plusSeconds(long)
  /// ```
@JavaMethod
  open func plusSeconds(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `plusDays`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plusDays(long)
  /// ```
@JavaMethod
  open func plusDays(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `plusHours`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plusHours(long)
  /// ```
@JavaMethod
  open func plusHours(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `plusMinutes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plusMinutes(long)
  /// ```
@JavaMethod
  open func plusMinutes(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `minusDays`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minusDays(long)
  /// ```
@JavaMethod
  open func minusDays(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `minusHours`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minusHours(long)
  /// ```
@JavaMethod
  open func minusHours(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `minusMinutes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minusMinutes(long)
  /// ```
@JavaMethod
  open func minusMinutes(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `minusSeconds`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minusSeconds(long)
  /// ```
@JavaMethod
  open func minusSeconds(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `minusNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minusNanos(long)
  /// ```
@JavaMethod
  open func minusNanos(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `truncatedTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.truncatedTo(java.time.temporal.TemporalUnit)
  /// ```
@JavaMethod
  open func truncatedTo(_ arg0: TemporalUnit?) -> OffsetDateTime!

  /// Java method `adjustInto`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.OffsetDateTime.adjustInto(java.time.temporal.Temporal)
  /// ```
@JavaMethod
  open func adjustInto(_ arg0: Temporal?) -> Temporal!

  /// Java method `isAfter`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.OffsetDateTime.isAfter(java.time.OffsetDateTime)
  /// ```
@JavaMethod
  open func isAfter(_ arg0: OffsetDateTime?) -> Bool

  /// Java method `isBefore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.OffsetDateTime.isBefore(java.time.OffsetDateTime)
  /// ```
@JavaMethod
  open func isBefore(_ arg0: OffsetDateTime?) -> Bool

  /// Java method `getDayOfYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.OffsetDateTime.getDayOfYear()
  /// ```
@JavaMethod
  open func getDayOfYear() -> Int32

  /// Java method `withDayOfMonth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withDayOfMonth(int)
  /// ```
@JavaMethod
  open func withDayOfMonth(_ arg0: Int32) -> OffsetDateTime!

  /// Java method `withDayOfYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withDayOfYear(int)
  /// ```
@JavaMethod
  open func withDayOfYear(_ arg0: Int32) -> OffsetDateTime!

  /// Java method `plusWeeks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plusWeeks(long)
  /// ```
@JavaMethod
  open func plusWeeks(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `withMonth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withMonth(int)
  /// ```
@JavaMethod
  open func withMonth(_ arg0: Int32) -> OffsetDateTime!

  /// Java method `plusMonths`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plusMonths(long)
  /// ```
@JavaMethod
  open func plusMonths(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `withYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withYear(int)
  /// ```
@JavaMethod
  open func withYear(_ arg0: Int32) -> OffsetDateTime!

  /// Java method `plusYears`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.plusYears(long)
  /// ```
@JavaMethod
  open func plusYears(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `minusMonths`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minusMonths(long)
  /// ```
@JavaMethod
  open func minusMonths(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `toLocalTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalTime java.time.OffsetDateTime.toLocalTime()
  /// ```
@JavaMethod
  open func toLocalTime() -> LocalTime!

  /// Java method `minusYears`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minusYears(long)
  /// ```
@JavaMethod
  open func minusYears(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `minusWeeks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.minusWeeks(long)
  /// ```
@JavaMethod
  open func minusWeeks(_ arg0: Int64) -> OffsetDateTime!

  /// Java method `toEpochSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.OffsetDateTime.toEpochSecond()
  /// ```
@JavaMethod
  open func toEpochSecond() -> Int64

  /// Java method `toLocalDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDateTime java.time.OffsetDateTime.toLocalDateTime()
  /// ```
@JavaMethod
  open func toLocalDateTime() -> LocalDateTime!

  /// Java method `withHour`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withHour(int)
  /// ```
@JavaMethod
  open func withHour(_ arg0: Int32) -> OffsetDateTime!

  /// Java method `withMinute`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withMinute(int)
  /// ```
@JavaMethod
  open func withMinute(_ arg0: Int32) -> OffsetDateTime!

  /// Java method `withSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withSecond(int)
  /// ```
@JavaMethod
  open func withSecond(_ arg0: Int32) -> OffsetDateTime!

  /// Java method `withNano`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.OffsetDateTime java.time.OffsetDateTime.withNano(int)
  /// ```
@JavaMethod
  open func withNano(_ arg0: Int32) -> OffsetDateTime!

  /// Java method `toLocalDate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.LocalDate java.time.OffsetDateTime.toLocalDate()
  /// ```
@JavaMethod
  open func toLocalDate() -> LocalDate!

  /// Java method `toZonedDateTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.ZonedDateTime java.time.OffsetDateTime.toZonedDateTime()
  /// ```
@JavaMethod
  open func toZonedDateTime() -> ZonedDateTime!
}
extension JavaClass<OffsetDateTime> {
  @JavaStaticField(isFinal: true)
  public var MIN: OffsetDateTime!

  @JavaStaticField(isFinal: true)
  public var MAX: OffsetDateTime!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.of(java.time.LocalDateTime,java.time.ZoneOffset)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: LocalDateTime?, _ arg1: ZoneOffset?) -> OffsetDateTime!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.of(int,int,int,int,int,int,int,java.time.ZoneOffset)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, _ arg6: Int32, _ arg7: ZoneOffset?) -> OffsetDateTime!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.of(java.time.LocalDate,java.time.LocalTime,java.time.ZoneOffset)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: LocalDate?, _ arg1: LocalTime?, _ arg2: ZoneOffset?) -> OffsetDateTime!

    /// Java method `from`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.from(java.time.temporal.TemporalAccessor)
    /// ```
  @JavaStaticMethod
  public func from(_ arg0: TemporalAccessor?) -> OffsetDateTime!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.parse(java.lang.CharSequence,java.time.format.DateTimeFormatter)
    /// ```
  @JavaStaticMethod
  public func parse(_ arg0: CharSequence?, _ arg1: DateTimeFormatter?) -> OffsetDateTime!

    /// Java method `parse`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.parse(java.lang.CharSequence)
    /// ```
  @JavaStaticMethod
  public func parse(_ arg0: CharSequence?) -> OffsetDateTime!

    /// Java method `now`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.now()
    /// ```
  @JavaStaticMethod
  public func now() -> OffsetDateTime!

    /// Java method `now`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.now(java.time.Clock)
    /// ```
  @JavaStaticMethod
  public func now(_ arg0: Clock?) -> OffsetDateTime!

    /// Java method `now`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.now(java.time.ZoneId)
    /// ```
  @JavaStaticMethod
  public func now(_ arg0: ZoneId?) -> OffsetDateTime!

    /// Java method `ofInstant`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.OffsetDateTime java.time.OffsetDateTime.ofInstant(java.time.Instant,java.time.ZoneId)
    /// ```
  @JavaStaticMethod
  public func ofInstant(_ arg0: Instant?, _ arg1: ZoneId?) -> OffsetDateTime!
}
