// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.time.temporal.TemporalAdjusters")
open class TemporalAdjusters: JavaObject {

}
extension JavaClass<TemporalAdjusters> {
  /// Java method `firstDayOfMonth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.TemporalAdjuster java.time.temporal.TemporalAdjusters.firstDayOfMonth()
  /// ```
@JavaStaticMethod
  public func firstDayOfMonth() -> TemporalAdjuster!

  /// Java method `firstDayOfNextMonth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.TemporalAdjuster java.time.temporal.TemporalAdjusters.firstDayOfNextMonth()
  /// ```
@JavaStaticMethod
  public func firstDayOfNextMonth() -> TemporalAdjuster!

  /// Java method `lastDayOfYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.TemporalAdjuster java.time.temporal.TemporalAdjusters.lastDayOfYear()
  /// ```
@JavaStaticMethod
  public func lastDayOfYear() -> TemporalAdjuster!

  /// Java method `firstDayOfNextYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.TemporalAdjuster java.time.temporal.TemporalAdjusters.firstDayOfNextYear()
  /// ```
@JavaStaticMethod
  public func firstDayOfNextYear() -> TemporalAdjuster!

  /// Java method `firstDayOfYear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.TemporalAdjuster java.time.temporal.TemporalAdjusters.firstDayOfYear()
  /// ```
@JavaStaticMethod
  public func firstDayOfYear() -> TemporalAdjuster!

  /// Java method `lastDayOfMonth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.TemporalAdjuster java.time.temporal.TemporalAdjusters.lastDayOfMonth()
  /// ```
@JavaStaticMethod
  public func lastDayOfMonth() -> TemporalAdjuster!
}
