// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("java.time.temporal.TemporalQuery")
public struct TemporalQuery<R: AnyJavaObject> {
  @JavaMethod
  public func queryFrom(_ arg0: TemporalAccessor?) -> JavaObject!
}
