// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.time.temporal.TemporalField")
public struct TemporalField {
  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.time.temporal.TemporalField.toString()
  /// ```
@JavaMethod
  public func toString() -> String

  /// Java method `range`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.temporal.ValueRange java.time.temporal.TemporalField.range()
  /// ```
@JavaMethod
  public func range() -> ValueRange!

  /// Java method `isSupportedBy`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.time.temporal.TemporalField.isSupportedBy(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  public func isSupportedBy(_ arg0: TemporalAccessor?) -> Bool

  /// Java method `isTimeBased`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.time.temporal.TemporalField.isTimeBased()
  /// ```
@JavaMethod
  public func isTimeBased() -> Bool

  /// Java method `getFrom`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.time.temporal.TemporalField.getFrom(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  public func getFrom(_ arg0: TemporalAccessor?) -> Int64

  /// Java method `adjustInto`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract <R extends java.time.temporal.Temporal> R java.time.temporal.TemporalField.adjustInto(R,long)
  /// ```
@JavaMethod(typeErasedResult: "R!")
  public func adjustInto<R: AnyJavaObject>(_ arg0: R?, _ arg1: Int64) -> R!

  /// Java method `rangeRefinedBy`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.temporal.ValueRange java.time.temporal.TemporalField.rangeRefinedBy(java.time.temporal.TemporalAccessor)
  /// ```
@JavaMethod
  public func rangeRefinedBy(_ arg0: TemporalAccessor?) -> ValueRange!

  /// Java method `isDateBased`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.time.temporal.TemporalField.isDateBased()
  /// ```
@JavaMethod
  public func isDateBased() -> Bool

  /// Java method `getBaseUnit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.temporal.TemporalUnit java.time.temporal.TemporalField.getBaseUnit()
  /// ```
@JavaMethod
  public func getBaseUnit() -> TemporalUnit!

  /// Java method `getRangeUnit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.temporal.TemporalUnit java.time.temporal.TemporalField.getRangeUnit()
  /// ```
@JavaMethod
  public func getRangeUnit() -> TemporalUnit!
}
