// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.time.temporal.TemporalAccessor")
public struct TemporalAccessor {
  /// Java method `get`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int java.time.temporal.TemporalAccessor.get(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func get(_ arg0: TemporalField?) -> Int32

  /// Java method `getLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long java.time.temporal.TemporalAccessor.getLong(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func getLong(_ arg0: TemporalField?) -> Int64

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.time.temporal.TemporalAccessor.isSupported(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func isSupported(_ arg0: TemporalField?) -> Bool

  /// Java method `query`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default <R> R java.time.temporal.TemporalAccessor.query(java.time.temporal.TemporalQuery<R>)
  /// ```
@JavaMethod(typeErasedResult: "R!")
  public func query<R: AnyJavaObject>(_ arg0: TemporalQuery<R>?) -> R!

  /// Java method `range`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.time.temporal.ValueRange java.time.temporal.TemporalAccessor.range(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  public func range(_ arg0: TemporalField?) -> ValueRange!
}
