// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaInterface("java.time.temporal.TemporalAdjuster")
public struct TemporalAdjuster {
  @JavaMethod
  public func adjustInto(_ arg0: Temporal?) -> Temporal!
}
