// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import JavaLangIO
import SwiftJava

@JavaClass("java.time.temporal.ValueRange", implements: Serializable.self)
open class ValueRange: JavaObject {
  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.temporal.ValueRange.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.temporal.ValueRange.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.temporal.ValueRange.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `getMaximum`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.temporal.ValueRange.getMaximum()
  /// ```
@JavaMethod
  open func getMaximum() -> Int64

  /// Java method `checkValidIntValue`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.temporal.ValueRange.checkValidIntValue(long,java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func checkValidIntValue(_ arg0: Int64, _ arg1: TemporalField?) -> Int32

  /// Java method `checkValidValue`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.temporal.ValueRange.checkValidValue(long,java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func checkValidValue(_ arg0: Int64, _ arg1: TemporalField?) -> Int64

  /// Java method `isIntValue`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.temporal.ValueRange.isIntValue()
  /// ```
@JavaMethod
  open func isIntValue() -> Bool

  /// Java method `isValidValue`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.temporal.ValueRange.isValidValue(long)
  /// ```
@JavaMethod
  open func isValidValue(_ arg0: Int64) -> Bool

  /// Java method `getMinimum`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.temporal.ValueRange.getMinimum()
  /// ```
@JavaMethod
  open func getMinimum() -> Int64

  /// Java method `isValidIntValue`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.temporal.ValueRange.isValidIntValue(long)
  /// ```
@JavaMethod
  open func isValidIntValue(_ arg0: Int64) -> Bool

  /// Java method `isFixed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.temporal.ValueRange.isFixed()
  /// ```
@JavaMethod
  open func isFixed() -> Bool

  /// Java method `getLargestMinimum`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.temporal.ValueRange.getLargestMinimum()
  /// ```
@JavaMethod
  open func getLargestMinimum() -> Int64

  /// Java method `getSmallestMaximum`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.temporal.ValueRange.getSmallestMaximum()
  /// ```
@JavaMethod
  open func getSmallestMaximum() -> Int64
}
extension JavaClass<ValueRange> {
  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.ValueRange java.time.temporal.ValueRange.of(long,long)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: Int64, _ arg1: Int64) -> ValueRange!

  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.ValueRange java.time.temporal.ValueRange.of(long,long,long,long)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: Int64, _ arg1: Int64, _ arg2: Int64, _ arg3: Int64) -> ValueRange!

  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.temporal.ValueRange java.time.temporal.ValueRange.of(long,long,long)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: Int64, _ arg1: Int64, _ arg2: Int64) -> ValueRange!
}
