// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.time.ZoneId", implements: Serializable.self)
open class ZoneId: JavaObject {
  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.ZoneId.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.ZoneId.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.ZoneId.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `getId`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String java.time.ZoneId.getId()
  /// ```
@JavaMethod
  open func getId() -> String

  /// Java method `normalized`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.ZoneId java.time.ZoneId.normalized()
  /// ```
@JavaMethod
  open func normalized() -> ZoneId!

  /// Java method `getRules`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.time.zone.ZoneRules java.time.ZoneId.getRules()
  /// ```
@JavaMethod
  open func getRules() -> ZoneRules!
}
extension JavaClass<ZoneId> {
  /// Java method `of`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.ZoneId java.time.ZoneId.of(java.lang.String)
  /// ```
@JavaStaticMethod
  public func of(_ arg0: String) -> ZoneId!

  /// Java method `from`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.ZoneId java.time.ZoneId.from(java.time.temporal.TemporalAccessor)
  /// ```
@JavaStaticMethod
  public func from(_ arg0: TemporalAccessor?) -> ZoneId!

  /// Java method `systemDefault`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.ZoneId java.time.ZoneId.systemDefault()
  /// ```
@JavaStaticMethod
  public func systemDefault() -> ZoneId!

  /// Java method `getAvailableZoneIds`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.util.Set<java.lang.String> java.time.ZoneId.getAvailableZoneIds()
  /// ```
@JavaStaticMethod
  public func getAvailableZoneIds() -> JavaSet<JavaString>!

  /// Java method `ofOffset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.time.ZoneId java.time.ZoneId.ofOffset(java.lang.String,java.time.ZoneOffset)
  /// ```
@JavaStaticMethod
  public func ofOffset(_ arg0: String, _ arg1: ZoneOffset?) -> ZoneId!
}
