// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLang
import JavaLangIO
import SwiftJava

@JavaClass("java.time.ZoneOffset", implements: TemporalAccessor.self, TemporalAdjuster.self,  Serializable.self)
open class ZoneOffset: ZoneId {
  /// Java method `get`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.ZoneOffset.get(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func get(_ arg0: TemporalField?) -> Int32

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.ZoneOffset.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.ZoneOffset.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.ZoneOffset.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.ZoneOffset.compareTo(java.time.ZoneOffset)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: ZoneOffset?) -> Int32

  /// Java method `compareTo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.ZoneOffset.compareTo(java.lang.Object)
  /// ```
@JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

  /// Java method `getLong`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long java.time.ZoneOffset.getLong(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func getLong(_ arg0: TemporalField?) -> Int64

  /// Java method `isSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.time.ZoneOffset.isSupported(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func isSupported(_ arg0: TemporalField?) -> Bool

  /// Java method `getId`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.time.ZoneOffset.getId()
  /// ```
@JavaMethod
  open override func getId() -> String

  /// Java method `query`.
  ///
  /// ### Java method signature
  /// ```java
  /// public <R> R java.time.ZoneOffset.query(java.time.temporal.TemporalQuery<R>)
  /// ```
@JavaMethod(typeErasedResult: "R!")
  open func query<R: AnyJavaObject>(_ arg0: TemporalQuery<R>?) -> R!

  /// Java method `range`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.ValueRange java.time.ZoneOffset.range(java.time.temporal.TemporalField)
  /// ```
@JavaMethod
  open func range(_ arg0: TemporalField?) -> ValueRange!

  /// Java method `normalized`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.ZoneId java.time.ZoneOffset.normalized()
  /// ```
@JavaMethod
  open override func normalized() -> ZoneId!

  /// Java method `adjustInto`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.temporal.Temporal java.time.ZoneOffset.adjustInto(java.time.temporal.Temporal)
  /// ```
@JavaMethod
  open func adjustInto(_ arg0: Temporal?) -> Temporal!

  /// Java method `getRules`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.time.zone.ZoneRules java.time.ZoneOffset.getRules()
  /// ```
@JavaMethod
  open override func getRules() -> ZoneRules!

  /// Java method `getTotalSeconds`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.time.ZoneOffset.getTotalSeconds()
  /// ```
@JavaMethod
  open func getTotalSeconds() -> Int32
}
extension JavaClass<ZoneOffset> {
  @JavaStaticField(isFinal: true)
  public var UTC: ZoneOffset!

  @JavaStaticField(isFinal: true)
  public var MIN: ZoneOffset!

  @JavaStaticField(isFinal: true)
  public var MAX: ZoneOffset!

    /// Java method `of`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.ZoneOffset java.time.ZoneOffset.of(java.lang.String)
    /// ```
  @JavaStaticMethod
  public func of(_ arg0: String) -> ZoneOffset!

    /// Java method `from`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.ZoneOffset java.time.ZoneOffset.from(java.time.temporal.TemporalAccessor)
    /// ```
  @JavaStaticMethod
  public func from(_ arg0: TemporalAccessor?) -> ZoneOffset!

    /// Java method `ofHours`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.ZoneOffset java.time.ZoneOffset.ofHours(int)
    /// ```
  @JavaStaticMethod
  public func ofHours(_ arg0: Int32) -> ZoneOffset!

    /// Java method `ofHoursMinutesSeconds`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.ZoneOffset java.time.ZoneOffset.ofHoursMinutesSeconds(int,int,int)
    /// ```
  @JavaStaticMethod
  public func ofHoursMinutesSeconds(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> ZoneOffset!

    /// Java method `ofTotalSeconds`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.ZoneOffset java.time.ZoneOffset.ofTotalSeconds(int)
    /// ```
  @JavaStaticMethod
  public func ofTotalSeconds(_ arg0: Int32) -> ZoneOffset!

    /// Java method `ofHoursMinutes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.time.ZoneOffset java.time.ZoneOffset.ofHoursMinutes(int,int)
    /// ```
  @JavaStaticMethod
  public func ofHoursMinutes(_ arg0: Int32, _ arg1: Int32) -> ZoneOffset!
}
