// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.math.MathContext", implements: Serializable.self)
open class MathContext: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

    /// Java method `getPrecision`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.math.MathContext.getPrecision()
    /// ```
  @JavaMethod
  open func getPrecision() -> Int32

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.math.MathContext.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.math.MathContext.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.math.MathContext.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<MathContext> {
  @JavaStaticField(isFinal: true)
  public var UNLIMITED: MathContext!

  @JavaStaticField(isFinal: true)
  public var DECIMAL32: MathContext!

  @JavaStaticField(isFinal: true)
  public var DECIMAL64: MathContext!

  @JavaStaticField(isFinal: true)
  public var DECIMAL128: MathContext!
}
