// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.awt.font.NumericShaper", implements: Serializable.self)
open class NumericShaper: JavaObject {
  /// Java method `isContextual`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.awt.font.NumericShaper.isContextual()
  /// ```
@JavaMethod
  open func isContextual() -> Bool

  /// Java method `getRanges`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.awt.font.NumericShaper.getRanges()
  /// ```
@JavaMethod
  open func getRanges() -> Int32

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean java.awt.font.NumericShaper.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String java.awt.font.NumericShaper.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int java.awt.font.NumericShaper.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32

  /// Java method `shape`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.awt.font.NumericShaper.shape(char[],int,int,int)
  /// ```
@JavaMethod
  open func shape(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  /// Java method `shape`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.awt.font.NumericShaper.shape(char[],int,int)
  /// ```
@JavaMethod
  open func shape(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32)
}
extension JavaClass<NumericShaper> {
  @JavaStaticField(isFinal: true)
  public var EUROPEAN: Int32

  @JavaStaticField(isFinal: true)
  public var ARABIC: Int32

  @JavaStaticField(isFinal: true)
  public var EASTERN_ARABIC: Int32

  @JavaStaticField(isFinal: true)
  public var DEVANAGARI: Int32

  @JavaStaticField(isFinal: true)
  public var BENGALI: Int32

  @JavaStaticField(isFinal: true)
  public var GURMUKHI: Int32

  @JavaStaticField(isFinal: true)
  public var GUJARATI: Int32

  @JavaStaticField(isFinal: true)
  public var ORIYA: Int32

  @JavaStaticField(isFinal: true)
  public var TAMIL: Int32

  @JavaStaticField(isFinal: true)
  public var TELUGU: Int32

  @JavaStaticField(isFinal: true)
  public var KANNADA: Int32

  @JavaStaticField(isFinal: true)
  public var MALAYALAM: Int32

  @JavaStaticField(isFinal: true)
  public var THAI: Int32

  @JavaStaticField(isFinal: true)
  public var LAO: Int32

  @JavaStaticField(isFinal: true)
  public var TIBETAN: Int32

  @JavaStaticField(isFinal: true)
  public var MYANMAR: Int32

  @JavaStaticField(isFinal: true)
  public var ETHIOPIC: Int32

  @JavaStaticField(isFinal: true)
  public var KHMER: Int32

  @JavaStaticField(isFinal: true)
  public var MONGOLIAN: Int32

  @JavaStaticField(isFinal: true)
  public var ALL_RANGES: Int32

    /// Java method `getShaper`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.awt.font.NumericShaper java.awt.font.NumericShaper.getShaper(int)
    /// ```
  @JavaStaticMethod
  public func getShaper(_ arg0: Int32) -> NumericShaper!

    /// Java method `getContextualShaper`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.awt.font.NumericShaper java.awt.font.NumericShaper.getContextualShaper(int)
    /// ```
  @JavaStaticMethod
  public func getContextualShaper(_ arg0: Int32) -> NumericShaper!

    /// Java method `getContextualShaper`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.awt.font.NumericShaper java.awt.font.NumericShaper.getContextualShaper(int,int)
    /// ```
  @JavaStaticMethod
  public func getContextualShaper(_ arg0: Int32, _ arg1: Int32) -> NumericShaper!
}
