// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.net.Authenticator")
open class Authenticator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `getPasswordAuthentication`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.net.PasswordAuthentication java.net.Authenticator.getPasswordAuthentication()
    /// ```
  @JavaMethod
  open func getPasswordAuthentication() -> PasswordAuthentication!

    /// Java method `getRequestingHost`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected final java.lang.String java.net.Authenticator.getRequestingHost()
    /// ```
  @JavaMethod
  open func getRequestingHost() -> String

    /// Java method `getRequestingSite`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected final java.net.InetAddress java.net.Authenticator.getRequestingSite()
    /// ```
  @JavaMethod
  open func getRequestingSite() -> InetAddress!

    /// Java method `getRequestingPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected final int java.net.Authenticator.getRequestingPort()
    /// ```
  @JavaMethod
  open func getRequestingPort() -> Int32

    /// Java method `getRequestingProtocol`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected final java.lang.String java.net.Authenticator.getRequestingProtocol()
    /// ```
  @JavaMethod
  open func getRequestingProtocol() -> String

    /// Java method `getRequestingPrompt`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected final java.lang.String java.net.Authenticator.getRequestingPrompt()
    /// ```
  @JavaMethod
  open func getRequestingPrompt() -> String

    /// Java method `getRequestingScheme`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected final java.lang.String java.net.Authenticator.getRequestingScheme()
    /// ```
  @JavaMethod
  open func getRequestingScheme() -> String
}
extension JavaClass<Authenticator> {
  /// Java method `requestPasswordAuthentication`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.net.PasswordAuthentication java.net.Authenticator.requestPasswordAuthentication(java.net.InetAddress,int,java.lang.String,java.lang.String,java.lang.String)
  /// ```
@JavaStaticMethod
  public func requestPasswordAuthentication(_ arg0: InetAddress?, _ arg1: Int32, _ arg2: String, _ arg3: String, _ arg4: String) -> PasswordAuthentication!

  /// Java method `requestPasswordAuthentication`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.net.PasswordAuthentication java.net.Authenticator.requestPasswordAuthentication(java.lang.String,java.net.InetAddress,int,java.lang.String,java.lang.String,java.lang.String)
  /// ```
@JavaStaticMethod
  public func requestPasswordAuthentication(_ arg0: String, _ arg1: InetAddress?, _ arg2: Int32, _ arg3: String, _ arg4: String, _ arg5: String) -> PasswordAuthentication!

  /// Java method `getDefault`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.net.Authenticator java.net.Authenticator.getDefault()
  /// ```
@JavaStaticMethod
  public func getDefault() -> Authenticator!

  /// Java method `setDefault`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static synchronized void java.net.Authenticator.setDefault(java.net.Authenticator)
  /// ```
@JavaStaticMethod
  public func setDefault(_ arg0: Authenticator?)
}
