// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.net.CacheResponse")
open class CacheResponse: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `getBody`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.io.InputStream java.net.CacheResponse.getBody() throws java.io.IOException
    /// ```
  @JavaMethod
  open func getBody() throws -> InputStream!
}
