// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("java.net.ContentHandlerFactory")
public struct ContentHandlerFactory {
  @JavaMethod
  public func createContentHandler(_ arg0: String) -> ContentHandler!
}
