// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.net.ContentHandlerFactory")
public struct ContentHandlerFactory {
  /// Java method `createContentHandler`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.net.ContentHandler java.net.ContentHandlerFactory.createContentHandler(java.lang.String)
  /// ```
@JavaMethod
  public func createContentHandler(_ arg0: String) -> ContentHandler!
}
