// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.net.CookieStore")
public struct CookieStore {
  /// Java method `getCookies`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.util.List<java.net.HttpCookie> java.net.CookieStore.getCookies()
  /// ```
@JavaMethod
  public func getCookies() -> List<HttpCookie>!

  /// Java method `removeAll`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean java.net.CookieStore.removeAll()
  /// ```
@JavaMethod
  public func removeAll() -> Bool
}
