// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.net.CookiePolicy")
public struct CookiePolicy {

}
extension JavaClass<CookiePolicy> {
  @JavaStaticField(isFinal: true)
  public var ACCEPT_ALL: CookiePolicy!

  @JavaStaticField(isFinal: true)
  public var ACCEPT_NONE: CookiePolicy!

  @JavaStaticField(isFinal: true)
  public var ACCEPT_ORIGINAL_SERVER: CookiePolicy!
}
