// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.net.CookieHandler")
open class CookieHandler: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<CookieHandler> {
  /// Java method `getDefault`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static synchronized java.net.CookieHandler java.net.CookieHandler.getDefault()
  /// ```
@JavaStaticMethod
  public func getDefault() -> CookieHandler!

  /// Java method `setDefault`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static synchronized void java.net.CookieHandler.setDefault(java.net.CookieHandler)
  /// ```
@JavaStaticMethod
  public func setDefault(_ arg0: CookieHandler?)
}
