// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import JavaIO
import SwiftJava

@JavaClass("java.net.DatagramSocketImpl", implements: SocketOptions.self)
open class DatagramSocketImpl: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `connect`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void java.net.DatagramSocketImpl.connect(java.net.InetAddress,int) throws java.net.SocketException
    /// ```
  @JavaMethod
  open func connect(_ arg0: InetAddress?, _ arg1: Int32) throws

    /// Java method `send`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.send(java.net.DatagramPacket) throws java.io.IOException
    /// ```
  @JavaMethod
  open func send(_ arg0: DatagramPacket?) throws

    /// Java method `disconnect`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void java.net.DatagramSocketImpl.disconnect()
    /// ```
  @JavaMethod
  open func disconnect()

    /// Java method `peekData`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract int java.net.DatagramSocketImpl.peekData(java.net.DatagramPacket) throws java.io.IOException
    /// ```
  @JavaMethod
  open func peekData(_ arg0: DatagramPacket?) throws -> Int32

    /// Java method `receive`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.receive(java.net.DatagramPacket) throws java.io.IOException
    /// ```
  @JavaMethod
  open func receive(_ arg0: DatagramPacket?) throws

    /// Java method `setTTL`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.setTTL(byte) throws java.io.IOException
    /// ```
  @JavaMethod
  open func setTTL(_ arg0: Int8) throws

    /// Java method `getTTL`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract byte java.net.DatagramSocketImpl.getTTL() throws java.io.IOException
    /// ```
  @JavaMethod
  open func getTTL() throws -> Int8

    /// Java method `setTimeToLive`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.setTimeToLive(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func setTimeToLive(_ arg0: Int32) throws

    /// Java method `leave`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.leave(java.net.InetAddress) throws java.io.IOException
    /// ```
  @JavaMethod
  open func leave(_ arg0: InetAddress?) throws

    /// Java method `joinGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.joinGroup(java.net.SocketAddress,java.net.NetworkInterface) throws java.io.IOException
    /// ```
  @JavaMethod
  open func joinGroup(_ arg0: SocketAddress?, _ arg1: NetworkInterface?) throws

    /// Java method `leaveGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.leaveGroup(java.net.SocketAddress,java.net.NetworkInterface) throws java.io.IOException
    /// ```
  @JavaMethod
  open func leaveGroup(_ arg0: SocketAddress?, _ arg1: NetworkInterface?) throws

    /// Java method `getLocalPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected int java.net.DatagramSocketImpl.getLocalPort()
    /// ```
  @JavaMethod
  open func getLocalPort() -> Int32

    /// Java method `getFileDescriptor`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.io.FileDescriptor java.net.DatagramSocketImpl.getFileDescriptor()
    /// ```
  @JavaMethod
  open func getFileDescriptor() -> FileDescriptor!

    /// Java method `setOption`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected <T> void java.net.DatagramSocketImpl.setOption(java.net.SocketOption<T>,T) throws java.io.IOException
    /// ```
  @JavaMethod
  open func setOption<T: AnyJavaObject>(_ arg0: SocketOption<T>?, _ arg1: T?) throws

    /// Java method `getOption`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected <T> T java.net.DatagramSocketImpl.getOption(java.net.SocketOption<T>) throws java.io.IOException
    /// ```
  @JavaMethod(typeErasedResult: "T!")
  open func getOption<T: AnyJavaObject>(_ arg0: SocketOption<T>?) throws -> T!

    /// Java method `supportedOptions`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.util.Set<java.net.SocketOption<?>> java.net.DatagramSocketImpl.supportedOptions()
    /// ```
  @JavaMethod
  open func supportedOptions() -> JavaSet<SocketOption<JavaObject>>!

    /// Java method `join`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.join(java.net.InetAddress) throws java.io.IOException
    /// ```
  @JavaMethod
  open func join(_ arg0: InetAddress?) throws

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.close()
    /// ```
  @JavaMethod
  open func close()

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.create() throws java.net.SocketException
    /// ```
  @JavaMethod
  open func create() throws

    /// Java method `peek`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract int java.net.DatagramSocketImpl.peek(java.net.InetAddress) throws java.io.IOException
    /// ```
  @JavaMethod
  open func peek(_ arg0: InetAddress?) throws -> Int32

    /// Java method `bind`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.DatagramSocketImpl.bind(int,java.net.InetAddress) throws java.net.SocketException
    /// ```
  @JavaMethod
  open func bind(_ arg0: Int32, _ arg1: InetAddress?) throws

    /// Java method `getTimeToLive`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract int java.net.DatagramSocketImpl.getTimeToLive() throws java.io.IOException
    /// ```
  @JavaMethod
  open func getTimeToLive() throws -> Int32
}
