// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("java.net.DatagramSocketImplFactory")
public struct DatagramSocketImplFactory {
  @JavaMethod
  public func createDatagramSocketImpl() -> DatagramSocketImpl!
}
