// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.net.InetSocketAddress")
open class InetSocketAddress: SocketAddress {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: InetAddress?, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: Int32, environment: JNIEnvironment? = nil)

    /// Java method `getHostString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.net.InetSocketAddress.getHostString()
    /// ```
  @JavaMethod
  open func getHostString() -> String

    /// Java method `isUnresolved`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean java.net.InetSocketAddress.isUnresolved()
    /// ```
  @JavaMethod
  open func isUnresolved() -> Bool

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final boolean java.net.InetSocketAddress.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.net.InetSocketAddress.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int java.net.InetSocketAddress.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `getAddress`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.net.InetAddress java.net.InetSocketAddress.getAddress()
    /// ```
  @JavaMethod
  open func getAddress() -> InetAddress!

    /// Java method `getPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final int java.net.InetSocketAddress.getPort()
    /// ```
  @JavaMethod
  open func getPort() -> Int32

    /// Java method `getHostName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public final java.lang.String java.net.InetSocketAddress.getHostName()
    /// ```
  @JavaMethod
  open func getHostName() -> String
}
extension JavaClass<InetSocketAddress> {
  /// Java method `createUnresolved`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.net.InetSocketAddress java.net.InetSocketAddress.createUnresolved(java.lang.String,int)
  /// ```
@JavaStaticMethod
  public func createUnresolved(_ arg0: String, _ arg1: Int32) -> InetSocketAddress!
}
