// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.net.MulticastSocket")
open class MulticastSocket: DatagramSocket {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: SocketAddress?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil) throws

    /// Java method `send`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.send(java.net.DatagramPacket,byte) throws java.io.IOException
    /// ```
  @JavaMethod
  open func send(_ arg0: DatagramPacket?, _ arg1: Int8) throws

    /// Java method `setTTL`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.setTTL(byte) throws java.io.IOException
    /// ```
  @JavaMethod
  open func setTTL(_ arg0: Int8) throws

    /// Java method `getTTL`.
    ///
    /// ### Java method signature
    /// ```java
    /// public byte java.net.MulticastSocket.getTTL() throws java.io.IOException
    /// ```
  @JavaMethod
  open func getTTL() throws -> Int8

    /// Java method `setTimeToLive`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.setTimeToLive(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func setTimeToLive(_ arg0: Int32) throws

    /// Java method `joinGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.joinGroup(java.net.InetAddress) throws java.io.IOException
    /// ```
  @JavaMethod
  open func joinGroup(_ arg0: InetAddress?) throws

    /// Java method `joinGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.joinGroup(java.net.SocketAddress,java.net.NetworkInterface) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func joinGroup(_ arg0: SocketAddress?, _ arg1: NetworkInterface?) throws

    /// Java method `leaveGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.leaveGroup(java.net.SocketAddress,java.net.NetworkInterface) throws java.io.IOException
    /// ```
  @JavaMethod
  open override func leaveGroup(_ arg0: SocketAddress?, _ arg1: NetworkInterface?) throws

    /// Java method `leaveGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.leaveGroup(java.net.InetAddress) throws java.io.IOException
    /// ```
  @JavaMethod
  open func leaveGroup(_ arg0: InetAddress?) throws

    /// Java method `setInterface`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.setInterface(java.net.InetAddress) throws java.net.SocketException
    /// ```
  @JavaMethod
  open func setInterface(_ arg0: InetAddress?) throws

    /// Java method `getInterface`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.net.InetAddress java.net.MulticastSocket.getInterface() throws java.net.SocketException
    /// ```
  @JavaMethod
  open func getInterface() throws -> InetAddress!

    /// Java method `setNetworkInterface`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.setNetworkInterface(java.net.NetworkInterface) throws java.net.SocketException
    /// ```
  @JavaMethod
  open func setNetworkInterface(_ arg0: NetworkInterface?) throws

    /// Java method `getNetworkInterface`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.net.NetworkInterface java.net.MulticastSocket.getNetworkInterface() throws java.net.SocketException
    /// ```
  @JavaMethod
  open func getNetworkInterface() throws -> NetworkInterface!

    /// Java method `setLoopbackMode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void java.net.MulticastSocket.setLoopbackMode(boolean) throws java.net.SocketException
    /// ```
  @JavaMethod
  open func setLoopbackMode(_ arg0: Bool) throws

    /// Java method `getLoopbackMode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.net.MulticastSocket.getLoopbackMode() throws java.net.SocketException
    /// ```
  @JavaMethod
  open func getLoopbackMode() throws -> Bool

    /// Java method `getTimeToLive`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.net.MulticastSocket.getTimeToLive() throws java.io.IOException
    /// ```
  @JavaMethod
  open func getTimeToLive() throws -> Int32
}
