// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("java.net.ProtocolFamily")
public struct ProtocolFamily {
  @JavaMethod
  public func name() -> String
}
