// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.net.SecureCacheResponse")
open class SecureCacheResponse: CacheResponse {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `getCipherSuite`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract java.lang.String java.net.SecureCacheResponse.getCipherSuite()
    /// ```
  @JavaMethod
  open func getCipherSuite() -> String
}
