// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaLangIO
import SwiftJava

@JavaClass("java.net.SocketImpl", implements: SocketOptions.self)
open class SocketImpl: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `connect`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.connect(java.lang.String,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func connect(_ arg0: String, _ arg1: Int32) throws

    /// Java method `connect`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.connect(java.net.InetAddress,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func connect(_ arg0: InetAddress?, _ arg1: Int32) throws

    /// Java method `connect`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.connect(java.net.SocketAddress,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func connect(_ arg0: SocketAddress?, _ arg1: Int32) throws

    /// Java method `getOutputStream`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract java.io.OutputStream java.net.SocketImpl.getOutputStream() throws java.io.IOException
    /// ```
  @JavaMethod
  open func getOutputStream() throws -> OutputStream!

    /// Java method `getInetAddress`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.net.InetAddress java.net.SocketImpl.getInetAddress()
    /// ```
  @JavaMethod
  open func getInetAddress() -> InetAddress!

    /// Java method `getLocalPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected int java.net.SocketImpl.getLocalPort()
    /// ```
  @JavaMethod
  open func getLocalPort() -> Int32

    /// Java method `getOption`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected <T> T java.net.SocketImpl.getOption(java.net.SocketOption<T>) throws java.io.IOException
    /// ```
  @JavaMethod(typeErasedResult: "T!")
  open func getOption<T: AnyJavaObject>(_ arg0: SocketOption<T>?) throws -> T!

    /// Java method `setOption`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected <T> void java.net.SocketImpl.setOption(java.net.SocketOption<T>,T) throws java.io.IOException
    /// ```
  @JavaMethod
  open func setOption<T: AnyJavaObject>(_ arg0: SocketOption<T>?, _ arg1: T?) throws

    /// Java method `listen`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.listen(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func listen(_ arg0: Int32) throws

    /// Java method `shutdownInput`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void java.net.SocketImpl.shutdownInput() throws java.io.IOException
    /// ```
  @JavaMethod
  open func shutdownInput() throws

    /// Java method `shutdownOutput`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void java.net.SocketImpl.shutdownOutput() throws java.io.IOException
    /// ```
  @JavaMethod
  open func shutdownOutput() throws

    /// Java method `getFileDescriptor`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.io.FileDescriptor java.net.SocketImpl.getFileDescriptor()
    /// ```
  @JavaMethod
  open func getFileDescriptor() -> FileDescriptor!

    /// Java method `supportsUrgentData`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected boolean java.net.SocketImpl.supportsUrgentData()
    /// ```
  @JavaMethod
  open func supportsUrgentData() -> Bool

    /// Java method `sendUrgentData`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.sendUrgentData(int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func sendUrgentData(_ arg0: Int32) throws

    /// Java method `setPerformancePreferences`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void java.net.SocketImpl.setPerformancePreferences(int,int,int)
    /// ```
  @JavaMethod
  open func setPerformancePreferences(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32)

    /// Java method `supportedOptions`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected java.util.Set<java.net.SocketOption<?>> java.net.SocketImpl.supportedOptions()
    /// ```
  @JavaMethod
  open func supportedOptions() -> JavaSet<SocketOption<JavaObject>>!

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.net.SocketImpl.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `accept`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.accept(java.net.SocketImpl) throws java.io.IOException
    /// ```
  @JavaMethod
  open func accept(_ arg0: SocketImpl?) throws

    /// Java method `close`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.close() throws java.io.IOException
    /// ```
  @JavaMethod
  open func close() throws

    /// Java method `create`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.create(boolean) throws java.io.IOException
    /// ```
  @JavaMethod
  open func create(_ arg0: Bool) throws

    /// Java method `available`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract int java.net.SocketImpl.available() throws java.io.IOException
    /// ```
  @JavaMethod
  open func available() throws -> Int32

    /// Java method `getPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected int java.net.SocketImpl.getPort()
    /// ```
  @JavaMethod
  open func getPort() -> Int32

    /// Java method `getInputStream`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract java.io.InputStream java.net.SocketImpl.getInputStream() throws java.io.IOException
    /// ```
  @JavaMethod
  open func getInputStream() throws -> InputStream!

    /// Java method `bind`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected abstract void java.net.SocketImpl.bind(java.net.InetAddress,int) throws java.io.IOException
    /// ```
  @JavaMethod
  open func bind(_ arg0: InetAddress?, _ arg1: Int32) throws
}
