// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava

@JavaInterface("java.net.SocketImplFactory")
public struct SocketImplFactory {
  @JavaMethod
  public func createSocketImpl() -> SocketImpl!
}
