// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import SwiftJava
import CSwiftJavaJNI

@JavaClass("java.net.SocketAddress", implements: Serializable.self)
open class SocketAddress: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
