// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import JavaIO
import SwiftJava

@JavaClass("java.net.SocketPermission", implements: Serializable.self)
open class SocketPermission: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.net.SocketPermission.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.net.SocketPermission.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `getActions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.net.SocketPermission.getActions()
    /// ```
  @JavaMethod
  open func getActions() -> String
}
