// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaInterface("java.net.SocketImplFactory")
public struct SocketImplFactory {
  /// Java method `createSocketImpl`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.net.SocketImpl java.net.SocketImplFactory.createSocketImpl()
  /// ```
@JavaMethod
  public func createSocketImpl() -> SocketImpl!
}
