// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.net.URISyntaxException")
open class URISyntaxException: Exception {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)

    /// Java method `getMessage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.net.URISyntaxException.getMessage()
    /// ```
  @JavaMethod
  open override func getMessage() -> String

    /// Java method `getIndex`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.net.URISyntaxException.getIndex()
    /// ```
  @JavaMethod
  open func getIndex() -> Int32

    /// Java method `getReason`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.net.URISyntaxException.getReason()
    /// ```
  @JavaMethod
  open func getReason() -> String

    /// Java method `getInput`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.net.URISyntaxException.getInput()
    /// ```
  @JavaMethod
  open func getInput() -> String
}
