// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.net.URLDecoder")
open class URLDecoder: JavaObject {

}
extension JavaClass<URLDecoder> {
  /// Java method `decode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String java.net.URLDecoder.decode(java.lang.String,java.nio.charset.Charset)
  /// ```
@JavaStaticMethod
  public func decode(_ arg0: String, _ arg1: Charset?) -> String

  /// Java method `decode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String java.net.URLDecoder.decode(java.lang.String,java.lang.String) throws java.io.UnsupportedEncodingException
  /// ```
@JavaStaticMethod
  public func decode(_ arg0: String, _ arg1: String) throws -> String

  /// Java method `decode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String java.net.URLDecoder.decode(java.lang.String)
  /// ```
@JavaStaticMethod
  public func decode(_ arg0: String) -> String
}
