// Auto-generated by Java-to-Swift wrapper generator.
import CSwiftJavaJNI
import SwiftJava

@JavaClass("java.net.URLStreamHandler")
open class URLStreamHandler: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `getDefaultPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected int java.net.URLStreamHandler.getDefaultPort()
    /// ```
  @JavaMethod
  open func getDefaultPort() -> Int32
}
